### ISSUE TITLE
cli_wallet hang after http rpc call

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#1]
Steps:
1. cli_wallet -r
2. curl -v --data '{"jsonrpc": "2.0", "method": "info", "params": [], "id": 1}' http://localhost:8091/rpc

Logs:
- cli_wallet

```
locked >>> here...
2585869ms th_a       main.cpp:170                  operator()           ] .
```
- curl

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8091 (#0)
> POST /rpc HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8091
> Accept: */*
> Content-Length: 59
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 59 out of 59 bytes
```

By the way, if give in a wrong method, curl will receive an error, but the wallet won't die.

**Comment by theoreticalbts** [comment]
I apologize for the lack of documentation.  By stepping through the code, the correct curl syntax seems to be

```
curl -v --data '{"jsonrpc": "2.0", "method": "call", "params": [0, "info", []], "id": 1}' http://localhost:8091/rpc
```

The first argument is an API identifier, the second is a method name on that API, and the third is the arguments to the API.  The API identifier is determined by `register_api()` call order on the connection object.  We are planning to have several different API's, some of which will require authentication to access.

This results in calling the correct method, which you can verify by setting a breakpoint in `info()` method in `wallet.cpp`.  However it hangs on the `get_global_properties()` call for some reason.  I'll continue the investigation, this ticket should remain open until we have curl access working and documented.

**Comment by theoreticalbts** [comment]
@bytemaster wrote the API code, knows why `remote_db` is hanging, and has partially figured out a solution.  Assigning this ticket to him.

Talking directly to the witness node is working.  I'll write up some examples and add them to the docs in a bit.

**Comment by theoreticalbts** [comment]
Fixed by adding dedicated HTTP server with `--rpc-http-endpoint` option.
