### ISSUE TITLE
FC's safe multiplication...isn't. 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#10]
Class fc::safe has following specification:

```
*  This type is designed to provide automatic checks for
*  integer overflow and default initialization. It will
*  throw an exception on overflow conditions.
```

And then defines this multiplication operator:

```
safe& operator *= ( safe v ) { value *= v.value; return *this; }
```

I'm pretty sure this operator implementation is not compliant with the class spec.

**Comment by vikramrajkumar** [comment]
> Proper way to fix this:

```
Assert sizeof() is 64 bits or less
Examine signs to determine whether result should be positive or negative
Multiply absolute values as uint128's
Ensure absolute value of result is absolute value of uint128()
Need special case for minimum value of signed type
```

> On a not-unrelated note, uint128 should probably be rewritten to use __uint128_t when compiling on GCC. With proper inlining, this change should enhance the performance of these checks to be equivalent to one 64-bit multiplication on Intel. (Fun fact: when multiplying two N-bit numbers, Intel CPU's actually return a 2N-bit result in two registers.) SO thread here: http://stackoverflow.com/questions/28868367/getting-the-high-part-of-64-bit-integer-multiplication says that the compiler knows this when using __uint128_t.
> 
> We could provide template specializations for smaller types that use appropriately sized ones, e.g. we could get away with using uint64_t for the product in safe<int32_t>. In fact, by doing if on sizeof, we should be able to do this without template specializations (hopefully the compiler optimizes away the untaken branches since the taken branch can be determined at compile time for any instantiation).

**Comment by vikramrajkumar** [comment]
> Scaling up to a uint128 works great iff we're using __uint128_t, but it's important to note that the __uint128_t type is only defined on useful compilers, which rules out MSVS. Personally, I'm OK with this. As it happens, I've already used a compiler intrinsic when setting the genesis authority, but that could be replaced with a less efficient solution without substantial penalty, as it's rare that we need to do it. Using fc::uint128's fixed point math every time we need to multiply two safe<uint64_t>s is unacceptably expensive.

**Comment by vikramrajkumar** [comment]
> Unlike full nodes in legacy BitShares, it's my understanding that in Graphene casual users won't be expected to be running full nodes. These days it can be expected that clued-in people either use Linux [1] as their primary OS, or can easily access it on a spare machine, VM or cloud server.
> 
> So if casual users have no need to run full nodes at all, and power users are perfectly capable of working with a non-Windows OS, is there any reason we need to support Visual Studio at all?

```
AFAIK no one has ever done any testing of Graphene on Visual Studio or Windows
AFAIK we've made zero plans to do so
If we really want a Windows executable we can simply use MingW, which (since it's GCC under the covers) should support all GCC features
```

> And FTR, I'm skeptical of the airy assertion that using uint128_t will meaningfully add to the CPU usage of the application, especially on the very light loads [2] we'll likely see for the next several years.

[1] Or some other UNIX-like OS. (footnote needed because most of the other people in this office, who mostly really know their stuff, prefer to use Macs for some inscrutable reason)

[2] Compared to the total throughput the system is capable of handling.

**Comment by emfrias** [comment]
and not to beat a dead horse, but if it ever becomes an issue, boost::multiprecision has a uint128_t that uses the native __uint128_t where available and fakes it where it's not.  It also has optional checking built in.  Might be easier to wrap it.

**Comment by vikramrajkumar** [comment]
^ @theoreticalbts might be worth looking into.

**Comment by bytemaster** [comment]
This is an optimization for after release.

**Comment by vikramrajkumar** [comment]
This is a violation of spec so not a wontfix. But assuming this can be postponed for now.

**Comment by bytemaster** [comment]
This isn't a hard fork, it is an implementation detail.  It could expose bugs that result in a hard fork, but that is a separate issue.
