### ISSUE TITLE
Define min feeds per Asset

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#104]
This should be a bitasset property defined by the issuer.  When there are not sufficient valid feeds then the result is as if there were no feeds.

**Comment by VoR0220** [comment]
In creating a bitasset property, would the bitasset have this characteristic from the start, as in it would be defined within asset.hpp/cpp?

**Comment by nathanielhourt** [comment]
@VoR0220 It would be specified in `asset_create_operation` and stored as a field on `asset_object`, specifically in `asset_object::bitasset_options` because it can be changed after the asset is created.
