### ISSUE TITLE
Check for fill_order virtual ops that do not represent a matched order

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#105]
In this event the paid/received asset types will likely be the same or have their meaning defined differently and this will potentially break the market history plugin.

**Comment by theoreticalbts** [comment]
Is there any way such `fill_order` virtual ops can ever happen?

**Comment by bytemaster** [comment]
Canceling a short order or perhaps a margin call.

**Comment by bytemaster** [comment]
Without short orders there is never a case will a fill_order vop is created with the same asset id.
