### ISSUE TITLE
Reducing key object bloat

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#106]
This ticket is to track the discussion of improving our key handling in order to reduce bloat in the number of key objects.  Having every key be an object is theoretically a nice normalized database design.  However, in practice, key objects are created for one-time use addresses, leading to bloat in the number of key objects in the system.

Also, @bytemaster suspects the container overhead for key objects puts the actual size of such objects in the range of the size of an address, resulting in little to no memory savings.  Benchmarks which measure this effect might be helpful additions to this discussion.

@bytemaster outlined a solution in today's meeting, which I encourage him to post here.

**Comment by nathanielhourt** [comment]
I believe the conclusion of today's discussion was that we want to remove the key objects and replace all uses of `key_id_type` with `address` if it is reasonably quick to do so, but that this is not a priority in the very short term and can be delayed until after internal testnet 1 (pre-alpha milestone).

Is that what the others understood?

**Comment by bytemaster** [comment]
I have removed the use of key_id_type or address in the transaction signatures field and just have the raw signatures now.

**Comment by bytemaster** [comment]
I believe this issue has been resolved and the migration completed with all tests passing.
