### ISSUE TITLE
Audit all usage of the word "burn" in the code

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#108]
The word "burn" is currently used to refer to two different concepts:
- (A) Moving core into the reserve fund
- (B) Making core permanently inaccessible (equivalent to sending to an address of all zeros)

However, the word "burn" should only refer to (B).  Thus, we definitely need to rename the `total_burned` field of `refund_worker_type`.

We should also rename `asset_burn_operation` to `asset_refund_operation`.  A separate `asset_burn_operation` is not needed, as it suffices to simply transfer funds to the null account.

**Comment by VoR0220** [comment]
Why not use the word "reserve" instead of "burn"?

**Comment by bytemaster** [comment]
max_supply - current_supply == reserve 

Burning needs to mean reducing the max_supply
