### ISSUE TITLE
Unused Signature Attack

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#112]
The protocol can be attacked by applying many unused and unnecessary signatures to a transaction.  There is currently no fee charged on a per-signature basis.  

We need to verify that any signature on the transaction is actually checked by validation and is not friv.

**Comment by arhag** [comment]
Didn't you solve this very replay attack a while ago on BitShares 0.x by checking uniqueness of the digest of the unsigned transaction (not the digest of the full transaction)?

Why isn't this attack being solved in the same way? Checking that any signatures provided are actually used is not enough to prevent such replay attacks. What about multisig conditions? If you have a M-of-N condition, that just means there would still be N choose M different valid transactions that an attacker can replay.

Or am I completely misunderstanding the nature of this attack?

**Comment by bytemaster** [comment]
You completely misunderstand the nature of the attack.   This attack is about adding unnecessary signatures to a transaction and thus bloating the size of the transaction.

**Comment by VoR0220** [comment]
Why would bloating the size of the transaction be an attack necessarily? Is this making it more difficult for a witness to sign a block? I'm not sure I fully understand the nature of the attack either....

**Comment by bytemaster** [comment]
In theory it allows arbitrary data to be included which bloats the ledger and/or memory usage.
