### ISSUE TITLE
Assertion failed Error when starting witness node ...

### ISSUE THREAD

**Issue by c055** [cryptonomex/graphene#114]
``` c++
Assertion failed: (_valid), function operator*, file /Users/xx/git/graphene/libraries/fc/include/fc/optional.hpp, line 192.
Abort trap: 6
```

**Comment by emfrias** [comment]
That's a fairly generic error, can you reproduce under gdb and post a stack trace?

**Comment by c055** [comment]
hey yep .. ok guess again my mistake .. just wiped out witness dir and started again ... seems to be working now ... closed .. will reopen if i'm getting more problems ...
