### ISSUE TITLE
Verify Database Version when Opening

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#116]
Detect when the software has changed and requires a reindex.

**Comment by VoR0220** [comment]
Would utilizing the chain_ID method be a good way of figuring out whether the software itself has changed or is that not what chain_ID is returning (there isn't really any documentation for this particular global state variable).

**Comment by VoR0220** [comment]
Looking around at Doxygen, it would seem one way to do this would be to check the object id of the db object the majority of delegate/witness nodes are running...however it would seem we need to implement a method that would call what db version is running on these nodes?
