### ISSUE TITLE
Verify all exceptions in graphene/chain/exceptions.hpp are actually used somewhere

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#117]
Every exception in the list should have a test that causes it to throw during validation.

**Comment by vikramrajkumar** [comment]
Subsumed by: #113

**Comment by theoreticalbts** [comment]
Commit 8ff25b813feeb95b2b7ffde12ed95c1e47ff6065 comments out the maximal set of legacy exception types that still allows us to compile.
