### ISSUE TITLE
chain_tests are broken

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#120]
After e161e5a9fcd4e268a5ab0bc16d873a08f253ce95 I get 14 failures in `chain_test`.

**Comment by theoreticalbts** [comment]
I fixed `double_sign_check`, will push as soon as I make sure it compiles

**Comment by nathanielhourt** [comment]
Resolved: f29eaa92e2207dc702bb7f014688146f1ba96879
