### ISSUE TITLE
Compiling now requires Boost >= 1.58

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#124]
Was this intentional? I remember @theoreticalbts saying something about how after 1.57 Boost gets complicated to build or something, just wanna make sure I actually need it before upgrading.

```
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.57.0

  Boost include path: /home/sigve/opt/boost_1_57_0/include

  Detected version of Boost is too old.  Requested version was 1.58 (or
  newer).
```

**Comment by xeroc** [comment]
Not a C++ coder, but I am certain BM knows what he does:
This is the corresponding commit:
https://github.com/cryptonomex/graphene/commit/8efa2e673856f61fac2c283b3b5766ceb1749af7

**Comment by svk31** [comment]
Right you are, thanks! I'll just close this then I guess

**Comment by svk31** [comment]
Just referencing what @theoreticalbts had to say about 1.58:

> (Note, 1.58.0 requires C++14 and will not build on Ubuntu LTS; this requirement was an accident, see )

Trying to build it now, will update here with the results.

**Comment by svk31** [comment]
I was able to build Boost 1.58.0 under Ubuntu 15 without issue, however compiling the toolkit now fails but I'm not sure it's related to Boost

**Comment by cryptid11** [comment]
I get that error even after `sudo apt-get autoremove libboost-dev; sudo add-apt-repository ppa:boost-latest/ppa; sudo apt-get install libboost1.55-all-dev libboost1.55-tools-dev libboost1.55-doc libboost1.55-dbg libboost1.55-dev` on ubuntu 14 lts, what's the problem here? (same story on debian jesse)

**Comment by abitmore** [comment]
@cryptid11 just follow the doc https://github.com/cryptonomex/graphene/wiki/build-ubuntu, skip the Qt steps. Probably you need to rebuild boost.

**Comment by cryptid11** [comment]
After that (but with 1.60 version https://steem.io/documentation/how-to-build/ that I find meanwhile) I get:

```
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:80 (FIND_PACKAGE)


-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:84 (FIND_PACKAGE)
```
