### ISSUE TITLE
boost_1_58 related build error..

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#126]
Ubuntu 14.04 build error.. After a fresh checkout and boost upgrade this the start of a long list of errors.  Seems to be a known issue in boost
http://lists.boost.org/Archives/boost/2015/02/220149.php

```
In file included from /home/jcalfee/opt/boost_1_58_0/boost/context/all.hpp:13:0,
                 from /home/jcalfee/bitshares/graphene/libraries/fc/src/thread/context.hpp:3,
                 from /home/jcalfee/bitshares/graphene/libraries/fc/src/thread/thread_d.hpp:5,
                 from /home/jcalfee/bitshares/graphene/libraries/fc/src/thread/thread.cpp:5:
/home/jcalfee/opt/boost_1_58_0/boost/context/execution_context.hpp:202:52: error: ‘std::index_sequence’ has not been declared
                                               std::index_sequence< I ... >) {
...
```

**Comment by bytemaster** [comment]
http://lists.boost.org/boost-users/2015/04/84110.php

I think you can fix by adding this to the build flags:
-DBOOST_NO_CXX14_INTEGER_SEQUENCE

**Comment by jcalfee** [comment]
An equals was required to make it valid: `-DBOOST_NO_CXX14_INTEGER_SEQUENCE=`

I don't think it is in this version of boost (empty: `egrep BOOST_NO_CXX14_INTEGER_SEQUENCE ~/opt/boost_1_58_0/ -r`).  Also:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    BOOST_NO_CXX14_INTEGER_SEQUENCE
```

same build error

**Comment by jcalfee** [comment]
https://github.com/boostorg/config/pull/58

**Comment by emfrias** [comment]
Ran into this somewhere too, ended up changing `indexed_sequence<...>` to `integer_sequence<size_t, ...>` as suggested in one of the threads on the mailing list to work around it.  That might be simpler than upgrading gcc, which is probably the right solution.

**Comment by jcalfee** [comment]
The error is a little different: `index_sequence< I ... >` .. what would you translate that to?

**Comment by emfrias** [comment]
whoops, I typed it wrong from memory, I meant that `index_sequence<T>` is supposed to be the same as `integer_sequence<size_t, T>`, a search and replace of `index_sequence<` for `integer_sequence<size_t,` should give you something that works, as long as your compiler knows what an integer sequence is...

There was a related change, I think I also had to search/replace `make_index_sequence<` to `make_integer_sequence<size_t,` or something, I'll see if I can find it

**Comment by bytemaster** [comment]
Are you all actually editing the boost source code to get this to build?

**Comment by jcalfee** [comment]
Have not...  What do you recommend?

**Comment by jcalfee** [comment]
Fixed... The gcc route was easy.  I did need to do a fresh clone (clean up old cmake file).  I'll add a few notes to the wiki.  I'll PM theoretical about updating the wiki.

Install gcc-4.9

CC=gcc-4.9 CXX=g++-4.9 cmake -DBoost_NO_SYSTEM_PATHS="TRUE" -DBOOST_ROOT="~/opt/boost_1_58_0" -DCMAKE_BUILD_TYPE=Debug
