### ISSUE TITLE
Test account "nathan" balance is empty

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#127]
This use to work for me, but now the account balance is empty. 

```
set_password pw
unlock pw
import_key "1.3.15" "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
```

Command and output:

```
unlocked >>> list_account_balances "1.3.15"
list_account_balances "1.3.15"

```

**Comment by bytemaster** [comment]
We have been updating how balances and keys are initialized in genesis.

**Comment by jcalfee** [comment]
OK,  this makes ideal branch material... ;).

Can you recommend a good commit that we should develop on?

**Comment by bytemaster** [comment]
import_balance nathan [5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3] true
