### ISSUE TITLE
Strange static_variant blocks in js_operation_serializer

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#128]
Several blocks are output that look like this:

https://github.com/cryptonomex/graphene-ui/blob/ea40ac06463e2de9c9ec45334e40ed7848cc7dbf/dl/src/chain/serializer_operation_types.coffee#L575-L581

```
static_variant [
    linear_vesting_policy_initializer    
    cdd_vesting_policy_initializer
] = static_variant [
    linear_vesting_policy_initializer    
    cdd_vesting_policy_initializer
]
```

I'm simply deleting them and it seems to be fine.  Immediately below the blocks these structures are used so this is probably ok:

https://github.com/cryptonomex/graphene-ui/blob/ea40ac06463e2de9c9ec45334e40ed7848cc7dbf/dl/src/chain/serializer_operation_types.coffee#L616-L640

**Comment by bytemaster** [comment]
I think this is a case where we just need to name the static_variant.
