### ISSUE TITLE
Review non-serialized blockchain parameters

### ISSUE THREAD

**Issue by emfrias** [cryptonomex/graphene#136]
In `graphene::chain::chain_parameters`, the following three fields are not reflected, so not modifiable:

```
genesis_proposal_review_period ///< minimum time in seconds that a proposed transaction requiring genesis authority may not be signed, prior to expiration
maximum_witness_count          ///< maximum number of active witnesses
maximum_committee_count        ///< maximum number of active delegates
```

in context here: https://github.com/cryptonomex/graphene/blob/master/libraries/chain/include/graphene/chain/types.hpp#L437-L441

Can someone verify that this omission was intentional, and if so, add a comment to that effect or move them out of the struct entirely.  I had assumed everything in `chain_parameters` was serialized and it surprised me when I couldn't find these parameters in the `get_dynamic_global_properties` output.

**Comment by bytemaster** [comment]
This was an unintentional omission and not the first that I have seen.   We need a good way to test for these kinds of omissions.
