### ISSUE TITLE
Shared data for unit testing (ex: memo data)

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#137]
Enhance memo test (https://github.com/cryptonomex/graphene/blob/52fd59f0aaa2d5edb7beb5357b35a7f8f5d54137/tests/tests/basic_tests.cpp#L170-L179) to use a JSON file with a sample public key (example: sender_private_seed: "1") and private key (receiver_private_seed: "2") and a text memo with the expected 1)text and 2)encrypted output (in hex).  I'll update the JavaScript side to ensure it passes. 

related: https://github.com/cryptonomex/graphene-ui/issues/34

**Comment by jcalfee** [comment]
Fyi, cli_wallet and javascript memos are not compatible right now.  Anytime we have a dependency like this I would suggest we add to the JSON file so that we can quickly detect it and get back in sync.

**Comment by vikramrajkumar** [comment]
@jcalfee Please check whether @nathanhourt's change here: https://github.com/cryptonomex/graphene/commit/ab740d6aaa685ed9d0e6ecd625b393d3598b92d9 is sufficient to close.

**Comment by jcalfee** [comment]
@vikramrajkumar Nathan's idea is to simply improve the test case so that it is testing the internal result in addition to the input and output.  It simplifies the code by not having a JSON file and gives an alternate implementation the HEX data they need to check there own code.  If it gets too hard to track changes I may suggest the JSON file again.
