### ISSUE TITLE
is_valid_name() is not RFC 1035 compliant 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#15]
RFC 1035 specifies the following format for domain names:

```
<domain> ::= <subdomain> | " "
<subdomain> ::= <label> | <subdomain> "." <label>
<label> ::= <letter> [ [ <ldh-str> ] <let-dig> ]
<ldh-str> ::= <let-dig-hyp> | <let-dig-hyp> <ldh-str>
<let-dig-hyp> ::= <let-dig> | "-"
<let-dig> ::= <letter> | <digit>
```

This is much different from the algorithm implemented in is_valid_name().

We need:
- A unit test for only this specific function, verifying it produces the correct result for many examples of valid and invalid names.
- An unambiguous specification in the form of BNF rule(s), state machine diagram(s) and/or regular expression(s).

**Comment by vikramrajkumar** [comment]
> I'm actually not seeing how this is that different from is_valid_name()... Aside from the slashes in child names, this looks pretty much like what's implemented.

**Comment by vikramrajkumar** [comment]
> You can't have a name like "aaa-bbb-1". I think we should state that RFC 1035 is the normative spec, and implement RFC 1035.
> 
> As it is, we have something that's almost RFC 1035 but not quite.

**Comment by vikramrajkumar** [comment]
> is_valid_name will reject "aaa-bbb-1":
> 
> ```
> else if( c >= '0' && c <= '9' )
> {
>      if( prev == ' ' || prev == '.' || prev == '-' || prev == '/' ) return false;
> }
> ```

**Comment by vikramrajkumar** [comment]
> Yes, and "aaa-bbb-1" is legal according to RFC 1035 spec. The purpose of this ticket is to try to get a consensus on whether:
- Option (A): We are implementing RFC 1035, and rejecting "aaa-bbb-1" is a bug.
- Option (B): We are implementing something that is not RFC 1035, and rejecting "aaa-bbb-1" is not a bug.

> If we're going with Option (A), we need to fix the code to conform to the spec in RFC 1035.
> 
> If we're going with Option (B), we should write a specification stating clearly and precisely the set of strings the code is intended to accept, and then fix the code to conform to the spec we write (if needed).

**Comment by vikramrajkumar** [comment]
> For the record, my own personal preference is for Option (A), and if I don't hear any arguments in favor of Option B I will likely rewrite the code to comply with RFC 1035 and close the ticket.

**Comment by vikramrajkumar** [comment]
> Ahh, you're right, it is legal to have a digit following a hyphen. That's a trivial change to is_valid_name, though.
> 
> FTR, I vote for option A. Complying with existing standards is best. We also need to get the roles of dots and slashes straight in our names; a name should not be allowed to contain both, as they are intended to be mutually exclusive representations of a name, i.e. "nathan/phone" and "phone.nathan" are the same name, so "nathan/phone.bob" should be illegal.

**Comment by vikramrajkumar** [comment]
`We also need to get the roles of dots and slashes straight in our names.`

> I agree. You think that the outcome of last week's discussions was that we agreed on Option (C), I think that the outcome of last week's discussions was that we agreed on Option (D):
- Option (C): Slashes and dots are different means of expressing the sub-account relationship. So "bigcorp/department/dude" and "dude.department.bigcorp" are different expressions which express traversal of the same path through the relation.
- Option (D): Slashes represent the sub-account relation (i.e. the account keys of "bigcorp/department/dude" are revocable by "bigcorp/department" or "bigcorp"), but dots don't represent any such relation (i.e. the interpretation of "bigcorp.com" is the same as "bigcorp-com", it's completely distinct from "bigcorp" account from the blockchain's point of view, although in practice Big, Inc. may wish to own both names).

> We should write a normative spec which clearly states what the semantics of dots and slashes are intended to be, and then make the code follow the spec.

**Comment by bytemaster** [comment]
"/" is valid and used to represent "parent/child" and can have at most one level
"-" is valid but does not translate to anything. 
aaa-bbb-1 may be valid.

**Comment by theoreticalbts** [comment]
Still needs a unit test

**Comment by arhag** [comment]
According to RFC 1035 multiple consecutive hyphens are allowed, but `is_valid_name` currently does not allow that. In order to comply, the cases for line 68 (`'.'`) and line 69 (`'-'`) need to be separated. The statement in line 70 is fine for the `'.'` case. However, for the `'-'` case a different version of line 70 is needed where the `prev == '-'` condition is removed from the if statement.

Also, if option (D) is the correct interpretation of slashes, why is only one of them allowed in a name? In other words, why is the parent/child relationship only allowed to go one level deep?

**Comment by vikramrajkumar** [comment]
I would guess that we are okay with a strict subset of the RFC.

Reopening this anyway as the OP requires a unit test with "many examples" and not the 2 in the closing commit.

**Comment by vikramrajkumar** [comment]
Also see: https://github.com/cryptonomex/graphene/commit/f88a7682dd962b2592e84a69385ebd68d3ced3e2#commitcomment-11776932

**Comment by nathanielhourt** [comment]
@arhag We decided some time ago to keep the account hierarchy simpler by only allowing one level of childing.

**Comment by vikramrajkumar** [comment]
Related: #93

**Comment by vikramrajkumar** [comment]
We have removed child accounts (#93) and I have updated the spec to Option (B'): a strict subset of RFC 1035, with a description here: https://github.com/cryptonomex/graphene/blob/9719689c346187d87b0b10af396d3e151c79162f/libraries/chain/operations.cpp#L66-L72

@theoreticalbts Please review and close if satisfied.

**Comment by vikramrajkumar** [comment]
Also note that some current names in BTS will fail the spec I've defined above: specifically those with adjacent hyphens like `a------------------------------------------------------------0` so we may want to consider relaxing the spec so that all BTS names validate.

Edit: Also the asset symbol spec will fail some current BTS symbols, specifically those with numbers like `TESTNOTE.3`.

**Comment by pmconrad** [comment]
Allowing adjacent hyphens would pave the road for IDN-like names.
Then again, IDN is just a workaround to the shortcomings of RFC-1035 wrt non-ASCII names.

**Comment by vikramrajkumar** [comment]
Also note that it is easier to relax the spec later, than to tighten it.

**Comment by bytemaster** [comment]
The account names of a---------------0... were created in an attempt to get on the front page / spam / attack the BitShares network.   I would suggest we not migrate account names that violate RFC-1035.

**Comment by vikramrajkumar** [comment]
They played by the BTS rules, and still satisfy RFC-1035 anyway. At worst they will be renamed to validate under 2.0, but we may as well keep them as-is.

Shortcomings in the user-interface are a separate issue.
