### ISSUE TITLE
Spamming a witness_node may eventually cause it to fork

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#150]
I was able to get a witness node on my system to fork from the rest of the network by spamming it with ~30 TPS. It stayed in sync fine for several minutes, but eventually forked and continued producing blocks on its lonely chain, never able to reconnect with the larger world. Very sad.

Even more sad, I have not acquired logs of this event. See issue #149

**Comment by VoR0220** [comment]
So you attacked just that individual node and tried to make the transactions solely through that one? I'd like to try and reproduce the problem.

**Comment by nathanielhourt** [comment]
@VoR0220 Yeah, I connected several different cli wallets to one node and ran flood_network on all of them.

**Comment by bytemaster** [comment]
Eric hasn't seen this issue even with spamming at 140 TPS.    What can we do to close this issue?

**Comment by nathanielhourt** [comment]
It may have been a fluke. I haven't attempted to reproduce it on a proper testnet, so I'm not sure if it's a repeatable issue.
