### ISSUE TITLE
Witness node produces blocks when forked

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#151]
A witness can get forked and continues producing blocks on that fork. Add a rule to the witness node that it will not produce blocks by witness ID `W` if the head block was also produced by `W`. This behavior should be suppressable (allowing the node to produce consecutive blocks by the same witness) using a command line flag.

**Comment by bytemaster** [comment]
Unless there is manual intervention no witness on a fork with below 33% witness participation will produce blocks.  This is designed to prevent minority forks from growing without manual intervention.  If a minority fork gets too long (beyond the undo history)  it could cause some nodes to get stuck on that fork.

In theory the only thing that should cause a split is network connectivity issues or a software bug.  In either event, the minority fork should stop producing.  

If the network fragments into more than 3 pieces each with less than 33% then manual intervention should be required to get everyone back on the same page.
