### ISSUE TITLE
Document transaction signature validation requirements

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#152]
In order to minimize the amount of work validating nodes need to do to validate a transaction's signatures, the client should minimize the number of signatures on the transaction. In other words, the set of signatures included in the transaction should be both necessary and sufficient to satisfy _a_ path in the authority tree (but not necessarily the optimal one, as finding this one is a hard problem).

The simplest solution is to sign with all available keys, and then to remove all keys which can be removed without losing authority for the transaction.

**Comment by nathanielhourt** [comment]
Note: This refers only to client logic, not to backend logic. The validator behavior will not be changed pursuant to resolving this issue.

**Comment by nathanielhourt** [comment]
Transactions can be filtered by tighter criteria prior to being propagated to the witnesses and the witnesses may refuse to include overly signed transactions; however, if a witness does choose to include an overly signed transaction it shall not invalidate the block.

**Comment by theoreticalbts** [comment]
Related: #157

**Comment by vikramrajkumar** [comment]
I think this can be closed after various changes in the interim, e.g.: https://github.com/cryptonomex/graphene/commit/83c8b4c5f9dd8bdb74c57eb30d60555ca365d692
