### ISSUE TITLE
Unable to upgrade Nathan to lifetime member!

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#156]
New chain.. Per https://github.com/cryptonomex/graphene/wiki/CLI-Wallet-Cookbook, I did a import_key "nathan"... then import_balance ... and then:
upgrade_account nathan true
0 exception: unspecified
10 assert_exception: Assert Exception
delta.amount > 0: 
   {}
   th_a  db_balance.cpp:55 adjust_balance

   {"account":"1.2.15","delta":{"amount":-1000000000,"asset_id":"1.3.0"}}
   th_a  db_balance.cpp:69 adjust_balance

**Comment by bytemaster** [comment]
Are you sure the import_balance worked properly and that your balance was greater than the upgrade fee?       According to that error your balance was 0.

**Comment by jcalfee** [comment]
I was trying to import "nathan" into the jul-9-test-genesis.json so this explains the zero balance.  Thanks...
