### ISSUE TITLE
Transaction Expiration & TaPoS makes signature verification impossible without chain state

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#157]
Given a transaction, it is impossible to verify signatures without the past 65K block IDs.  

We currently use the lower 16 bits of the block number plus the lower 32 bits of the block ID to identify a TaPos check.   Signatures require the full 160 bits of the block ID _IF_ using relative expiration. 

At the cost of 14 bytes per transaction we could include the full ID and keep transactions independent of the context.   

It is also impossible to calculate the expiration without chain context.   Both of these things violate the core principle of transactions being self describing.   

I propose that we always use the full ID and absolute expirations.  This will make the calculation of the digest ease and make interpreting a "stand alone" transaction possible without referencing the chain state.

We may not require the full 160 bits of the TaPoS ID to have it achieve its purpose.   Our earlier conclusion was that 32 bits was not sufficient because attackers could "mine" blocks in order to migrate transactions to an attacking chain.    Bitcoin is currently mining 72 bits every 10 minutes at a cost of $6000.   I think that we should replace the current transaction header with:

```
uint32_t block_number
array<char,10>   block_id[4...14]
uint32_t expiration
```

A total of 18 bytes which will replace 8 bytes used today for a total cost of 10 bytes per transaction.    Because the block number is the first 4 bytes of the block id, this is really the same as including the first 14 bytes of the block ID in the TaPoS history.

**Comment by theoreticalbts** [comment]
If the protocol uses a blockhash of length `N` bits, we are saying that `N` bits is the number of bits required to provide a cryptographically strong unique identification of a block.

Let `N_h` be the number of bits used to identify a block in the block header, and `N_t` be the number of bits used to identify a block in a TaPoS tx header.  This proposal sets `N_t < N_h`, but if this is true, you can get free gains -- if `N_t` is too short to be secure, then you can gain security by increasing `N_t` to `N_h`.  If `N_t` is sufficiently long to be secure, then you can save bytes (and achieve greater conceptual and code unity by using the same value everywhere it is necessary to identify a block) by shortening `N_h` to `N_t`.

**Comment by bytemaster** [comment]
After further thought I think we can use

```
uint32_t block_num
uint32_t block_time
uint32_t block_digest
uint32_t expiration
```

A total of 12 bytes which is just 4 bytes larger than the current system on the wire and is sufficient to protect against any/all accidental reorganizations leaving only malicious witnesses.   There is only one witness able to generate a particular block at a particular time and it would require them to mine their signature to produce a second block at the same timestamp with the same block_digest.  

Mining of signatures is 1000x more difficult than straight sha256 mining and there are no ASICs available to do ECC signature mining.    If we assume a GPU/CPU can do 1000x more SHA256 calculations per second than ECC signatures and the Bitcoin network has 400 Petahash/sec to generate 68 bits of 0's every 10 minutes and that a GPU can do 600 Mhash/sec.   Then it follows that the computational difficulty of finding a 32 bit collision in 1 second is:

666 Billion GPUs will produce 72 bits of 0's every 10 minutes
400 Trillion GPUs would be required to produce 68 bits of 0's every second
6000 GPUs to produce 32 bits of 0's every second via ECC signing.

The cost of the equipment to execute the attack would be several million dollars assuming there was no latency involved in spinning up the GPUs or doing network communications to coordinate those GPUs.     When you factor in latency overheads and the desire to "catch up" to the real time network the cost to mine one counterfeit block every second on average would be close to 10 million dollars worth of equipment and cost $200 per hour in electricity.   

These are very high costs to execute an attack that you could only get away with ONCE and it requires the collusion of every single witness to pull off.

**Comment by bytemaster** [comment]
As far as whether we can reduce the block hash from 128 bit down to 64 or even 32 bit depends upon how someone wishes to prove a block is a legitimate block and who is able to produce a fake block.

If all you check is the hash history and not the signatures of the witnesses then anyone can cheat by producing a fake block whose hash checks out.   Considering this is what we do when reindexing prior to a checkpoint then we need enough bits in the block_id to prevent counterfeits from being inserted into the history.  All of the power of bitcoin is only able to produce one 68 bit collision every 10 minutes.  128 bits is enough require all of the power of bitcoin for 5000 years to produce a single collision. 

If an attacker did create a collision it would only disrupt newly syncing nodes and would be easily countered by adding a checkpoint and verifying witness signatures on checkpoint blocks.  

For TaPoS we don't require the same level of security.  TaPoS is there to prevent accidental short-term forks and NOT to protect against 100% witness collusion nor the generation of fake blocks.

Different security requirements mean different bit requirements are optimal.

**Comment by bytemaster** [comment]
Solution:
1. Implement a TaPoS assert operation predicate that offers full block ID validation for transactions that want the added security.  This is only required for transactions that are of high value and transfer control of funds to a newly created identifier and where the witnesses cannot be trusted. 
2. Remove the full block ID from the transaction digest generation.

**Comment by jcalfee** [comment]
What is the best time for me to update the JavaScript?
