### ISSUE TITLE
API to get accounts where owner or active matches an Address

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#164]
We used to have an API call like this given a list of key_ids.  It may have been lost when the key_id was removed.

This is used for existing accounts signup.

I need a replacement, something like this:

```
vector<optional<account_object>> database_api::get_accounts_by_address(const vector<address>)
```

**Comment by bytemaster** [comment]
database_api::get_key_references( public_key ) does the job.

It will return all accounts that reference that public key.

**Comment by jcalfee** [comment]
Sorry! thanks for finding this...  Should we put a vector around the public_key parameter?  Some users may have as many as 7 thousand keys.

**Comment by bytemaster** [comment]
Then we would need a vector< vector< > > result.
