### ISSUE TITLE
Add API call to fetch and subscribe to all objects related to a given account

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#166]
At present, there is no good way for clients to fetch all data relevant to a given account. There is also no way to ask for notification if new objects related to an account are created (i.e. balances, orders, etc). We need an API call to fetch all of this relevant data, and optionally to subscribe to updates to existing objects or addition of new relevant objects.

**Comment by xeroc** [comment]
Not sure about the market subscriptions yet .. but can we have those notifications as verbal as possible too?

**Comment by nathanielhourt** [comment]
@xeroc See #45 for that. I'll probably be getting to that in the coming weeks.

**Comment by bytemaster** [comment]
Updated subscription to be detect additions and removal of objects.

dffc83cca9e710e509c307237a3767b966da2505

**Comment by vikramrajkumar** [comment]
Superseded by: #183
