### ISSUE TITLE
witness config crashing on specifying multiple witnesses

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#167]
https://github.com/cryptonomex/graphene/commit/aa794e7836244e0287f3fa3d94e8081b513af08f#commitcomment-12207443

Used to be able to paste duplicate lines in config file like:

```
witness-id = "1.6.0"
witness-id = "1.6.1"
witness-id = "1.6.2"
```

Now client crashes on start if this is attempted.

**Comment by bytemaster** [comment]
Multiple witnesses should never be used in practice, if you must have multiple witnesses use the command line argument for testing.
