### ISSUE TITLE
Complete Genesis Initialization 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#17]
> Define a JSON format for the complete genesis state, sufficient to launch as a smooth upgrade from BitShares. Implement loading of this genesis state into the object graph, and test building a chain off of that initialization complete with transactions which claim genesis stakes, transfer assets, etc.
> 
> Need to make sure that account withdrawals work for imported PTS and BTC addresses in addition to BTS addresses.

**Comment by bytemaster** [comment]
Please include the issue description in the commit log rather than just #17 that way scanning the commit history is easier.

**Comment by vikramrajkumar** [comment]
Snapshot code including account name modifications: https://github.com/bitshares/bitshares/compare/cba06218f962f93576a5b94911009138cf07425f...5b2385d246
