### ISSUE TITLE
Verify the NULL_ACCOUNT works as specified 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#170]
This account is supposed to have no possible way of passing an authority check.

The authority object should probably be able to represent:

always, never, and conditional (default).  

I think a weight of 0 should represent "ALWAYS" 
I think a weight > 1 with 0 keys, 0 accounts, and 0 addresses should be NEVER.

**Comment by nathanielhourt** [comment]
Also need to check that the TEMP_ACCOUNT can't change its authority.

**Comment by bytemaster** [comment]
~~Null account should be configured with a public key for which there is no private key.  This way we can avoid any special case logic~~

**Comment by bytemaster** [comment]
The null account has a weight of 1 but no keys or child accounts which means it is impossible to reach the threshold.

**Comment by theoreticalbts** [comment]
Why is creating an account with an impossible authority threshold forbidden?

**Comment by theoreticalbts** [comment]
What is the reason to forbid people from using authority weights to "brick" an account?  I do not see any reason to prevent this at the blockchain level.  We've previously discussed that what I call _autonomous accounts_ (a "bricked" account which has signed at least one proposed transaction) may be a useful primitive.

I am also aware there is at least one coin (I forget which one) that performed its genesis distribution to those who sent Bitcoins to a specific bricked Bitcoin address.  Being able to create a bricked account other than the null account would also be useful in case someone wants to do a similar thing on a Graphene-based blockchain.

**Comment by xeroc** [comment]
> I am also aware there is at least one coin (I forget which one) that performed its genesis distribution to those who sent Bitcoins to a specific bricked Bitcoin address. Being able to create a bricked account other than the null account would also be useful in case someone wants to do a similar thing on a Graphene-based blockchain.

Counterparty did a so called `Proof-of-Burn`:
http://counterparty.io/news/why-proof-of-burn/
The corresponding address was `1CounterpartyXXXXXXXXXXXXXXXUWLpVr`

**Comment by bytemaster** [comment]
You can create a bricked account by adding the NULL_ACCOUNT as the required account authority.   This makes creating a bricked account for special purposes explicit and prevents accidental bricking of an account.
