### ISSUE TITLE
Conflicting comments regarding semantics of issuer_permissions

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#176]
There are conflicting comments [here](https://github.com/cryptonomex/graphene/blob/master/libraries/chain/include/graphene/chain/protocol/asset_ops.hpp#L25-L28) and [here](https://github.com/cryptonomex/graphene/blob/master/libraries/chain/protocol/asset_ops.cpp#L171-L172) regarding the semantics of `issuer_permissions` and `flags` in `asset_options`.

The comment in `asset_ops.hpp` implies that setting a permission bit means the owner is allowed to _change_ the corresponding flag.  However the comment and implementation in `asset_ops.cpp` says that setting a permission bit means the corresponding flag may be _enabled_.

Put another way, the implementation allows the issuer to make a blockchain-enforced promise of the form "I will never enable this flag" on any flag that is currently disabled.  The header comment implies the issuer can make a blockchain-enforced promise of the form "I will never change this flag from its current state" on any flag.

Since the behavior specified in the header gives slightly more flexibility in the types of blockchain-enforced promises issuers can make, I am inclined to change the implementation, removing the check in `validate()` and adding the following check to `evaluate()`:

```
// changed flags must be subset of old issuer permissions
FC_ASSERT(!((o.new_options.flags ^ a.options.flags) & ~a.options.issuer_permissions),
          "Flag change is forbidden by issuer permissions");
```

The purpose of this ticket is to gather consensus on which semantics is more desirable.

**Comment by bytemaster** [comment]
You can enable / disable the flag bits at any time if you have permission.   The flags are not ONE WAY.
