### ISSUE TITLE
cli_wallet fails to start: TypeID: Space.Type.0 (2.6.0) doesn't match expected value 2.7.15

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#177]
`2481904ms th_a       main.cpp:114                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
10 assert_exception: Assert Exception
fc::to_uint64( s.substr( 0, first_dot ) ) == SpaceID && fc::to_uint64( s.substr( first_dot+1, second_dot-first_dot-1 ) ) == TypeID: Space.Type.0 (2.6.0) doesn't match expected value 2.7.15`

**Comment by nathanielhourt** [comment]
The type IDs got changed recently. You can fix this by editing your wallet.json and changing `2.7.15` to `2.6.15`
