### ISSUE TITLE
Implement unit test for MIA backed by asset other than CORE

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#179]
Create a unit test for an MIA backed by a non-CORE asset.
- Check that you cannot stack MIA too deep (I think it is a requirement that an MIA is backed by CORE, a UIA, or an MIA backed by CORE).

**Comment by theoreticalbts** [comment]
Related:  #480

**Comment by theoreticalbts** [comment]
I discovered a [work-in progress](https://github.com/cryptonomex/graphene/commit/dcb7f557bd22ddc35f5de5f0f16983d649b9ccd5) test case in my local repo, pushing so it doesn't get forgotten.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#41
