### ISSUE TITLE
Test renewal of annual membership

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#180]
Create an annual membership, renew it before expiration, make sure the date is pushed back the proper amount regardless of when the renewal occurs.

Then try renewing a lapsed annual membership.  Make sure fees have reasonable semantics in the gap between expiry and renewal.

**Comment by theoreticalbts** [comment]
Related bugs:  #455 #539

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#42
