### ISSUE TITLE
Implement unit test for all assert predicates

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#184]
All predicates in [assert.hpp](https://github.com/cryptonomex/graphene/blob/dffc83cca9e710e509c307237a3767b966da2505/libraries/chain/include/graphene/chain/protocol/assert.hpp) need to be exercised by unit tests.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#45
