### ISSUE TITLE
Implement unit test for whitelist_markets and blacklist_markets

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#186]
The `whitelist_markets` and `blacklist_markets` are properties on an asset.  But first we must ask, what are the intended semantics of these fields?

Assigning to @bytemaster to answer this question.

**Comment by bytemaster** [comment]
These fields limit which markets an asset can be traded against.   

Whitelist markets means a set of other assets that a user issued asset may trade against.
Blacklist markets implies the asset can trade against anything but the specified markets.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#47
