### ISSUE TITLE
Implement unit test to change backing asset of MIA

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#187]
MIA's can have their backing asset changed, but only when there is no supply.  The unit test should verify:
- Backing asset cannot be changed with nonzero supply
- After the backing asset is changed, it can no longer be borrowed against the old backing
- After the backing asset is changed, it can be borrowed against the new backing

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#48
