### ISSUE TITLE
Implement unit test for proposed tx already containing some owner / active approvals

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#189]
Specifically you should trigger the test in the last two `for` loops:  https://github.com/cryptonomex/graphene/blob/dffc83cca9e710e509c307237a3767b966da2505/libraries/chain/proposal_object.cpp#L57-L60

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#50
