### ISSUE TITLE
Change custom operation id type to account_id_type

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#195]
I believe the custom operation is intended to support third-party extensions, and the (currently 16-bit) ID field is an identifier for the particular extension used by the custom operation.

If multiple third-party developers create extensions, they will face a coordination problem assigning non-conflicting ID's.  However, globally coordinated assignment of unique ID's is a problem the blockchain database already solves.  We can leverage this solution by simply requiring each third-party extension to register an account, and then the account ID serves as the identifier for the extension.

If multiple Graphene-based chains exist, this solution must be extended.  I suggest the account name should be a base58 hash of a document describing the semantics of the extension, then extensions would be able to self-discover their ID on any Graphene-based chain by looking for an account name with this hash.  It doesn't matter who owns the account; what matters is that:
- The name uniquely identifies the semantics of the extension (which is achieved by making it a function of a detailed description of the semantics)
- For any Graphene-based chain, all clients on that chain will translate a 160-bit name to the same 48-bit ID (by looking up the account by name)
- The ID field of the custom operation is large enough to contain such a 48-bit ID

Only the last item requires core support; the first two points are up to extension developers that use the custom operation.  The required core support is a simple -- indeed trivial -- change, namely changing the ID field from `uint16_t` to `account_id_type`.

**Comment by bytemaster** [comment]
The proposed solution only moves the problem because without authentication there is nothing to prevent abuse of the IDs or squatting on the hash of a protocol.  

Anyone developing an extension will be able to see what ids have already been used by other parties and avoid using those.   Overlap doesn't hurt anything because 3rd parties already need to know how to reject invalid content.
