### ISSUE TITLE
Test core_exchange_rate update logic in update_expired_feeds()

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#198]
Specifically, the unit tests need to hit this code:  https://github.com/cryptonomex/graphene/blob/d827c5df281eafe43d6d0d00533ea0a0f2643c1c/libraries/chain/db_update.cpp#L256-L260

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#57
