### ISSUE TITLE
Verify Missed Block Calculation on Maintenance Intervals 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#201]
If there is a very long maintenance interval relative to the normal block interval it would result in the blockchain thinking there are many missed blocks and growing it maximum undo history, possibly pushing it over the edge.  

The calculation for the number of missed blocks needs to factor in maintenance intervals _or_ the maintenance interval period needs to be within a "tolerable" number of missed blocks.

**Comment by theoreticalbts** [comment]
This ticket can be broken down into two parts:
- The slot <-> time mapping functions in `db_witness_schedule.cpp` need to take into account the maintenance interval.
- Everywhere that needs slot <-> time mapping, including (but not limited to) the dynamic undo buffer computation, needs to use those functions.

**Comment by theoreticalbts** [comment]
I will work on the first part.

**Comment by theoreticalbts** [comment]
Well, interestingly enough, maintenance blocks lasting longer than regular blocks was not implemented.  Implemented now (groundwork laid in f80219fd5244626ee63fdd11827357f3d796c350 and 0d0be55e102a7fa8346e6738819a4851433c34c0, actual implementation in 5b9cd9122e5b600dac369e360d7bc0789f0d67e5, many tests un-broken in 6bebdbad1c82193acf5f6a919318afc2f5a42fd6).
