### ISSUE TITLE
Implement unit test to verify time of next block

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#208]
`generate_empty_blocks` queries the implementation for the time of the next block.  The time of each block (including maintenance intervals) should be verified by some test (perhaps added to `generate_empty_blocks`, perhaps a new test case).

**Comment by theoreticalbts** [comment]
On further consideration, this should actually be a separate test which sets the parameters and then makes sure the sequence of block times matches a hard-coded test vector.  It should also have some cases involving changing parameters in the middle and missing blocks.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#58
