### ISSUE TITLE
Refactor fee_schedule from array to struct 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#21]
This will make the JSON more readable and allow more flexible fields

**Comment by vikramrajkumar** [comment]
> This has been "implemented" but with backward compatibility that may break somethings with funny pointer math. operations.cpp needs to be updated to reference the fields by name rather than "index" and the fee enum needs to be removed.

**Comment by nathanielhourt** [comment]
I've fixed this, but haven't pushed it yet.
