### ISSUE TITLE
Problems found in memo_data code review

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#212]
As it is defined as `optional<memo_data>`, validation will fail if `memo_data` cannot be deserialized into `memo_data` structure even if validation code does not check any constraints on the contents of the structure.  There is no reason the chain should be parsing memos at all -- memo format and parsing should be strictly wallet layer functionality.

Here is the list of changes:
- Change from `optional<memo_data>` to `vector<char>`, then deserialize the `vector<char>` to an `optional<memo_data>` in the wallet.  This means memo data structure changes aren't hardforks, merely wallet upgrades.
- Change the deserialized memo type from `optional<memo_data>` to `static_variant<memo_format_1, memo_format_2, ..., memo_format_n>`.  This allows new memo data structures to easily be implemented, while maintaining support for older data structures.
- Implement additional memo formats for (at minimum) a public, unencrypted memo and the existing format.

**Comment by theoreticalbts** [comment]
Hmm, on further reflection, I think actually memo would fit very well as an extension (i.e. in the current `extensions_type`).  This would allow memo to be added to any operation in a generic way (although a wallet UI might not understand how to show the memo to the user for all op types).

**Comment by vikramrajkumar** [comment]
I believe this was shelved; removing from milestone.

**Comment by theoreticalbts** [comment]
This wasn't fixed before launch, so sadly it probably won't ever be implemented.
