### ISSUE TITLE
Upgrade stealth_memo from optional to static_variant

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#213]
I suspect analogous changes to #212 should be implemented for `stealth_memo` if the contents of that data structure are used to ease wallet implementation and should not be validated by the chain.

Actually, it seems that `stealth_memo` is defined but never used.  Is it because the implementation is unfinished, or should the `stealth_memo` member be deleted?

**Comment by vikramrajkumar** [comment]
https://github.com/cryptonomex/graphene/issues/212#issuecomment-129561136

**Comment by bytemaster** [comment]
stealth_memo field is used for cases where someone may want to scan the entire blockchain for potential memo's like they do in BTS.

stealth_confirmation object is currently passed out-of-band between the sender/receiver and is REQUIRED to receive funds.   

This is not a field that could change, it contains no human readable text and is of a fixed size.

**Comment by theoreticalbts** [comment]
I think this can be closed.
