### ISSUE TITLE
[Feature Request] link a 'trading' key to each account

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#218]
We now have
- an account owner key that 'owns' the name
- an account active key that can spend funds

why don't we add
- a trading key that is only allowed to do trades?

That would GREATLY benefit liquidity, because you can write bots and put them anywhere.
You could also offer an API (or a API proxy) that people can use for trading without revealing "withdrawal" access to their funds ..

This would be pretty much the same security scheme as most other exchanges offer already and it would be an easy thing to get funding through a worker/budget item!

Any thoughts?

**Comment by nmushegian** [comment]
One problem is that since you can create your own asset, it'd be just as easy to steal it via trades.

Maybe it would work if you had to whitelist particular markets.

**Comment by xeroc** [comment]
> One problem is that since you can create your own asset, it'd be just as easy to steal it via trades.

Haven't thought about that. Makes sense. Thanks  @nmushegian 

> Maybe it would work if you had to whitelist particular markets.

This would only require an additional field/array for each user that contains the whitelisted assets. Would it make sense to restrict to markets directly? If I trust USD, GOLD and SILVER, I may chose to trade GOLD:SILVER too ..

**Comment by xeroc** [comment]
This is definitely worth a consideration:
https://www.reddit.com/r/BitcoinMarkets/comments/3fuo9o/haasbot_23_beta_build_1_is_now_available_okcoin/#cttchyz

**Comment by theoreticalbts** [comment]
It seems questionable whether it makes sense to trust someone to trade your money if you don't trust that person not to take your money.  If you let someone dishonestly trade on your behalf, they would be able to trade your money away by trading it for worthless UIA's, or participating in "lopsided" trades.
