### ISSUE TITLE
Where should we put specifications? 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#22]
In particular, I have written this file: https://gitlab.bitshares.org/dlarimer/graphene/blob/64fdf24e4526d0c5f84e2397ec40ee7eaf6d9145/doc/witness-rng.md

This is a normative specification of how the witness scheduler's RNG works. Anyone should be able to independently implement the RNG based on this document.

It does not seem to belong in a doc comment on the witness scheduler class, as the doc comment is deeply tied to the names of methods and other implementation details. The spec is at a higher level of abstraction than our particular implementation.

It does not seem to belong in its current home in the doc/ subdirectory of this repo, because things were moved away from there in the past (see e.g. 32c8f8ca9e7933cc3197d5172c96fcb8e1ceb561).

It does not seem to belong in https://github.com/graphene as that repo seems to be dedicated to stuff at the "marketing layer," like blog posts. This file is quite clearly highly specific technical documentation.

I am not aware of any other places we are currently putting documentation. So please figure out where this file belongs and put it there. In addition, please include a URL of the new location in the commit message or this ticket.

**Comment by bytemaster** [comment]
It should be referenced as doc/spec.dox and defined in a /*\* @defgroup */  Then it can be referenced elsewhere in the code and linked to by doxygen.
