### ISSUE TITLE
Genesis initialization of bit commitment secrets needs to be revised 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#23]
Genesis secrets for init witnesses are currently based on genesis_private_key. This won't be doable for real init witnesses with real private keys.

Since the bit commitment needs to support a "never committed" state to deal with new witnesses who have never produced a block, we should simply set the genesis witnesses to this state.

**Comment by nathanielhourt** [comment]
This is a sub-issue of #17
