### ISSUE TITLE
API crash fix code needs review

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#232]
I believe crashes #221 and #222 may be due to a problem I found in FC API implementation.  Specifically the `get_connection()` function was locking a `shared_ptr` into a local variable `tmp`, then returning the locked pointer as a reference.  This is wrong, as the locked pointer only has the same lifetime as the `shared_ptr` -- when the local variable goes out of scope, the locked pointer becomes invalid, so returning it is incorrect.

I fixed it in FC master branch by returning the `shared_ptr` instead, but I am not 100% sure this is the right thing to do, as I am not sure why the reason for using `weak_ptr` instead.  So this approach should be reviewed by someone who understands the high-level design of this code ( @bytemaster or possibly @nathanhourt ), in particular, under what circumstances only `weak_ptr` references to a connection should remain.

The `callback_functor` now stores the pointer as a `shared_ptr` rather than a reference, which keeps it from being culled -- but it also has the side effect of prolonging the life of the object.  The alternative would be making it a `weak_ptr` rather than a `shared_ptr`, but this means there needs to be logic in the `callback_functor` to deal with what should happen when the `weak_ptr` is found to be null.  Basically there are two reasonable alternatives -- no-op (so `callback_functor` would silently swallow `operator()` when `api_connection` is null) or throw an exception.

I'm hazy on what API callbacks are, and how they are used, at all levels of the API.  My understanding based on looking at `api_connection.hpp` is that maybe the owner of `generic_api` object is responsible for keeping the `api_connection` around as its own `shared_ptr`, signaling to the `api_connection` framework that it wishes to terminate the connection by destroying the `api_connection` object.  The effect of using `shared_ptr` in `callback_functor` is that the `api_connection` framework now overrides its caller's wishes and forces the connection to remain open for the lifetime of the `callback_functor` object.

My first thought was that the life extension of the `api_connection` by having a `shared_ptr` in `callback_functor` was wrong, and it should be a `weak_ptr`.  My second thought contradicted this:  The `detail::callback_functor` is a local in `call_generic`, so the extension doesn't matter so much; it will only be internal to the method.  My third thought contradicted the second thought:  The `callback_functor` is saved in `bind_first_arg()` result, meaning the `callback_functor` escapes `call_generic` and therefore has a longer lifetime.

So the question which needs to be answered:  What is the lifetime of the `callback_functor` object, and should the `api_connection` be forced open for this lifetime?  If the answer is "yes," my patch stands as-is.  If the answer is "no," then the right thing to do is change my patch so the `get_connection()` result, originally a reference, should be converted to a `weak_ptr` instead of a `shared_ptr`.  And then logic to handle the `weak_ptr` being null should be inserted wherever it is dereferenced (I think only in `callback_functor`).  Which leads to the sub-question of what should happen when the `weak_ptr` is null.

This is pretty complicated abstract code using templates and function pointers, and AFAICT it is totally undocumented.  It should definitely be documented, and the above analysis should be carefully reviewed by someone who understands the code.

**Comment by bytemaster** [comment]
I believe the fix in number #221 will cause a memory leak because the functor will hold a shared pointer to the API and the API will hold the functor.  

The proper solution is to use a weak pointer and throw if the connection is no longer valid.
