### ISSUE TITLE
Filter transactions from get_account_history result based on block number

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#236]
Negative block number -> relative to head

**Comment by theoreticalbts** [comment]
Allowing negative block numbers for relative to head is a bad idea -- the client will likely want to track block numbers on its own.

We need a new index of `(account ID, block number) -> operation_history_id` where the `ohid` is the last op by the account in the block.  The index should be disabled unless requested on the CLI.  Disabling will increase performance but `get_account_confirmed_history()` will not be able to query based on block number.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#61
