### ISSUE TITLE
Implement full node with N-block confirmation delay

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#237]
Pursuant to #234, option (3), implement an option on `fork_database` which prevents the pushing of blocks which have not yet received N confirmations. This option must be exposed in the config file, as well as being specifiable from the testing infrastructure.

**Comment by theoreticalbts** [comment]
In order to implement (3), you need some sort of header validation on un-pushed blocks.  If you don't do any header validation, you must ensure you only connect to node(s) that do, i.e. you will be using approach (2).

The witness scheduler algorithm gives you half a round of witnesses.

**Comment by nathanielhourt** [comment]
Good point. And due to the inability to reliably determine a witness's key in future blocks, without doing full validation (because it may have been changed in the unprocessed blocks) we cannot do proper header validation.

Given this issue, rather than substantially rework consensus protocol, I'll be implementing approach (2) instead.
