### ISSUE TITLE
Withdraw permission specification is inconsistent 

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#24]
The withdraw_permission_create doc comment in operations.hpp states: "Only one withdrawal may occur per period for a given permission. Any subsequent withdrawals will fail until the next period begins, even if the sum of all withdrawals within a given period does not exceed the withdrawal limit."

The withdraw_permission_object doc comment in withdraw_permission_object.hpp states: "Any number of withdraws may be made so long as the total amount withdrawn is less than the limit for any given period."

These requirements are inconsistent...

**Comment by nathanielhourt** [comment]
The former spec is incorrect. We now allow multiple withdrawals per period, up to the limit. A certain developer neglected to update the docs when he implemented that revision.

**Comment by nathanielhourt** [comment]
Looks like this has already been fixed.
