### ISSUE TITLE
Polish delayed node

### ISSUE THREAD

**Issue by nathanielhourt** [cryptonomex/graphene#240]
Following up on #237, there are some limitations of the initial implementation. Primarily, that the delayed node does not handle forking right now.

Optimally, the delayed node will check that the block ID's match for a given block number between its trusted node and itself, and, if they don't, pop blocks until they do. If it runs out of undo history, it needs to resync (this is currently hard to do without restarting the process, as it's impossible to clear the object graph from memory without destroying the `database`). Then it will resume syncing from the trusted node as usual.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#63
