### ISSUE TITLE
get_full_account subscriptions returns *two* notifications

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#243]
While writing a script for #233, I noticed that a `get_full_account`
subscriptions gives _two_ notifications on a transaction. From my point of few
it seem to be the _current_ and the _previous_ transaction. Also, the content of
the array (asset, transation) changes between both notifications:
## First:

```
[
  [
    {
      "owner": "1.2.3184", 
      "balance": 1695538561, 
      "id": "2.5.3", 
      "asset_type": "1.3.0"
    }, 
    {
      "most_recent_op": "2.9.78", 
      "pending_vested_fees": 2089843, 
      "total_core_in_orders": 0, 
      "pending_fees": 0, 
      "owner": "1.2.3184", 
      "id": "2.6.3184", 
      "lifetime_fees_paid": 58515604
    }
  ]
]
```
## Second:

```
[
  [
    {
      "most_recent_op": "2.9.80", 
      "pending_vested_fees": 2089843, 
      "total_core_in_orders": 0, 
      "pending_fees": 0, 
      "owner": "1.2.3184", 
      "id": "2.6.3184", 
      "lifetime_fees_paid": 58515604
    }, 
    {
      "owner": "1.2.3184", 
      "balance": 1695538561, 
      "id": "2.5.3", 
      "asset_type": "1.3.0"
    }
  ]
]
```

Also, it seem there is one redundent encapsulation "[]" here.

I'd also like to add a feature request, such that the notification either
contains the transaction or at least a transaction id, otherwise, I would need
to request the operation from 2.9.\* and then get the tx details from their.

**Comment by bytemaster** [comment]
The outer [] are because this is a callback method and may have 0 or more parameters.   In this case, there is 1 parameter, an array of database objects that have changed.

What is interesting is that the most_recent_op is different between the First and Second call.  As far as I can tell from visual inspection, that is the only change.  

It would be helpful if I had some timestamps on these notices.

**Comment by bytemaster** [comment]
Ok, so further review of the code indicates that there are two times I notify of changes:
1. when the transaction is applied to the "pending state"
2. when the transaction is applied as part of a block  

In either case the proper response is to update your local map of  OBJECT_ID=>OBJECT_DATA with the content provided by the callback.

**Comment by xeroc** [comment]
Thanks for clarification

**Comment by xeroc** [comment]
> What is interesting is that the most_recent_op is different between the First and Second call. As far as I can tell from visual inspection, that is the only change. 

Do you have any explanation of why this may be the case? It's not very intuitive :(

Why does the first (assuming pending) state change have an `op_id` at all?
