### ISSUE TITLE
fork_database.hpp:  fork_item::invalid is never used

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#248]
The original purpose was to track blocks that get pushed and are then found to be invalid and then to prevent the fork database from accepting any additional blocks on top of that block.  

Under BTS 0.x we had some issues where a block would get marked as invalid when it shouldn't have and then we would never be able to switch back to that fork.    So there is some risk for marking things as invalid, but in theory the BTS 2 undo architecture shouldn't have the same issues.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#66
