### ISSUE TITLE
Implement and test virtual operations

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#250]
Some big fat TODO's in `db_market.cpp` here:  https://github.com/cryptonomex/graphene/blob/eeeab17477a635fcff7f2d294dff8ecf25449b10/libraries/chain/db_market.cpp#L89-L116

This is basically to generate a virtual cancel op to inform account history listeners that orders have been cancelled due to certain asset management actions.

**Comment by theoreticalbts** [comment]
Virtual ops generated by a proposed transaction require special attention.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#67
