### ISSUE TITLE
Better handling of non-broadcast transactions in cli_wallet

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#256]
- Allow specifying expiration time in cli_wallet
- If `broadcast` is `false`, then place transaction into a local store
- Allow users to inspect the local store and broadcast transactions

The motivation here is to provide some way for `cli_wallet` users to inspect fees before authorizing the transaction.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#68
