### ISSUE TITLE
object_database created outside witness_node_data_dir on fresh install 

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#257]
- Install brand new `witness_node`
- `object_database` is created in the wrong place
- Subsequent run doesn't recognize it

**Comment by abitmore** [comment]
https://bitsharestalk.org/index.php/topic,18751.msg243241.html#msg243241

> the object_database and genesis.json file location (if it is provided in the config.ini and not the --genesis-json cmd line arg) are relative to the folder from which the witness_node binary is executed.

See also https://bitsharestalk.org/index.php/topic,18751.msg243253.html#msg243253

**Comment by abitmore** [comment]
My steps for reproducing this issue:
- build in /app/bts/bts2-pre1/
- cd /app/bts/scripts/
- gdb
- (gdb) file /app/bts/bts2-pre1/pragrams/witness_node/witness_node
- (gdb) set args --data-dir=/app/bts/witness_node_data_dir-pre1/
- (gdb) run

A `object_database` folder is created under `/app/bts/scripts/`.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#69
