### ISSUE TITLE
witness_update operation needs tested

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#258]
We need a `witness_update_operation` to be able to update `block_signing_key` and `url` field of a `witness` object.

Setting the `block_signing_key` to zero should not be allowed (this will be reserved for when/if we implement witness resignation).  There should also be a memo field in the operation which contains the secret, encrypted to the new signing key.  The memo field should be `vector<char>`.

**Comment by theoreticalbts** [comment]
Committee members are in the same situation:  They have a `url` field which can never be updated.

**Comment by theoreticalbts** [comment]
These ops need unit tests.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#70
