### ISSUE TITLE
Witness private key may be lost if wallet crashes

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#259]
`cli_wallet` does not save the private key for a new witness until the witness is registered on chain; this is wrong.

**Comment by emfrias** [comment]
what's more, even after the witness is registered on the chain and the key is imported into the wallet, it doesn't trigger an automatic save or backup (like import_key does).  I just lost a few witness keys because I really like to hit ctrl-c when I make a typo.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#71
