### ISSUE TITLE
fc::http::websocket_*{client,server} violate rule of 5

### ISSUE THREAD

**Issue by pmconrad** [cryptonomex/graphene#278]
During testing I found that websocket_server (and others) in fc/src/network/http define an empty custom destructor. This leaves the resources allocated by the underlying implementation dangling when the original websocket_server instance has been deleted. Even worse, the underlying implementation continues to listen on the socket.

Probably not a high priority issue because instances typically are created on application startup and stay alive until shutdown.

**Comment by bytemaster** [comment]
The destructor of the unique_ptr<> is what frees the memory.
