### ISSUE TITLE
witness_node hangs silently when attempting to listen on already-used port

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#280]
Discovered the hard way that it was hanging in `reset_p2p_node()` when I accidentally re-used an occupied server-side port.  This seems like a common error so let's tell the user and exit cleanly instead of simply hanging with no error message.

**Comment by bytemaster** [comment]
I think this is a logging issue.  The P2P code will print a message to warn the user that it is waiting for the port to become available.    It is using the "ulog"

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#77
