### ISSUE TITLE
Stopping witness node with Ctrl+C when port is already in use results in unclean shutdown

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#290]
Steps to repro:
- Listen on p2p port in another process
- Start `witness_node` attempting to listen on same p2p port
- Press Ctrl+C to stop `witness_node`
- Stop other process listening on p2p port
- Start `witness_node`
- Witness node must resync

The solution is to try to listen on all ports before opening the DB.

**Comment by theoreticalbts** [comment]
Related:  #280

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#78
