### ISSUE TITLE
CLI wallet hangs when witness node goes away

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#291]
- Start `witness_node`
- Start `cli_wallet` connected to `witness_node` RPC
- Stop `witness_node` with Ctrl+C
- `cli_wallet` prints "Server has disconnected us" but hangs, unresponsive to Ctrl+C, and needs to be killed by `kill` command

**Comment by theoreticalbts** [comment]
Fixed.

**Comment by abitmore** [comment]
Just a note, `cli_wallet` is responsive to Ctrl+D at any time, doesn't need to `kill`.
