### ISSUE TITLE
Restarting witness overwrites current log file(s) but not appends

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#293]
Which may lead to loss of some maybe-useful logs.

**Comment by abitmore** [comment]
Looks like commit https://github.com/cryptonomex/fc/commit/08944de151de5769fd69e01496297c6d55d2e456 doesn't fix this issue.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#79
