### ISSUE TITLE
when I build the testnet,occurred errors!

### ISSUE THREAD

**Issue by lanzf** [cryptonomex/graphene#294]
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:59 (FIND_PACKAGE)

-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:63 (FIND_PACKAGE)

-- Configuring Graphene on Linux
-- Using  as BerkeleyDB root
## -- Looking for: db_cxx-6.0

-- Could not find Berkeley DB >= 4.1 (missing:  BDB_INCLUDE_DIR BDB_LIBRARIES) 
-- Configuring project fc located in: /home/lanzengfei/graphene/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  libraries/fc/CMakeLists.txt:122 (FIND_PACKAGE)

CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindOpenSSL.cmake:334 (find_package_handle_standard_args)
  libraries/fc/CMakeLists.txt:142 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by theoreticalbts** [comment]
As stated in the very beginning of `README.md`, when building from source you must install the prerequisites.  How you do this depends on your OS.  For Ubuntu Linux, instructions are maintained at:

https://github.com/cryptonomex/graphene/wiki/build-ubuntu
