### ISSUE TITLE
Logs are not saving properly

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#298]
Sometimes the log just stops saving.  I need to figure out why and fix it.

**Comment by abitmore** [comment]
If you mean you can't find the "72 hours ago" logs which is described in #299, it's because that current logs are set to be truncated every day (log files older than 24 hours will be automatically deleted in order to save disk space). Perhaps it is configurable.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#80
