### ISSUE TITLE
Implement unit tests for advanced proposal usage

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#311]
- Autonomous account
- Use proposal to implement not-valid-before semantics

Not-valid-before is tricky.  What we want is a transaction which is signed, but cannot execute before time `t`.  We cannot use a review period to implement this, because sigs cannot be added during the review period.

What I want to do is implement the following changes:
- Allow adding / removing of sigs to a proposed transaction at any time.
- If a proposed transaction gains sufficient authority to execute during the review period, it does not execute.
- If the proposed transaction has sufficient authority to execute and its review period has passed, then anyone can pay a fee to apply an empty signature delta to update the proposal, which causes it to execute.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#83
