### ISSUE TITLE
Assert Processing Budget - Crash 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#313]
3599870ms th_a       application.cpp:422  
      handle_transaction   ] Got transaction 
from network
1ms th_a       db_block.cpp:97  
push_block           ] new_block.block_num():
 172076 new_block.id(): 0002a02c211ed6b4ab4ab
41989d9f0007ad02fef
witness_node: /home/clayop/graphene/libraries
/chain/db_maint.cpp:333: void graphene::chain
::database::process_budget(): Assertion `time
_to_maint > 0' failed.
Aborted (core dumped)

**Comment by theoreticalbts** [comment]
The problem is in https://github.com/cryptonomex/graphene/blob/1177cfe0ed10026b6b5d112da53bfa6f206845ce/libraries/chain/db_maint.cpp#L523-L527

The fix will be a hardfork.

**Comment by theoreticalbts** [comment]
Reproduced by above test and fixed.
