### ISSUE TITLE
Updating votes with CLI wallet doesn't work

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#323]
CLI wallet needs to be able to vote for a list of things.

**Comment by theoreticalbts** [comment]
Also, the account doesn't refresh from the chain after voting.  So if you vote for things one-by-one, your next vote transaction is wrong (since votes are specified in the tx as the complete set of things you want to vote for, rather than a delta against the previous set).

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#90
