### ISSUE TITLE
CLI wallet exceptions when decrypting memo

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#325]
- If you can't decrypt a memo in CLI wallet, you get a backtrace.
- CLI wallet can't decrypt memos of transactions you send

**Comment by bigcube** [comment]
The memo is needed for tracking and audit purposes.  It should be made available and even prioritised for a fix.

"Memos use a shared secret that can be derived from both ends knowing the pub key of the other party only .. I assume the cli-wallet tries to derive the shared secret in the wrong way such that it fails to load the other parties private key .."

**Comment by ByronAP** [comment]
This should be priority

**Comment by ByronAP** [comment]
Please fix this its killing my system with all the errors it causes.

**Comment by abitmore** [comment]
Any back trace so that we can analyse?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#91
