### ISSUE TITLE
UIA option "market_fee_percent" should not be an Integer

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#329]
If it's in `_uint64`, it's unable to be set to 0.2% or so.

```
update_asset ABITUSDA null {"market_fee_percent":0.2,"core_exchange_rate":{"base":{"amount":1,"asset_id":"1.3.0"},"quote":{"amount":1,"asset_id":"1.3.662"}}} true
4 parse_error_exception: Parse Error
Couldn't parse uint64_t
    {}
    th_a  string.cpp:113 to_uint64

    {"i":"0.2"}
    th_a  string.cpp:116 to_uint64

    {"*this":"0.2"}
    th_a  variant.cpp:405 as_uint64
```

**Comment by theoreticalbts** [comment]
Like all percentages in the backend, `market_fee_percent` is on a scale of `GRAPHENE_100_PERCENT` internally, so each click of `market_fee_percent` represents a 0.01% change.

Whether we should make this a 0-100 scale to make the CLI wallet API internally consistent (e.g. `register_account` will use 0-100 as of the next update) is a question I will leave to @bytemaster

**Comment by theoreticalbts** [comment]
Well, it seems the decision on this one is for this particular API method to use the same format as the backend.  Changing this would break existing clients.  So the existing implementation stands.
