### ISSUE TITLE
Vesting vs Non-Vesting Fees

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#34]
Only fees above a certain threshold defined by consensus must vest.   This means that in practice only the following fees require vesting:
1. Premium Name Registration
2. Lifetime and Annual Memberships
3. Large Data Transactions
4. Symbol Name Registration

Other fees (transfers, market orders, etc) will be below the threshold and thus vest immediately.

**Comment by nathanielhourt** [comment]
Dupe #31
