### ISSUE TITLE
Already connected to requested peer when specifying mutliple seed nodes

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#341]
I get this error when I have two nodes running on localhost, then try to run a third node configured to connect to both of the first two nodes as seed nodes.

```
763261ms th_a       main.cpp:183                  main                 ] Exiting with error:
90003 already_connected_to_requested_peer: already connected to requested peer
already connected to requested endpoint 127.0.0.1:1787
    {"endpoint":"127.0.0.1:1787"}
    p2p  node.cpp:4522 connect_to_endpoint

    {}
    th_a  application.cpp:140 reset_p2p_node

    {}
    th_a  application.cpp:337 startup
```

**Comment by theoreticalbts** [comment]
Actually, I was also specifying the _same_ seed node multiple times (I forgot and specified it both as command line parameter _and_ in the config file.)

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#96
