### ISSUE TITLE
Transfer Whitelist / Reputation to a new account name.

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#35]
A user should be able to transfer their white list permissions to a new account name without consulting with all of the individual white list authorities.  This is slightly more work for the authorities because they will have to scan the database and update their records when they see this transfer operation.

Only transfer and not copy.  Some Web of Trust implementations may imply uniqueness. 

How does this impact voting applications?

**Comment by nathanielhourt** [comment]
This sounds suspiciously like a request for an `account_rename_operation`. Is this really that important?

**Comment by theoreticalbts** [comment]
The precise semantics and use case for this are not clear.  I would really like to close this as wontfix.
