### ISSUE TITLE
Black swan triggers based on short squeeze price, not true price

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#350]

**Comment by theoreticalbts** [comment]
The short squeeze protection has call orders match more aggressively than the price feed.

What's happening in this issue is that the short squeeze protection's aggressive matching attempts a match against an order in black swan territory, which triggers a black swan, even if the least collateralized call order is not in black swan territory according to the feed.

In other words, the short squeeze protection algorithm matches call orders against bids at a premium to the feed.  When there isn't enough collateral to fund the premium, a black swan is triggered.  My initial impression is that the correct behavior is to simply reduce the premium to what the position can can afford with its entire collateral.

However, my understanding became more nuanced when I noticed an interesting effect:  The better collateralized call orders can reach further into the bid side of the book, because they can pay a higher premium!  In other words, the worst collateralized margin position is not necessarily at the top of the book (if you define the top-of-book Ask to be the Ask which matches at least as many Bids as every other Ask).

From a standpoint of system stability, we of course would like to automatically trade away the worst collateralized position.  However, it is possible to imagine a situation where:
- The maximum premium is 20%
- Position A only has sufficient collateral to pay a 10% premium
- Position B can afford the entire 20% (i.e. it is solvent even at the short squeeze protection's aggressive price)
- Position A and B have the same debt and are both in margin call territory.
- There is an offer at 15% premium sufficient to buy out exactly one of the two debts.

Matching the offer against A is impossible.  Matching the offer against B goes against the design principle that the margin call algorithm should strive to always clear the least solvent short.

It seems that it would be possible to match the offer against A and B _combined_, i.e. fill half of the offer against B at 20% premium, then fill the other half of the offer against A at 10% premium.  The offer receives 15% as it requested, and the margin call algorithm has made progress on the least collateralized short as specified in its design goal.

**Comment by bytemaster** [comment]
Not a bug, @theoreticalbts misunderstood the issue.

**Comment by theoreticalbts** [comment]
I guess the issue is what "conservative" behavior is.  My misunderstanding was that "conservative" behavior is "don't trigger black swan unless you must, because black swans are bad."  @bytemaster has convinced me that a "conservative" black swan trigger should activate _before_ the least collateralized short not fully wiped out, as this means the longs won't get a haircut (provided the "real" price of the asset doesn't move between when the settlement is triggered and when the long redeems).
