### ISSUE TITLE
Different account ids on the same account

### ISSUE THREAD

**Issue by clayop** [cryptonomex/graphene#353]
transfer clayoptest1 clayoptest23 20000 CORE "" true
3421351ms th_a       wallet.cpp:529                get_account          ] my account id 1.2.
91535 different from blockchain id 1.2.91533

**Comment by clayop** [comment]
get_account clayoptest23
327991ms th_a       wallet.cpp:529                get_account          ] my account id 1.2.91535 different from blockchain id 1.2.91533
{
  "id": "1.2.91535",
  "membership_expiration_date": "1970-01-01T00:00:00",
  "registrar": "1.2.17269",
  "referrer": "1.2.17269",
  "lifetime_referrer": "1.2.17269",

**Comment by theoreticalbts** [comment]
I suspect cli_wallet account caching behavior, I'm thinking maybe the registration initially reported to the cli_wallet happened on a different fork (so the account had a different ID).  And the cli_wallet has no way to update the ID of an account, it just assumes the ID will always be correct and immutable -- but this isn't true in the presence of forks.

**Comment by bytemaster** [comment]
The CLI wallet needs to be updated to be more reliable with respect to caching.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#98
