### ISSUE TITLE
Error when decrypting memo

### ISSUE THREAD

**Issue by elmato** [cryptonomex/graphene#364]
"get_account_history xxxxx 100"

3434700ms th_a       wallet.cpp:2321               operator()           ] Error when decrypting memo: 10 assert_exception: Assert Exception
wallet._keys.count(op.memo->to): Memo is encrypted to a key GPH6fzuewtdfrMtqSWQzLrnV4oqskBjGHy8WpzKVzqSVvCeGtjVR5 not in this wallet.
    {"k":"GPH6fzuewtdfrMtqSWQzLrnV4oqskBjGHy8WpzKVzqSVvCeGtjVR5"}
    th_a  wallet.cpp:2314 operator()

**Comment by xeroc** [comment]
Have you imported ALL your keys or only the owner key? please check that you also imported the active_key (which should be identical to the initial memo_key) ..

**Comment by elmato** [comment]
Yes, the strange thing is that i was able to see the memo once and then (without touching the wallet.json)  , after restarting the cli_wallet that error started to show.
I will try to reproduce and give a more details.
