### ISSUE TITLE
Build websocketpp with WEBSOCKETPP_STRICT_MASKING

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#365]
Receiving crash report from @xeroc : https://bitsharestalk.org/index.php/topic,18751.msg241652.html#msg241652

Looks like upstream issue https://github.com/zaphoyd/websocketpp/issues/395

According to comments in the code, the code has some performance optimizations which rely on assumptions that are usually true, but can be broken by compliant C++ compilers.  Apparently one such compiler is GCC 4.9.x with high optimization settings.  `WEBSOCKETPP_STRICT_MASKING` will use a slower, non-optimized version which should play nicely with all compilers.

Having a build that works on all systems is more important than speed of decoding websocket messages.  So I propose enabling `WEBSOCKETPP_STRICT_MASKING` in build script

**Comment by wackou** [comment]
I've had the same problem (also on main bts2 network), and I can confirm that defining WEBSOCKETPP_STRICT_MASKING solved my issue

**Comment by Br0ckSamps0n** [comment]
After discovering this issue as prevailing in the master and the v.2.15.286 I ventured on to IRC.  There I found "complexring" and he suggested the following (follow the instructions but change the cmake to the below):

cmake -DCMAKE_BUILD_TYPE=DEBUG CXX="/usr/bin/g++ -DWEBSOCKETPP_STRICT_MASKING" .

when compiling which did the trick.

Enjoy!

**Comment by theoreticalbts** [comment]
Looks like it's been fixed upstream by [this commit](https://github.com/zaphoyd/websocketpp/commit/4e2fb75d07d903554ae4d729deb00c4ce79a53fc).  For discussion, see [this upstream issue](https://github.com/zaphoyd/websocketpp/issues/395).

**Comment by theoreticalbts** [comment]
Added to fc, we just need to bump fc submodule for next release.

**Comment by xeroc** [comment]
This resolves the issue for me. Closing..

**Comment by Br0ckSamps0n** [comment]
This issue has returned yet again. To work around it simply make sure the build type is "DEBUG".

**Comment by wackou** [comment]
yes, it happened here: https://github.com/bitshares/bitshares-2/commit/16b59e0b422c486238f4b6a09261dfd310b0c481#commitcomment-15240045
