### ISSUE TITLE
Shut down cleanly

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#370]
Currently a clean shutdown isn't even attempted unless you do `SIGINT`, and the shutdown logic suffers from various issues:  #309, #340, #358.

We need to overhaul the shutdown process.

**Comment by bytemaster** [comment]
I updated the shutdown process to close the P2P code.   

SIGINT is the only way shutdown is intended to happen.   We could add an RPC call but that would be a potential security issue.

It shuts down cleanly for me.
