### ISSUE TITLE
wallet.json ends up empty when disk is full

### ISSUE THREAD

**Issue by pmconrad** [cryptonomex/graphene#372]
I had a CLI client running on the same partition as a witness_node (not my actual witness, just a node). The witness node produced lots of logs, filling up the disk until both witness_node and cli_wallet crashed. More precisely, the node crashed and the wallet shut down upon losing the node connection.

The end result was that the wallet.json used by the cli_wallet was an empty file. That shouldn't happen IMO. (I was able to load a backup wallet, nothing was lost.)

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#100
