### ISSUE TITLE
CLAIM BALANCE problem

### ISSUE THREAD

**Issue by lanzf** [cryptonomex/graphene#376]
I import key from 0.9.3c , when click CLAIM BALANCE,there is do nothing ,and I try again many times.

**Comment by xeroc** [comment]
Can you leave it open for a few minutes? Depending on the size of your key file it may take some time to read all of your balances

**Comment by jcalfee** [comment]
possible duplicate: https://github.com/cryptonomex/graphene-ui/issues/319

**Comment by theoreticalbts** [comment]
Probably obsolete.
