### ISSUE TITLE
Short Squeeze Protection / Margin Call Explanation

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#379]
![img_0856](https://cloud.githubusercontent.com/assets/347290/10527599/5f634e44-735f-11e5-8a32-d66092379e92.JPG)

A margin call will occur any time the highest bid is less than the call price and greater than the Short Squeeze Protection Price.

**Comment by xeroc** [comment]
I made some more pictures that I intend to use in a separate paper discussing this engine

![dex-engine-def-0](https://cloud.githubusercontent.com/assets/117800/10755458/3448e438-7c9e-11e5-8f2f-61bf59575124.png)
![dex-engine-def-1](https://cloud.githubusercontent.com/assets/117800/10755459/344bac0e-7c9e-11e5-9645-d6e70d87ca82.png)
![dex-engine-def-2](https://cloud.githubusercontent.com/assets/117800/10755457/344789b2-7c9e-11e5-8495-f2e95f7556d5.png)
![dex-engine-def-3](https://cloud.githubusercontent.com/assets/117800/10755460/34507ff4-7c9e-11e5-833d-da8aaa20dd63.png)

**Comment by theoreticalbts** [comment]
If this ticket isn't something actionable, this discussion should be moved somewhere else.

**Comment by theoreticalbts** [comment]
Move images into documentation, then close.

**Comment by theoreticalbts** [comment]
@xeroc : Please move the images into documentation and close when finished (or maybe you've already put them there, I don't know).
