### ISSUE TITLE
Api wishlist for a better GUI

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#382]
I would like the following api calls to be added in order to improve the frontend (in order of importance):
- [x] **get_market_order_history(asset_id_type a, asset_id_type b, fc::time_point_sec start, fc::time_point_sec end)**

It would return a list of orders for the given market. I first asked for this in June, it's essential to having a functional Exchange. See #47 
- [ ] **get_market_summary(asset_id_type a, asset_id_type b)**

It would return a short summary of that market: bid/ask depth, latest price, 24h change if possible
- [ ] **get_account_order_history(asset_id_type a, asset_id_type b, uint32_t start, uint32_t limit)**

It would return the successful orders made by that account in the given market, a negative start argument should count backwards from most recent transaction (-1 for starting at most recent I guess)
- [ ] **lookup_assets_simple(const string& lower_bound_symbol, uint32_t limit)**

It would simply return a list of assets with only three fields: symbol, id and precision. This is useful because in a lot of cases that's all the information we need, but instead we now ask for the full asset object including nested objects. This would reduce load on the backend as well as frontend.
- [ ] **lookup_account(account_id_type account_id)const;**

Similar to the assets lookup, it would simply return the account name and id. This prevent us from looking up X full account objects just in order to display some names.

I would also like to remind you of #375, which is essential in order to display a user's created assets

**Comment by xeroc** [comment]
While we are at it. For traders we need to **ALSO** offer those Calls for the
CLI-wallet:
- Market (quote/base) Data
  - Market Ticker
  - Market Volume
- Market Orderbook
- Open Orders of account
- Cancel an order

I would agree with this having very high priority b/c we need traders to
interfacer for liquidity!

**Comment by ByronAP** [comment]
This should be high priority and in the cli rpc api

**Comment by mindphlux1** [comment]
I agree that the CLI wallet needs the essential option to cancel an order, and also view your open orders. This is really important. I am trying to write a liquidity bot, but it cannot be completed until these features are working.

**Comment by maqifrnswa** [comment]
cancel_order exists, it just isn't exposed:
https://github.com/bitshares/bitshares-2/blob/bitshares/libraries/wallet/wallet.cpp#L1908

**Comment by maqifrnswa** [comment]
Is there any opposition from devs if I was to submit a pull request that exposes cancel_order and puts it in the graphene::wallet::wallet_api?

**Comment by xeroc** [comment]
Give it a shot and refer this issue in the pull request comment ala (#382)

**Comment by xeroc** [comment]
Can we also have a call that derives the **total** trading volume for **all** markets in BTS (if possible) .. so that we can be ranked here:
- http://cryptocoincharts.info/markets/info

**Comment by bytemaster** [comment]
These are some good ideas.    Our goal with the API was to make it as few calls as possible.

lookup_account can be replaced with _get_object( account_id )_ which already does what you want.

get_account_order_history is simply a filtering of the existing history that the wallet should already have.  We want to avoid fetching data twice and to encourage good proper caching / filtering on the client side.

get_market_summary seems like it would be nice, except that the server would have to calculate that data on the fly and it could be a potential DOS.   

lookup_assets is one that I think needs to be added.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#103
