### ISSUE TITLE
bugs in market BTS:CNY

### ISSUE THREAD

**Issue by todasun** [cryptonomex/graphene#386]
![image](https://cloud.githubusercontent.com/assets/10720816/10639640/f1fc177a-7843-11e5-8dd1-cf8fa8b4a480.png)

**Comment by svk31** [comment]
Not really a bug but a "feature" of the market. The bids are too high to fullfill the criteria needed for them to match the margin orders. There needs to be a buy in the range 0.0228 - 0.0230, and nothing above that in order for the call orders to fill.
