### ISSUE TITLE
[API] Transactions have no GUID until they enter a block, making exchange integration very difficult

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene#387]
When you send a transaction, you are not immediately presented with a GUID which can then be used to later identify and look up the transaction. The use of a callback (on block inclusion) to achieve this goal is insufficient for reliability reasons, between sending and block inclusion there could be:

**a power cut**
**witness crash**
**cli_wallet crash**

In addition, exchanges which currently have a single threaded wallet design would be left blocking for 3 seconds waiting for the callback to occur.

IMO there needs to be a TXID or other GUID identifier available immediately, which can then be used in all later queries to refer to the transaction.

**Comment by ByronAP** [comment]
I work around this by storing the nonce (signed_transaction.operations.memo.nonce) from the transfer then searching through history until I find a match then i store the id (1.11.*).

**Comment by wildbunny** [comment]
Use transfer2 it returns a txid and the signed transaction.

**Comment by ByronAP** [comment]
my cli wallet doesn't have that method

**Comment by wildbunny** [comment]
Grab and build from the latest :)

**Comment by ByronAP** [comment]
will do

**Comment by theoreticalbts** [comment]
If transfer2 API call solves your problem, I'm going to close this.
