### ISSUE TITLE
delayed_node connects to the P2P network

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#388]
People need to run this

```
./programs/delayed_node/delayed_node --trusted-node="127.0.0.1:8090" -d delayed_node -s "0.0.0.0:0" --p2p-endpoint="0.0.0.0:0" --seed-nodes "[]"
```

in order for the delayed node not to connect to the internet via P2P .. the default seed nodes are in place otherwise

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#104
