### ISSUE TITLE
Add receiver name to transfer operation

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#39]
This name would allow users to "send to a name" without having to fear being cheated by a light wallet server doing a bad name->id resolution.    This validation could be skipped by everyone but witness nodes and could be performed as a pre-check (only on propagation of the transaction) because the name/id mapping cannot be changed.

The only "con" with this approach is it would increase the size of a transfer operation.  

This fits in with the philosophy of including any assumed or implied state in the transaction. 

This same technique could be used for any operation where it is assumed an asset is changing owners:

account_transfer
transfer
others??

**Comment by theoreticalbts** [comment]
I thought the only supported configurations were:
- Connecting a native wallet such as `cli_wallet` to a trusted full node running on localhost or through a secure network path
- Using a hosted wallet

If you use the first approach, you trust the full node because you control it.  If you use the second approach, you trust the hosted wallet provider not to send you JS which steals your private keys.  Taking away the provider's ability to lie to you about the chain state doesn't take away their ability to steal your funds if malicious / hacked.  Neither of the use cases we plan to initially support are affected by this attack vector.

**Comment by jcalfee** [comment]
account_create and account_update owner, active 
If that is setup wrong, there could be big trouble in the near or distant future...

Search generated sterilizer_operation_types for "to_account" to find more...
https://github.com/cryptonomex/graphene-ui/blob/master/dl/src/chain/serializer_operation_types.coffee

The encrypted memo could be protected by having a to name and the blockchain address used to create the shared secret.  A witness would have to ensure that they match.  In this case I believe the transaction should be prevented from providing a to key_id..

The account's memo_key is vulnerable too, that one looks a bit complicated..

I was just thinking about support for named assets and accounts everywhere ... but that was too much in the way of code changes.  Great idea, to narrow it down like this...

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php/topic,16829.msg215313.html#msg215313

**Comment by jcalfee** [comment]
How about "send to name" for transfer only.  However, the CLI and GUI can give the option to append check digits and account ID onto the name...  https://bitsharestalk.org/index.php/topic,16829.msg216606.html#msg216606

**Comment by pch957** [comment]
Yes, web wallet is convenient, but it's poor security
once  the JS file been replaced, all user's private key will been stealed.
this is the only way I can think  to enhance security, 
place the web server in a private network, keep ssl certify file safe.

and we should have another choice to get more security light wallet.
we need desktop application, mobile app ....

**Comment by svk31** [comment]
A chrome extension would be cool as well

**Comment by theoreticalbts** [comment]
We have an assert op, I will document how to do this.
