### ISSUE TITLE
Get vested balances fail with an entry with 0 days vesting

### ISSUE THREAD

**Issue by mindphlux1** [cryptonomex/graphene#390]
I have this worker entry which has 0 days vesting:

get_object 1.13.235
[{
    "id": "1.13.235",
    "owner": "1.2.22517",
    "balance": {
      "amount": 0,
      "asset_id": "1.3.0"
    },
    "policy": [
      1,{
        "vesting_seconds": 0,
        "start_claim": "1970-01-01T00:00:00",
        "coin_seconds_earned": "0",
        "coin_seconds_earned_last_update": "2015-10-21T09:51:27"
      }
    ]
  }
]

get_vested balances fails like this:

 get_vesting_balances mindphlux
get_vesting_balances mindphlux
13 St12domain_error: divide by zero
divide by zero: 
    {"account_name":"mindphlux","what":"divide by zero"}
    th_a  wallet.cpp:1551 get_vesting_balances

Thanks,
mindphlux

**Comment by theoreticalbts** [comment]
Fixed
