### ISSUE TITLE
HARDFORK - Refund Order Create Fee on Cancel

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#393]
Market participants expect placing / moving orders to be cheap and filling orders to be expensive.

To prevent spam, all transactions require some kind of fee.
Placing orders consumes memory and cannot be trivially cheap so needs a high fee.
Canceling orders frees memory and has historically been free.

We can make placing orders free, filling orders (relatively) expensive, and canceling orders cheap with the following change.
1.  User pays $0.25 to place an order 
2.  User pays $0.001 to cancel an order, and gets a refund of $0.25 \* NETWORK_FEE_PERCENT
3.  If the order fills then there is no refund of the $0.25

Under this plan the cost to place / update an order is $0.001 while the cost of having an order filled is $0.25.

The only remaining issue with the above is that part of the original fee ($0.20) goes to the referrer who may have withdrawn their cashback.   To keep things simple, the only fee that gets refunded is the network fee.   

If the user is a lifetime member then it looks like this:
1. User pays $0.25 to place an order and receives $0.20 cash back 
2. User pays $0.001 to cancel an order, and gets a refund of $0.05 and $0.0008 cash back. (total cost $0.0002)
3. If the order is actually filled the user paid $0.05

If the user is an annual subscriber then it looks like this:
1. User pays $0.25 to place an order and receives $0.125 cash back
2. User pays $0.001 to cancel an order and receives $0.0005 cash back and a refund of $0.05 (total cost $0.0755)
3. If the order is actually filled the user paid $0.125 

If the user is a basic member then it looks like this:
1. User pays $0.25 to place an order
2. User pays $0.001 to cancel an order and gets $0.05 back (total cost $0.20)
3. If the order is actually filled the user pays $0.25 

The break even point for deciding whether to upgrade to a lifetime member is if the user would end up canceling 500 orders.   If they end up canceling 10000 orders because they are a market maker then the average cost would be ($100 + 50000*.0002)/50000 => 0.0022 and the total spent would have been $110 dollars.

As long as the average order size is greater than $25 dollars, the market fees on the filled orders will be less than other exchanges that charge (0.2%) of volume.   Anyone who does $55,000 of volume will pay over $110 in fees on centralized exchanges.    If you are placing and canceling thousands of orders with a bot and doing less than $55,000 of volume then chances are your bot is not effective and is spamming the network.

**Comment by xeroc** [comment]
I assume this is a hardfork proposal ..
How quickly can this be implemented and what would it cost the shareholders?

**Comment by bytemaster** [comment]
This particular change will adjust the balance in a way that cannot be calculated by operations related to this account alone which violates some graphene principles.

**Comment by bytemaster** [comment]
This hard fork needs to define an extension field for cancel order that allows the individual canceling the order to claim the funds back.  This will keep it in compliance.

There is a potential attack vector of someone crafting orders that fill 99% and then canceling them to avoid the minimum fill order fee.   This will require adding a field to the order that tracks whether or not it has been partially filled.    A partially filled order does not qualify for a refund.

Additionally this hardfork should include code that pays income from order matching to the referrer of the order account if the asset in question is CORE or a bitasset issued by the committee account.

**Comment by clayop** [comment]
Great idea. I cannot complain about trading fees any more :)
But $0.20(50 BTS) for non-lifetime member "seems" quite high and may drive out new users. Can we decrease the baseline to $0.10 or $0.05 and set break-even point to 1000 or 2000?

Add: Be advised that many UIAs already have "market fee" of 0.2% or something, that is the same level as other exchanges. So trading fees are considered as additional cost, and we'd better keep it as low as network can sustain.

Add2: If we set the base fee to $0.10 (Approximately, 25 BTS), the break-even point is 1,250 orders. Total cost per order for a basic member is $0.08.

**Comment by sfinder** [comment]
Based on my trading experience with traditional exchange , why not design a "WELCOME" package for the new user by giving new user life-time membership fee for this first 20 trades.....

**Comment by sfinder** [comment]
Based on my trading experience with traditional exchange , why not design a "WELCOME" package for the new user by giving new user life-time membership fee for this first 20 trades.....

**Comment by clayop** [comment]
I asked about this to some of Korean members who are daily traders. They think the current level ($0.03, 10 BTS) is good, or if higher they are not willing to 'try' our DEX.

"Let's not increase the fee 800%..."

**Comment by bitcrab** [comment]
agree with clayop, for common user 10BTS for trade is ok, if more they would not like to trade.

**Comment by pureland** [comment]
how about transfer fee ?

**Comment by bytemaster** [comment]
The approach outlined in the original issue is crude and deprecated.  Closing this issue so we can open a new issue with a better design.
