### ISSUE TITLE
[API] get_block returns transactions with no IDs

### ISSUE THREAD

**Issue by wildbunny** [cryptonomex/graphene#395]
Calling get_block results in an array of transactions, but each one has no object ID, making it impossible to identify them correctly

**Comment by xeroc** [comment]
since this is demanded by more exchanges and partners I added a priority tag

**Comment by wildbunny** [comment]
Thanks, xeroc - txids were kindly added to the block, which is great, but it would be nice if the transactions and operations both had **object id's** as well. :)

**Comment by xeroc** [comment]
I could very much need those for stats.bitshares.eu as well

**Comment by theoreticalbts** [comment]
Fixed, closing.
