### ISSUE TITLE
BitShares-light_2.15.296.exe - Entry Point Not Found crash at startup

### ISSUE THREAD

**Issue by brekyrself** [cryptonomex/graphene#399]
BitShares-light_2.15.296.exe

Installed the light wallet on Vista sp2 and received the following error upon trying to launch the app.  "The procedure entry point Shell_NotifyIconGetRect could not be located in the dynamic link library SHELL32.dll

Tried running as admin etc... still the same error/crash upon launch.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#106
