### ISSUE TITLE
Change the default binary name in Linux package, and add symlink to /usr/bin/ or different location which is in PATH

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene#401]
As you know, linux is case-sensitive. After installing [bitshares-light_2.0.151027_amd64.deb](https://github.com/bitshares/bitshares-2/releases/download/v2.15.294/bitshares-light_2.0.151027_amd64.deb) by:

```
wget https://github.com/bitshares/bitshares-2/releases/download/v2.15.294/bitshares-light_2.0.151027_amd64.deb
sudo dpkg -i bitshares-light_2.0.151027_amd64.deb
```

I literally spent over a half an hour trying to figure out why there is no package like: `bitshares-light`, `bitshares`, `bitshares-*`, `graphane*`, etc... and why bitshares doesn't "just work" after an instalation.

At the end I have noticed in my unity menu, that bitshares actually is installed, but without the knowledge how to check location of running program, I would never guess, how this binnary is called and how I could run this from command line.

In my opinion name of deb package should be consistent with the name of main BitShares binary file

**Suggested solution:**

Rename deb package to `BitShares-light_2.0.*.deb` and modify deb package, in a way to create symlink `/usr/bin/BitShares-light` -> `/opt/BitShares-light` after instalation.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#108
