### ISSUE TITLE
expose cancel_order in wallet api

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene#402]
Don't know if this is intentional or an oversight, but cancel_order is available in the wallet but not exposed in the wallet api. It's needed for some trading bots.
https://github.com/bitshares/bitshares-2/blob/bitshares/libraries/wallet/wallet.cpp#L1908
but is not here:
https://github.com/bitshares/bitshares-2/blob/bitshares/libraries/wallet/include/graphene/wallet/wallet.hpp

thanks

**Comment by xeroc** [comment]
duplicate of #382
