### ISSUE TITLE
Committee members with zero vote count despite being voted for

### ISSUE THREAD

**Issue by bigcube** [cryptonomex/graphene#404]
User account Fav has voted for a few committee members but their vote count is zero. BTS2 network has completed a number of maintenance periods but the vote counts were not updated.

Member 1
{
  "id": "1.5.13",
  "committee_member_account": "1.2.21106",
  "vote_id": "0:82",
  "total_votes": 0,
  "url": "smartcoin.pw"
}

Member 2
{
  "id": "1.5.14",
  "committee_member_account": "1.2.23725",
  "vote_id": "0:84",
  "total_votes": 0,
  "url": "graphene.cubeconnex.com/bitcube.html"
}

get_account fav
{
  "id": "1.2.21106",
  "membership_expiration_date": "1969-12-31T23:59:59",
  "registrar": "1.2.21106",
  "referrer": "1.2.21106",
  "lifetime_referrer": "1.2.21106",
  "network_fee_percentage": 2000,
  "lifetime_referrer_fee_percentage": 8000,
  "referrer_rewards_percentage": 0,
  "name": "fav",
  "owner": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "BTS5poFTVoUUtHJ7t5f1dDzGoHLQads69zeNb3qVmbmExYMLC5Lww",
        1
      ]
    ],
    "address_auths": []
  },
  "active": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "BTS5poFTVoUUtHJ7t5f1dDzGoHLQads69zeNb3qVmbmExYMLC5Lww",
        1
      ]
    ],
    "address_auths": []
  },
  "options": {
    "memo_key": "BTS5poFTVoUUtHJ7t5f1dDzGoHLQads69zeNb3qVmbmExYMLC5Lww",
    "voting_account": "1.2.5",
    "num_witness": 17,
    "num_committee": 4,
    "votes": [
      "1:22",
      "1:24",
      "1:25",
      "1:26",
      "1:27",
      "1:28",
      "1:29",
      "1:30",
      "1:32",
      "1:35",
      "1:36",
      "1:38",
      "1:40",
      "1:44",
      "1:49",
      "0:50",
      "1:52",
      "1:56",
      "2:66",
      "2:73",
      "0:76",
      "0:82",
      "0:84"
    ],
    "extensions": []
  },
  "statistics": "2.6.21106",
  "whitelisting_accounts": [],
  "blacklisting_accounts": [],
  "blacklisted_accounts": [],
  "cashback_vb": "1.13.52"
}

**Comment by abitmore** [comment]
Not only committee members, but also witnesses (and workers?). It's a side effect of the design for better performance. Currently only the numbers of who "are voted in" will be updated at maintenance point.

**Comment by roadscape** [comment]
On the mumble Dan said that votes are tallied accurately, but they are only SHOWN accurately for **active** committee members/workers/witnesses. 

So there's currently no way to see accurate total_votes for any inactive object.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#110
