### ISSUE TITLE
Documentation For Websocket Subscriptions Needs Changing?

### ISSUE THREAD

**Issue by SterL** [cryptonomex/graphene#420]
On this page: https://github.com/cryptonomex/graphene/wiki/websocket-rpc-howto under "Here is an example of a full session: ", it gives this example json: {"id":1,"method":"call","params":[0,"login",["",""]]} 

However, I believe it should be this: {"id":1,"method":"call","params":[1,"login",["",""]]}

When calling the way you have it with a 0 in the params, we get in error. Put a 1 in the params and we get the expected result.

**Comment by theoreticalbts** [comment]
Good catch.

**Comment by theoreticalbts** [comment]
That wiki article is badly outdated, so I deleted it.  More complete and up-to-date documentation is available in [README.md](https://github.com/cryptonomex/graphene/blob/master/README.md) -- or just go to https://github.com/cryptonomex/graphene and scroll down
