### ISSUE TITLE
Create a gitter chat room for cryptonomex/graphene repository

### ISSUE THREAD

**Issue by noisy** [cryptonomex/graphene#421]
You may heard about https://gitter.im/ - This is a tool design for developers. Every repository can have own chat root well integrated with github. There is a activity feed which shows recent issues and pull requests. Gitter has support for markdown and code syntax highlighter which is great during conversations about code.

I first realize how powerful tool is it during contributing for [cookiecutter-django](https://gitter.im/pydanny/cookiecutter-django) projects. Gitter is well known in developers community thanks to gitter badges which are often placed on the top of README.md file, next to another badges.

![selection_205](https://cloud.githubusercontent.com/assets/201263/10855636/1d3b2f9c-7f43-11e5-9baf-e031a64fd574.png)

Gitter allows for private rooms, but by defaults all rooms are public and free of charge. In my opinion this is a great way of sharing knowledge about the code outside the core developers.

**Very important note:**

This is not just another chat for bitshares users. Gitter is for people who care about the code.

**Comment by kenCode-de** [comment]
I'll second this motion. +1 +1 +1 
..and by the way, where is this CNX Telegram app I have been hearing about? 
Tox is encrypted voice and video, along with chat: https://tox.chat

**Comment by noisy** [comment]
BTW. did I mentioned, that gitter has an IRC gateway? :) https://irc.gitter.im/

**Comment by theoreticalbts** [comment]
Off-topic.  We use Slack for our dev chat.

**Comment by noisy** [comment]
@theoreticalbts Could you describe, how I could join this chat?
