### ISSUE TITLE
Many things need to be moved to a plugin

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#422]
Things in core that need to move to plugins:

Indexes:
- `account_member_index`

Objects:
- `impl_account_transaction_history_object_type`
- `impl_witness_schedule_object_type`
- `impl_budget_record_object_type`
- remove `impl_reserved0_object_type`
- remove `custom_object_type`
- `operation_history_object_type`

Fields:
- `account_object.whitelisted_accounts`
- `account_object.blacklisted_accounts`
- `witness_object.last_aslot`
- `witness_object.url`
- `witness_object.total_missed`
- `witness_object.last_confirmed_block_num`
- `dpo.recent_slots_filled`
- `dpo.last_irreversible_block_num`
- `dpo.recently_missed_count`

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#116
