### ISSUE TITLE
Database API get_proposed_transactions add public key to search

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#433]
The proposal update transaction can include public key approvals.  So this should probably also search on public key approvals: 

https://github.com/cryptonomex/graphene/blob/9b0abe27908af7ba3b856fc0d026743bc10ff1f4/libraries/app/database_api.cpp#L1384-L1400

**Comment by jcalfee** [comment]
On second though, that may require another API call.  I currently don't have any cases for this so we should probably just keep this in mind but wait on the change...

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#123
