### ISSUE TITLE
Add support for proposal transaction to database_api_impl::get_required_fees

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#434]
I'm passing a full transaction with one operation: proposal_create

proposal_create has proposed_ops (array operation) .. It looks like it gets to this array and expects an object: 

`{"code":1,"message":"7 bad_cast_exception: Bad Cast\nInvalid cast from type 'array_type' to Object\n    {\"type\":\"array_type\"}\n    th_a  variant.cpp:568 get_object","data":{"code":7,"name":"bad_cast_exception","message":"Bad Cast","stack":[{"context":{"level":"error","file":"variant.cpp","line":568,"method":"get_object","hostname":"","thread_name":"th_a","timestamp":"2015-11-05T16:15:22"},"format":"Invalid cast from type '${type}' to Object","data":{"type":"array_type"}}]}}`

It would be reasonable to recurse into this array but simply append to the return `vector<asset>` .. The caller knows the object graph and can still place the fees correctly back into the transaction.

**Comment by jcalfee** [comment]
I'm passing a full transaction with one operation: proposal_create

proposal_create has proposed_ops (array operation) .. It looks like it gets to this array and expects an object (like most other typical transactions): 

`7 bad_cast_exception: Bad Cast↵Invalid cast from type 'array_type' to Object↵ {"type":"array_type"}↵ th_a variant.cpp:568 get_object`

It would be reasonable to recurse into this array but simply append to the return `vector<asset>` .. The caller knows the object graph and can still place the fees correctly back into the transaction.

**Comment by jcalfee** [comment]
I have added a recursive call to go into a proposal_object and calculate the fees for its operations, I simply want to flatten all the fee objects and return one list...

I think there is only 1 issue:  `op (source is not a pointer)`

``` c++
vector<asset> database_api_impl::get_required_fees( const vector<operation>& ops, asset_id_type id )const
{
   vector<asset> result;
   // dynamic size (I hope) ?
   //result.reserve(ops.size()); 
   const asset_object&  a = id(_db);
   for( const auto& op : ops ) {
      const auto& pop = dynamic_cast<const proposal_object*>(op);//  op (source is not a pointer)
      if( pop != nullptr ) {
          result.push_back( _db.current_fee_schedule().calculate_fee( op, a.options.core_exchange_rate ) );
          for( const auto& asset : get_required_fees( pop.proposed_ops, id ) )
             result.push_back( asset ); // new, but this should work 
      } else {
          result.push_back( _db.current_fee_schedule().calculate_fee( op, a.options.core_exchange_rate ) );
      }
   }
   return result;
}
```

(edited)

jcalfee [9:08 AM]
original: https://github.com/cryptonomex/graphene/blob/9b0abe27908af7ba3b856fc0d026743bc10ff1f4/libraries/app/database_api.cpp#L1363-L1371

**Comment by theoreticalbts** [comment]
Proposal does not take a vector of `operation`, rather it takes a vector of `op_wrapper`, where `op_wrapper` is a class containing a single member called `op` of type `operation`.

**Comment by theoreticalbts** [comment]
Merged to develop, awaiting review.

**Comment by jcalfee** [comment]
theoretical [4:29 PM]
note in particular how proposed_ops is different from what you have -- i have "proposed_ops":[{"op":[0,...]}] and you have "proposed_ops":[[0,...]]

jcalfee
Is it easy to remove the "op":?  That's going to save the client from having to clone and recursively change the transaction.

I would like to look into this in the c++ side as soon as I have a chance.  This is just the finishing touches.  I'm sure your very busy with other stuff.

**Comment by jcalfee** [comment]
The above is not an issues, it is in the serializer format.  I'll verify (review) after fixing this:  https://github.com/cryptonomex/graphene/issues/439

**Comment by jcalfee** [comment]
reviewed, it works

**Comment by theoreticalbts** [comment]
Still needs merged.

**Comment by theoreticalbts** [comment]
Merged.
