### ISSUE TITLE
Vesting not working properly

### ISSUE THREAD

**Issue by tonyk2** [cryptonomex/graphene#441]
Both for the Life Time member and his referrer.

https://bitsharestalk.org/index.php/topic,19961.msg256350.html#msg256350

**Comment by roadscape** [comment]
Also.. someone suggested this may be due to the fee SCALE being ignored when doing the calcs.

**Comment by theoreticalbts** [comment]
Three different referral system bugs have been identified:  #449 #453 #455 .  Closing, as discussion should move to those tickets.
