### ISSUE TITLE
Referral lifetime upgrade split does not work correctly

### ISSUE THREAD

**Issue by mindphlux1** [cryptonomex/graphene#443]
Fav signed up 2 users that both have upgraded to LT.

They paid 20k each.

Fav received 6k instead of 12k per lifetime upgrade.

Fav has now a total of 12k instead of 24k vesting. There seems to be a problem that the FACTOR is not applied to lifetime upgrades when calculating the referral program 'payouts'

Please see this thread for details:
https://bitsharestalk.org/index.php/topic,19961.0.html

**Comment by theoreticalbts** [comment]
Will be fixed by #449 #453 #455
