### ISSUE TITLE
Distribute Market Fees on Core Asset to Referral Program

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#446]
Currently the BitShares network does not charge a percentage based market fee on trades of the core asset (BTS) or assets created by the committee account (BitAssets like USD, CNY, etc). Instead BitShares has a fixed price for filled orders defined by the order creation fee.  See Worker Proposal #445 for more information.

This proposal is to implement a hard-fork that would grant committee members the option to charge market fees for their assets. Any market fees earned would be converted to BTS via the fee pool and then distributed to the referral program like any other fees.

Contractor: Cryptonomex
Cost: $4500
Escrow: Bunkerchain Labs
Escrow Cost: $450
Worker: TBD
Worker Terms: 2M BTS paid over 40 days at 50,000 BTS per day.  Bunkerchain Labs will sell the BTS to raise $4950 and refund any remaining BTS to the blockchain.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#127
