### ISSUE TITLE
Open Source Graphene UI for BitShares

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#447]
Under this proposal the Graphene-UI repository (https://github.com/cryptonomex/graphene-ui) will be licensed under the following options:
1. GPL 3.0 for all users 
2. BSD for use with the BitShares blockchain 
3. Non-GPL use with other blockchains will be available for purchase from Cryptonomex.

The benefits this has to the BitShares ecosystem is lower barriers to entry for startups wanting to create their own wallet services and exchanges as well as being fully Open Source to improve marketing/PR for the bitshares blockchain.  Companies such as BitCash, OpenLedger, and other startups will have larger margins and higher incentives which should help increase marketing for BTS.

The new license will take effect immediately upon the first fully funded day.

Contractor: Cryptonomex
Escrow: None
Cost: 10M BTS
Worker: TBD

10M BTS to be paid out over 1 year at 28,000 BTS per day. Any surplus BTS will be refunded to the network. By paying over 1 year, the 10M BTS is effectively vesting linearly over a period of 1 year.  Cryptonomex will be required to sell enough to cover taxes at the time the funds are received but otherwise will attempt to retain the remaining BTS as an investment.

**Comment by noisy** [comment]
@bytemaster any progress?

**Comment by svk31** [comment]
@xeroc Can we close this? This was handled differently in the end afaik, and the GUI is now MIT licensed.
