### ISSUE TITLE
market subscription results differ from get_short_orders/get_limit_orders

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#45]
The results from a market subscription return a very different object for the same order type compared to the get_short_orders and get_limit_orders calls, there might be a reason for this but would it be possible to harmonise them to use the same structures? 

``` javascript
get_limit_orders 1.4.1 1.4.0 1:
[{
    "id": "1.8.3",
    "expiration": "2015-06-13T19:24:54",
    "seller": "1.3.11",
    "for_sale": 9791100,
    "sell_price": {
      "base": {
        "amount": 9900000,
        "asset_id": "1.4.0"
      },
      "quote": {
        "amount": 10000,
        "asset_id": "1.4.1"
      }
    }
  }]
```

market sub result:

``` javascript
[[1, {
   "amount_to_sell": {
      "amount": 5, 
      "asset_id": "1.4.0"
   },
   "expiration": "2020-01-01T00:00:00",
   "fee": {
      "amount": 0, 
      "asset_id": "1.4.0"
   },
   "fill_or_kill": false,
   "min_to_receive": {
      "amount": 800, 
      "asset_id": "1.4.1"
   },
   "seller": "1.3.11"
}]
,[1,"1.8.1"]]
```

**Comment by nathanielhourt** [comment]
Interesting. Looks like the market subscription is handing you back the operation that created the order rather than the order it created...

In an ideal world, what exact data would you like the market subscription to give you?

**Comment by svk31** [comment]
Ideally I would like to have the first type of structure, the same as what you get when asking for the orderbook. This way I can just update the orderbook directly with the new orders, while what I'm doing now is simply using the subscription notification to fire off api calls to refetch the shorts, limit orders, call orders and settle orders. Having the data directly in the subscription would save a lot of rpc calls.

I'm also seeing an issue with partial fills. A partial fill does not get reflected in get_limit_orders, it always gives the original order. If I'm subscribed to a market I can take the fill_order that I get and update the partially filled order, but someone arriving after the fact won't have the accurate state of the orderbook.

**Comment by bytemaster** [comment]
The market subscription results will be different because we cannot assume the order still exists.  They are giving you an operation history not a set of active orders.   If you want to fetch the active order, look at the ID of the order created and fetch that.

**Comment by nathanielhourt** [comment]
I think what he's saying is that the existing subscription API is not particularly useful, and a much more useful subscription would notify of new order objects, modified objects, and deleted objects within a given market pair.

**Comment by svk31** [comment]
Yea exactly Nathan, right now I can only use it to trigger another full refresh of the market, which is a brute force approach. I could make it slightly smarter and determine what I need to fetch depending on the results returned by the subscription, but I still wouldn't make direct use of the objects returned to update the markets, I'd only need the operation type to do so.

**Comment by bytemaster** [comment]
If you subscribe to the actual order IDs then you will receive updates when they are deleted or partially filled.

The existing callback will give you the order ID which will notify you of NEW orders on the books.  

With these APIs there is nothing more that is needed.   

If you subscribe_to_objects( [IDs....] ) then you will get a call back with the object value every time it changes, if the object is deleted then you will get a callback with just the "ID" of the deleted object.

**Comment by svk31** [comment]
So you're saying we should subscribe to every single open order for a given market? That sounds unsustainable to me, imagine a thousand users subscribing to a thousand orders, that's a million subscriptions already, can we handle that many? 

Again, what I'd like us to do is really make use of the websocket functionality to automatically push complete updates whenever a market changes, not simply notify that a market has changed which will then trigger additional round-trips to the server to fetch the actual data.

**Comment by svk31** [comment]
Closing this as it's outdated and the discussion above is no longer accurate.
