### ISSUE TITLE
BitStamp Style - Instant Order 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#450]
BitStamp supports an instant order feature that is designed to get the buyers or sellers the best price possible without them having to worry about setting the price or constantly moving their order.  

```
    When you place an instant order, we add an order at the current bid or ask price (depending on the type of the order). If there is not enough bitcoins available at that price, our trading engine will then reposition your order every second to the current order book offer.
```

If someone wants to sell bitcoin, then the price is set to the lowest sell offer and continues to automatically move with the lowest sell offer as the books change.  

If someone wants to buy bitcoin, then the offer is set to the highest buy offer and continues to automatically move with new bids.  

The end result is a user interface where the buyer / seller automatically get the best possible price without having to "cross the spread". Rather than prioritizing these orders by price, they are prioritized by first come, first serve.  This creates a lot of liquidity on either side of the price by users who want a set-it and forget it system. 

To implement this feature within bitshares would require adding a new order type and a priority queue combined with matching all orders against this priority queue prior to considering other limit orders. 

In addition to requiring a hardfork, this would also require significant updates to the user interface to support the new operation types.

Bunkerchain Labs will be responsible for all acceptance testing to verify that the features are properly implemented and that the product has been delivered properly. Their fee includes all of the overhead associated with managing the worker proposal and associated accounting. The assumption is that they will help run a test network, perform actual testing of the user interface to find bugs, and verify that sufficient unit tests have been implemented.  In other words they provide QA for BitShares and are a source of accountability for Cryptonomex. 

Contractor: Cryptonomex
Cost:  $30,000 
Worker: TBD
Escrow: Bunkerchain Labs
Escrow Cost: $3000

**Comment by wmbutler** [comment]
I have UX'd this on the graphene-ui side:

https://github.com/cryptonomex/graphene-ui/issues/457

**Comment by cassiopaia** [comment]
mh .. 10% for an escrow ? .. IMO this i a bit much ...

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#128
