### ISSUE TITLE
Margin Trading 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#451]
BitShares is an exchange that is competing with various centralized exchanges. By offering margin trading users of BitShares have an opportunity to earn interest while giving traders leverage. Properly implemented Margin Trading can ensure that lenders are always made whole and only lose their interest in extreme cases. 

The basic idea is to track the total market depth before and after every partially filled order or canceled order. Any time there is insufficient market depth to close all open margin positions, margin calls occur.  

The full scope of this proposal and algorithm must be defined prior to setting a price for this particular worker proposal. Initial estimates are at least $60,000 to properly implement and test this with a GUI. This ticket has been created to foster discussion and will be updated as details of the proposal are outlined.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#129
