### ISSUE TITLE
Maintain Proxy Voting Totals ($3000)

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#454]
The purpose of this proposal is to update the graphene code to keep vote totals up to date for all witnesses, committee members, and ultimately every account that has proxy votes.

This will improve transparency and allow people to easily audit the power structure of BitShares to know who has influence and how much. 

This proposal would be to provide an API that will return all accounts that have a particular user set as their proxy. It would also update the Account/Voting page for a particular user to display their total influence along with a list of all accounts that are actively proxying through them.

No hard fork will be required, and enabling this extra tracking would be optional for witness nodes looking to save CPU and Memory but can be enabled for block explorers and API nodes looking to feed data to the wallet.

Contractor: Cryptonomex
Cost: $3000
Worker: 
Escrow:  BunkerChain Labs

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#131
