### ISSUE TITLE
Worker Proposal submission fails to display at http://cryptofresh.com/workers

### ISSUE THREAD

**Issue by wmbutler** [cryptonomex/graphene#456]
```
create_worker "billbutler" "2015-11-21T00:00:00" "2016-02-21T00:00:00" 500000000 "Bitshares UI Project Manager" "https://docs.google.com/document/d/14d9bBAyUoB9wcBpFnYoGpE1MF0RnOwMKpF2Z8eh0QkI/edit?usp=sharing" {"type" : "vesting", "pay_vesting_period_days" : 30} true
{
  "ref_block_num": 43551,
  "ref_block_prefix": 4241440461,
  "expiration": "2015-11-04T19:39:45",
  "operations": [[
      34,{
        "fee": {
          "amount": 200000,
          "asset_id": "1.3.0"
        },
        "owner": "1.2.21594",
        "work_begin_date": "2015-11-21T00:00:00",
        "work_end_date": "2016-02-21T00:00:00",
        "daily_pay": 500000000,
        "name": "Bitshares UI Project Manager",
        "url": "https://docs.google.com/document/d/14d9bBAyUoB9wcBpFnYoGpE1MF0RnOwMKpF2Z8eh0QkI/edit?usp=sharing",
        "initializer": [
          1,{
            "pay_vesting_period_days": 30
          }
        ]
      }
    ]
  ],
  "extensions": [],
  "signatures": [
    "1f4328ed866d1f21a2e1d07180fbeed95baf718c07198631c2e5b4a248182c7bed3d2a375fb127b04802b9ea371710ea9ec628b48162df5db4b4df6dfc95f919fd"
  ]
}
```

**Comment by theoreticalbts** [comment]
If you do `get_account_history` on the account, you can see that this worker creation it is not included in the account history, and expiration is very far in the past.  So for whatever reason, this transaction wasn't included in the chain -- the worker creation never happened.

I have no conclusive explanation for why it wasn't included in the chain if the CLI wallet didn't give you any errors.  Probably some networking issue on the p2p network -- it just somehow didn't reach the witnesses in time to be included.  So you should probably just create a new worker.

**Comment by wmbutler** [comment]
I'm connected to my own local full node. I suppose it's possible that my full node is not connected to the network?

**Comment by wmbutler** [comment]
That was it. Once I connected to a proper full node, everything was fine.
