### ISSUE TITLE
Are fees enabled in cashback_test?

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#461]
Looks like 8c91d17301a942a72260b19b421bab799701d753 removed `enable_fees()` call from `cashback_test`.  This test needs to be evaluated whether the fees are still nonzero, or if this commit inadvertently disabled the fees that are supposed to be tested.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#162
