### ISSUE TITLE
Issues compiling from cmake

### ISSUE THREAD

**Issue by Jzarecta** [cryptonomex/graphene#463]
Tried compiling from source:

```
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TSL_LIBS = 

-- Finished fc module configuration...
-- egenesis: 
-- embed_genesis_args: -t/home/.../Downloads/graphene/libraries/egenesis/egenesis_brief.cpp.tmpl---/home/.../Downloads/graphene/libraries/egenesis/egenesis_brief.cpp-t/home/jza/Downloads/graphene/libraries/egenesis/egenesis_full.cpp.tmpl---/home/.../Downloads/graphene/libraries/egenesis/egenesis_full.cpp
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/.../Downloads/graphene/libraries/fc/Boost_INCLUDE_DIR
   used as include directory in directory /home/.../Downloads/graphene/libraries/fc

-- Configuring incomplete, errors occurred!
See also "/home/.../Downloads/graphene/CMakeFiles/CMakeOutput.log".
```

**Comment by theoreticalbts** [comment]
You need Boost 1.57 or later.  More detailed instructions for building on Ubuntu Linux are available at https://github.com/cryptonomex/graphene/wiki/build-ubuntu

**Comment by Jzarecta** [comment]
I have boost 1.59.0-3 on Arch Linux.

**Comment by xeroc** [comment]
`git submodule update --init --recursive` maybe?

The sources compile flawlessly with my ArchLinux

**Comment by theoreticalbts** [comment]
Sounds like your cmake can't find Boost for whatever reason.  Suggest checking:
- Do you have Boost module for `cmake` installed?
- Do you have `pkg-config` installed and able to find Boost?
- Do you have Boost in nonstandard location?
- Is there any information in`CMakeOutput.log`?

As this ticket doesn't include steps to reproduce the problem, Arch is not officially supported platform, and @xeroc says it works for him, I'm going to close this ticket.  If you still have problems, feel free to visit the community technical support forum at https://bitsharestalk.org/index.php/board,45.0.html
