### ISSUE TITLE
Fill operations contain no information about market fees

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#464]
Playing around with market fees on a local testnet I've noticed that there's no data whatsoever indicating that market fees were charged. In a market with 50% market fees I placed an order to buy 6 USD, and only received 3 USD even though the fill operations say I received 6 USD as can be seen from the screenshot:

![image](https://cloud.githubusercontent.com/assets/6890015/11456388/4ff9a8ea-9687-11e5-89b0-b73847fbd3fb.png)

The missing 3 USD obviously went to the fee pool for the market due to the 50% market fee.

Here's the operation json for the first fill of 5 USD, as you can see there's no indication of market fees being charged:

```
[
0: 4,
1: {
  account_id: "1.2.7",
  fee: {
    amount: 25000,
    asset_id: "1.3.2"
  },
  order_id: "1.7.16",
  pays: {
    amount: 200000000,
    asset_id: "1.3.0"
  },
  receives: {
    amount: 50000,
    asset_id: "1.3.2"
  }
}
]
```

**Comment by theoreticalbts** [comment]
Yeah those market fees should be recorded in the v-op, and displayed in the GUI too...

**Comment by theoreticalbts** [comment]
Actually the fee is recorded, from the JSON:

```
fee: {
    amount: 25000,
    asset_id: "1.3.2"
  },
```

That's a 2.5 USD fee right there.

The GUI should be updated to show you got 5 USD but payed 2.5 USD fee.  The data you need is there, it's purely a GUI level problem, not a backend problem.

**Comment by theoreticalbts** [comment]
Closing, discussion should move to the above `graphene-ui` ticket as this is a UI problem.
