### ISSUE TITLE
Test framework needs refactoring

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#469]
Some tests their use own database, others use fixture.  This is a sign that the fixture incorrectly assumes a single DB should be sufficient; we need a fixture that can manage multiple DB's.

Many methods have implicit inputs or outputs related to the `trx` field, which is effectively a global variable (ugh).  For implicit outputs, see almost any `database_fixture` convenience method.

For implicit inputs, for example `create_sell_order` does not set the expiration on `trx`, so effectively its output expiration is dependent on the value of expiration at input.

Many of the methods of `database_fixture` are candidates for a reusable API that should exist somewhere else.  For example, `cli_wallet` effectively duplicates some of the higher-level convenience methods of `database_fixture`.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#133
