### ISSUE TITLE
market history

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#47]
As far as I can tell there's no api call to get the market history for a given market. We'll need this to construct price history charts in the GUI and to display the order history.

**Comment by bytemaster** [comment]
bucket-size = 1
bucket-size = 60
bucket-size = 86400

adding those lines to config.ini will give you 1 sec, 1 minute, and 1 day resolution in the market history plugin.

**Comment by bytemaster** [comment]
Everything appears to be working.

**Comment by svk31** [comment]
I still can't get any results out of this api call, it always returns an empty array. Using these settings: 

```
# Track market history by grouping orders into buckets of equal size measured in seconds, may specify more than one bucket size
bucket-size = 60
bucket-size = 300
bucket-size = 1800

# How far back in time to track history for each bucket size, measured in the number of buckets (default: 1000)
history-per-size = 1000
```

I'm passing these arguments:

> 1.3.0 1.3.1 60 2015-06-27T08:39:33 2015-07-07T08:39:33

Using the cli_wallet I also get an empty array back

**Comment by svk31** [comment]
Update: the api call works but only using a single bucket-size setting in config.ini. Once I define more than one I only get empty arrays in response.

**Comment by svk31** [comment]
This still doesn't work, can we get it working for launch please?

**Comment by svk31** [comment]
Oh and the thing that doesn't work is still only price history for chart data, we still do not have a market history api call to display the order history for a given market. If our purpose is to be an exchange we really need this!

**Comment by abitmore** [comment]
Any progress? How can we release without this feature?

**Comment by noisy** [comment]
@bytemaster any updates? lack of history on markets is a serious issue IMO.

**Comment by kryo2k** [comment]
bump

**Comment by maqifrnswa** [comment]
Also needed for algorithmic trading, which is needed for liquidity

**Comment by bytemaster** [comment]
Closing this issue because we have a history.  A new issue should be created with specific changes if the current solution is not good enough.
