### ISSUE TITLE
Implement sign_message utility

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#470]
BitShares' global public name-to-key mapping is the beginnings of a general public key infrastructure, but it is missing some pieces, such as the ability to sign arbitrary message with a key.

Message signing should include a unique role identifier for the message, so cross-protocol attacks aren't possible.  I.e. if the user has the same key in protocol A and protocol B, it might be possible to trick a program which signs messages for protocol A on behalf of the user into signing a message which is a valid, harmless protocol A message, but a valid, malicious message in protocol B.  If A and B have different global hashes which must be included in the signed hash, this attack becomes impossible.  Similar rationale to chain ID.

**Comment by theoreticalbts** [comment]
I'd started this in a local repo, pushed it to branch https://github.com/cryptonomex/graphene/tree/470-util-sign-message

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#134
