### ISSUE TITLE
Implement balance_log utility

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#473]
Any reinterpretation of past transactions should not change user balances.  Thus, it will be useful to create a utility which takes a blockchain directory, hooks `changed_objects` DB signal, replays the chain, and logs all balance changes.

Such utility should be run before every upgrade to ensure that the new code doesn't change balances.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#135
