### ISSUE TITLE
Asset supply mismatch triggered during unit tests

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#474]
I get this `edump()` during unit test run:

```
1155794ms th_a       db_debug.cpp:82               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 902
```

First, we need to fix it.

Second, our testing framework should flag this condition as fatal.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#136
