### ISSUE TITLE
Audit of accounts & referral system percentages - report attached

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#476]
I wanted to check the distribution of network, registrar, referrer, and lifetime referrer reward percentages.

The following table shows all unique configurations with their frequencies. I thought it might be useful for the other devs, and I also have a few questions.

![](https://i.imgur.com/SyydVkf.png)

Explanation:

A = "Party A"
B = "Party B"
I = "self" 
Where the cells are blank, the reward is 0.
Registrar % is calculated as: _100% - network_pct - lifetime_referrer_pct - referrer_pct_

Questions:
- With the planned fix, what happens with all 1% rewards?
- Who gets cut short when the rewards to add up to more than 100%?

**Comment by theoreticalbts** [comment]
`referrer_pct` is a fraction of what's left, formula should be `(100% - network_pct - lifetime_referrer_pct) * (100% - referrer_pct)` -- the idea being that the account creation op has a valid range from 0-1.  Yes, we should have probably done that with `lifetime_referrer_pct` too for consistency, but we didn't.

Closing ticket as obsolete.
