### ISSUE TITLE
Improve index on account operation history

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#477]
Operations are now indexed by account and sequence for efficient traversal and query.

**Comment by theoreticalbts** [comment]
I created this ticket in response to commit 1628270e88b20278a00b05c80ac6bd4816fc8a8a appearing on the master branch.

If you have a commit like this, please file an issue and create a branch.  When the commit is ready for review, put it on the develop branch.  Please don't put it onto master until it is reviewed and tested.

**Comment by theoreticalbts** [comment]
This particular commit needs to not update FC.

**Comment by theoreticalbts** [comment]
What is the use case for this?  There are several reasons why I want to reject this commit:
- We were planning on putting account history on disk.  Giving additional indexes on account history will encourage us to use them.  Such usage will make putting those records on disk harder in the future.
- History tracking is bad for memory usage and adding more indexes will only increase the problem.  This would be less of a problem if we had some way to disable account history tracking altogether, specify only particular accounts to track, or put history tracking into a plugin.
- Account history tracking doesn't belong in core.  It should go into a plugin.  We should be striving to minimize the amount of new code which goes into core "temporarily" until the modular plugin architecture is implemented.

**Comment by theoreticalbts** [comment]
New branch created at https://github.com/cryptonomex/graphene/tree/477-history-account-history-indexing

**Comment by mvandeberg** [comment]
It is in a plugin and is configurable.

**Comment by mvandeberg** [comment]
67b9f5ba7c8904e4ff35928467fadf0ae5d3c73e Tested and validated then new get_relative_account_history API call and fixed a bug in the existing get_account_history API call.

**Comment by theoreticalbts** [comment]
Reopening so this gets merged.

**Comment by theoreticalbts** [comment]
I guess I lost this battle...at least I have rebased it so there is no longer an FC conflict
(edit:  by "I lost this battle" I mean "my above decision to reject this patch was overruled even though the points I raised weren't addressed")

**Comment by abitmore** [comment]
Use case: "this ... will help exchanges big time .. especially bittrex currently has problems with the account history call"

By the way, the new API will likely make witness_node use more memory. According to discussions in #621, perhaps we'll have memory issue soon. So it's best if we can evaluate how much more memory usage introduced by this new feature, and/or optimize.

**Comment by xeroc** [comment]
@mvandeberg 
From what I understand, `start` and `stop` in `get_relative_account_history` are the unique sequence numbers of the account specific history. Thus having `start=1` and `stop=`10` will give me the very first operations done in my account. That is nice for pagination.

However, if I want to create a pagination the other way round (most recent ops first), I have no way of knowing the sequence number of the most recent op and thus cannot go to the _second_ page for pagination because I can't know what the first op on the second page would have as a sequence number .. Am I missing something?

**Comment by theoreticalbts** [comment]
Leaving to @mvandeberg to close this (if he wants to answer the above question)

**Comment by mvandeberg** [comment]
I believe it returns operations most recent to oldest. So passing 0 and int max will get you the most recent ops. If you do 1-10, it will return them in reverse order (most recent to oldest). That is what makes sense based on the behavior of get_account_history. These methods should work identically except that one uses operation ids (a global sequence number) vs a sequence number unique to the account.
