### ISSUE TITLE
Forbid publishing non-null core exchange rate for MIA backed by non-CORE asset

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#482]
The current core exchange rate check logic for feeds is incorrect for non-CORE backed MIA's, as noted in #480

For now, the chain only does the right thing when the core exchange rate is null.  So this ticket is for a witness-only hardfork which has the witnesses only accept null core exchange rate for MIA backed by non-CORE asset.

Since this change merely restricts the set of possible valid transactions, and does not change the semantics of any transaction, it suffices to only upgrade (a majority of) the active signing witnesses.

The trade-off is that fees cannot be paid using an MIA backed by a non-CORE asset.  A hardfork to accept such MIA can be implemented as a second hardfork which will require all nodes to upgrade -- but that second hardfork can be deferred (we don't want to hardfork too often because it inconveniences users and exchanges).

This strategy allows us to capture 90% of the value (get non-CORE-backed MIA's up and trading) without inconveniencing users with a mandatory hardfork for functionality they likely don't even use.

**Comment by abitmore** [comment]
So why rush out v2.0.151215? As it says "All full nodes will need to upgrade by Wed 2015-12-16 at 18:00 UTC" when is just one day after the hardfork introduced by v2.0.151209.

**Comment by abitmore** [comment]
Because #481 is too critical?

**Comment by theoreticalbts** [comment]
Yeah, we just went ahead and rolled out the hardfork as part of #481 fix.
