### ISSUE TITLE
Clearing force settlement orders is incorrect

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#485]
There are some nodes getting stuck in `clear_expired_orders()`.

**Comment by theoreticalbts** [comment]
On closer analysis of the code, there are no obvious bugs.  The commit compiles now, overwrote it with push -f.  I maintained my changes to `object_id.hpp` as a separate commit, I would like those changes in particular to be reviewed.

**Comment by theoreticalbts** [comment]
See #478 for backtrace

**Comment by bytemaster** [comment]
https://bitsharestalk.org/index.php/topic,20631.new.html#new

**Comment by roadscape** [comment]
I encountered this issue last night, here's the backtrace:
https://bitsharestalk.org/index.php/topic,19507.msg270657.html#msg270657

**Comment by theoreticalbts** [comment]
@roadscape would you happen to have a datadir that reliably gets stuck?

**Comment by roadscape** [comment]
Reliably, no.. but if it happens to my main node again I'll archive and upload the datadir/logs

**Comment by abitmore** [comment]
@theoreticalbts I have a stuck witness_node running in gdb right now. What can I help?

**Comment by theoreticalbts** [comment]
The rebase patch needs to fix [this flipped inequality](https://github.com/cryptonomex/graphene/blob/bf147aea10cc8c9b771d8e03438157dda797fcac/libraries/db/include/graphene/db/object_id.hpp#L143-L146) and implement `operator>` for `object_id_type`.

**Comment by theoreticalbts** [comment]
This might have been fixed by one of the previous commits, putting it on hold until we figure out whether we see this one in the wild again (hopefully not).

**Comment by theoreticalbts** [comment]
Leaving this open for now, if we don't see any new reports of this when time rolls around for the next release, it should be declared "fixed" and closed.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#139
