### ISSUE TITLE
should websocket api send notification when order object is filled?

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene#488]
Right now, "set_subscribe_callback" websocket will send all updated objects to the callback. However, if an order object (1.7.*) is filled, and thus no longer included in the blockchain, no notification is sent. If a user is monitoring the order object to see if it is still "on the books," they will miss the change.

Should order objects not included in the chain (since they are filled) send a notification when they are filled?

**Comment by svk31** [comment]
Filled orders are deleted so the notification is simply the object id itself.

**Comment by xeroc** [comment]
> Filled orders are deleted so the notification is simply the object id itself.

That explains a lot .. I have wondered about those notifications that are plain object IDs and not even JSON objects ..

**Comment by svk31** [comment]
Yea any notification that only contains an ID is an object deletion.

This is the code handling object deletions in the GUI:

https://github.com/cryptonomex/graphene-ui/blob/master/dl/src/api/ChainStore.js#L147-L185

**Comment by xeroc** [comment]
Thanks for letting me know .. I just ignore all these nonJS messages in the python libraries atm

**Comment by theoreticalbts** [comment]
I think the outcome of this discussion is that notification does happen and there is no bug, so I'm going to close this.

I should note that you can also look for the `fill_order_operation` which is a virtual op [1] emitted when the order is filled.

[1] A virtual op is created spontaneously by the chain (as opposed to a "normal" non-virtual op which is included in a transaction signed by a user).

**Comment by xeroc** [comment]
Is there a way to get notified of orders that are only partially matched? @svk31

**Comment by abitmore** [comment]
@xeroc good question. Should this issue be re-opened?

**Comment by theoreticalbts** [comment]
@xeroc I think the order object changes, and also partial fill v-op(s) will appear in the op history of the order's owner.
