### ISSUE TITLE
account object does not contain whitelisted_accounts array

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#489]
This appears to be missing from the account object, only the blacklisted_accounts array is included. This array is needed for https://github.com/cryptonomex/graphene-ui/issues/600

```
    },
    "statistics": "2.6.17",
    "whitelisting_accounts": [],
    "blacklisting_accounts": [],
    "blacklisted_accounts": [
      "1.2.12"
    ]
```

**Comment by theoreticalbts** [comment]
Not really a bug, rather we're adding information that's not needed for validation.

**Comment by svk31** [comment]
Seems like a bug to me since the equivalent data exists for whitelisting_accounts, blacklisting_accounts and blacklisted_accounts. Any chance of someone of looking into this anytime soon?

**Comment by theoreticalbts** [comment]
I guess we weren't reflecting that field...

**Comment by theoreticalbts** [comment]
Fixed, merged.
