### ISSUE TITLE
Feature:  Custom committees

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#491]
Fee-backed assets, or FBA's, will require several pieces.  This ticket describes one of those pieces, custom committees.

In current Graphene release, there are two accounts, `GRAPHENE_COMMITTEE_ACCOUNT` and `GRAPHENE_RELAXED_COMMITTEE_ACCOUNT`.  The semantics of `GRAPHENE_COMMITTEE_ACCOUNT` are as follows:
- Every maintenance interval, the account's authority is updated to the top `N` committee members voted for by the proxies of holders of `CORE` asset.
- Account can only act through proposals which go through a review period of `t` seconds.

This ticket proposes making `committee_size = N`, `committee_asset = CORE` and `review_period_seconds = t` fields in a new object, called `committee_object`.

Every account would then have an `optional< committee_id_type >` which would be set during account creation.  If this field is non-optional, the account's authority
will be set every maintenance interval using the same algorithm on the asset specified in `committee_asset`.

There are some details to fill in:
- An account must now specify which committee(s) it is willing to serve on.  I think a separate `committee_member_object`
  for each committee you are willing to serve on, so a single LTM account can serve on multiple committees (thus well-known
  community members can use their account's existing reputation to help bootstrap trust in a new committee.)  This also allows
  voters to specify preferences of the form "I support Alice for committee C, but not committee D."
- The `committee_member_object` now needs a `committee` field to indicate for which committee it's running.
- By previous point, we need to refer to committee ID's, so the ~~`committee_member_object`~~ `committee_object` will be a protocol object and its ID's will also become part of the protocol.
- Reserve some low-numbered ~~`committee_member_object`~~ `committee_object` for future system-level expansions.
- Index `committee_object` by `committee_asset` field, then compute votes for each asset at most once, regardless of how many committees exist for the asset.
- Spam potential limited by account creation fees, LTM fees for committee members, and voting fees / limits.  Spam potential of custom committees (with or without custom asset) not worse than spam potential of CORE voting.
- Committee members are no longer unique on `committee_member_account`, but unique on the composite key `(committee_member_account, committee)`.

Things to think about:
- How do we do things like `COMMITTEE_ACCOUNT` and `RELAXED_COMMITTEE_ACCOUNT` as separate account objects, but not separate committee objects?
- One idea:  Have a committee object which clones membership of another committee object.  Allows committees and accounts to be 1-1 (every account has own committee object).  This is useful because we can add a field to the committee specifying the account it is for, allowing us to go from committee to account without a new index on the large account set.
- Another idea:  Store the review period in the account object, not the committee object.
- We need a new operation to create a committee member for a committee other than the core committee, as the committee operations don't have extensions field defined.
- Specifying the committee when an account is created can be done by adding an extension to the `account_create_operation`
- Ideally we should make the `COMMITTEE_ACCOUNT` and `RELAXED_COMMITTEE_ACCOUNT` simply exercise the new committee code, so we only do vote counting, etc. in one place.

**Comment by theoreticalbts** [comment]
Actually I am having second thoughts about committee objects being protocol objects.  There is little reason to have multiple accounts with the same committee as their authority, so we can attach the committee to the account instead.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#141
