### ISSUE TITLE
please be consistent with the versioning of releases

### ISSUE THREAD

**Issue by maqifrnswa** [cryptonomex/graphene#495]
All previous bitshares releases had a leading "v." The most recent one did not (2.0.160103b). This breaks any script that assumes versioning will be consistent.

Will future releases have leading v's?

**Comment by theoreticalbts** [comment]
This was due to human error.  We need to improve our release procedures.

**Comment by maqifrnswa** [comment]
Thanks - I also noticed that the tag on the -ui repository is not actually on the bitshares branch, but is on a hanging commit not associated with any branch. This prevents automated detection of new releases using "git describe"
