### ISSUE TITLE
Change License Headers in Code

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#496]
The MIT license at the top-level of the code is inconsistent with the license embedded in every file.   

We should change the header of every file to simply reference the LICENSE.md file

**Comment by theoreticalbts** [comment]
Is this really high priority?

**Comment by xeroc** [comment]
@theoreticalbts:
I can help out if you don't find the time to do so ..

edit: See new branch below
edit2: It appears that I have branched of 'master' instead of 'develop'

**Comment by theoreticalbts** [comment]
@xeroc thanks this saves me some time...In the future, please read https://github.com/cryptonomex/graphene/wiki/How-we-use-version-control
