### ISSUE TITLE
[API] No block History API available

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#497]
Having History API accessible only via **Websocket** after querying for `database` is extremely unpleasant when coding a trading bot.
In my case, I only wanted to provide the last price and the 24h volume as well as lowest ask and highest bid.

I could of course use Futures/Promises or Callbacks, but IMHO there should also be a way to simply poll for the history without needing to use asynchronous websockets

Please consider opening up the history api to RPC requests as well and authenticate for RPC or allow to register for the history API similar to websockets

**Comment by theoreticalbts** [comment]
The real solution to this is allowing you to specify in the configuration file, for each API, whether to expose that API over HTTP.  Which is part of #224, which has officially been deemed Low Priority.

As a workaround, I suggest writing a Python script to proxy websocket calls over HTTP.
