### ISSUE TITLE
Crypto API

### ISSUE THREAD

**Issue by mvandeberg** [cryptonomex/graphene#500]
This issue is for the witness node side of the stealth transfers for https://github.com/cryptonomex/graphene-ui/issues/650

There will be a new API, called crypto, that makes these crypto methods available. https://github.com/cryptonomex/fc/blob/master/src/crypto/elliptic_secp256k1.cpp#L405-L552

**Comment by xeroc** [comment]
Could we have a little more in-source documentation on these calls, please?

**Comment by theoreticalbts** [comment]
Moving discussion about documentation of this feature to #582.  I want to be able to close this so I don't get confused about what is/isn't merged for this release.
