### ISSUE TITLE
Require voted entities to exist

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#501]
Accounts may be able to vote for non-existing entities.  This should not be allowed.

**Comment by theoreticalbts** [comment]
Also, need to make sure the vote count check (you can't vote for a larger `num_committee` than the number of committee members you actually vote for) checks the number of committee members being voted for, not the total number of entities voted for.

**Comment by theoreticalbts** [comment]
Non-trivial since there is no single index for vote entities.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#143
