### ISSUE TITLE
Implement new market API

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#503]
This ticket is for the new market API being implemented by @mvandeberg -- if you are @mvandeberg and/or @bytemaster please write some information about the specification, rationale, and design notes for these changes in this ticket.

**Comment by theoreticalbts** [comment]
I've reformatted the commits which were previously floating in a now-dead version of the develop branch into a new commit by these commands:

```
git checkout origin/master -b 503-api-new-market-api
git checkout 4e80f7628df6092255ea600ffa6191e6a97d09a6 libraries/app/{api,database_api}.cpp libraries/app/include/graphene/app/database_api.hpp
git commit -m "Implement new market API #503" --author=Vandeberg
git rebase --whitespace=fix HEAD~1
```

NB, `origin/master` was 51c10580fa9c547d8dafbd6e374d713850140ff6 at the time of this writing.

**Comment by mvandeberg** [comment]
These changes add a higher level and easier to use API for accessing public market information. The additions are based on the API used by Poloniex. See https://poloniex.com/support/api/ Public API Methods.

**Comment by xeroc** [comment]
This sounds great. It will make the calls for
https://github.com/xeroc/python-graphenelib/blob/master/grapheneexchange/grapheneexchange.py
execute much faster. Currently, I need to maintain _three_ connects (2 x witness, 1 x cli_wallet) to offer a poloniex-style python api

**Comment by theoreticalbts** [comment]
Merged.
