### ISSUE TITLE
New market API uses doubles

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#504]
The new market API implemented as part of #503 uses doubles.  Use of doubles in any financial system is a worst practice, and this situation should be corrected.  If #246 is finally implemented we should isolate the `double`'s into their own API.

An alternative version is to refactor the JSON code to take a `parse_float` function pointer, like Python's JSON parser, and then have the floats parsed as some kind of rational or string class that doesn't lose information.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#144
