### ISSUE TITLE
compile error on windows

### ISSUE THREAD

**Issue by cgafeng** [cryptonomex/graphene#51]
win7x64, vs2013

1>D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(932): error C2664: 'boost::asio::basic_waitable_timerstd::chrono::steady_clock,boost::asio::wait_traits<Clock,boost::asio::waitable_timer_service<Clock,WaitTraits>>::basic_waitable_timer(const boost::asio::basic_waitable_timer<Clock,WaitTraits,boost::asio::waitable_timer_service<Clock,WaitTraits>> &)' : cannot convert argument 2 from 'boost::chrono::milliseconds' to 'const std::chrono::time_pointstd::chrono::system_clock,std::chrono::system_clock::duration &'
1>          with
1>          [
1>              Clock=std::chrono::steady_clock
1>  ,            WaitTraits=boost::asio::wait_traitsstd::chrono::steady_clock
1>          ]
1>          Reason: cannot convert from 'boost::chrono::milliseconds' to 'const std::chrono::time_pointstd::chrono::system_clock,std::chrono::system_clock::duration'
1>          No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(1003) : see reference to function template instantiation 'std::_Ref_count_obj<_Ty>::_Ref_count_objstd::reference_wrapper<boost::asio::io_service,boost::chrono::duration<int_least64_t,boost::milli>>(std::reference_wrapperboost::asio::io_service &&,boost::chrono::duration<int_least64_t,boost::milli> &&)' being compiled
1>          with
1>          [
1>              _Ty=boost::asio::steady_timer
1>          ]
1>          D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory(1003) : see reference to function template instantiation 'std::_Ref_count_obj<_Ty>::_Ref_count_objstd::reference_wrapper<boost::asio::io_service,boost::chrono::duration<int_least64_t,boost::milli>>(std::reference_wrapperboost::asio::io_service &&,boost::chrono::duration<int_least64_t,boost::milli> &&)' being compiled
1>          with
1>          [
1>              _Ty=boost::asio::steady_timer
1>          ]
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/transport/asio/connection.hpp(317) : see reference to function template instantiation 'std::shared_ptrboost::asio::steady_timer std::make_sharedboost::asio::steady_timer,std::reference_wrapper<boost::asio::io_service,boost::chrono::milliseconds>(std::reference_wrapperboost::asio::io_service &&,boost::chrono::milliseconds &&)' being compiled
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/transport/asio/connection.hpp(313) : while compiling class template member function 'websocketpp::transport::asio::connection<config>::timer_ptr websocketpp::transport::asio::connection<config>::set_timer(long,websocketpp::transport::timer_handler)'
1>          with
1>          [
1>              config=fc::http::detail::asio_with_stub_log::transport_config
1>          ]
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/transport/asio/endpoint.hpp(833) : see reference to function template instantiation 'websocketpp::transport::asio::connection<config>::timer_ptr websocketpp::transport::asio::connection<config>::set_timer(long,websocketpp::transport::timer_handler)' being compiled
1>          with
1>          [
1>              config=fc::http::detail::asio_with_stub_log::transport_config
1>          ]
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/transport/asio/endpoint.hpp(77) : see reference to class template instantiation 'websocketpp::transport::asio::connection<config>' being compiled
1>          with
1>          [
1>              config=fc::http::detail::asio_with_stub_log::transport_config
1>          ]
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/endpoint.hpp(42) : see reference to class template instantiation 'websocketpp::transport::asio::endpointfc::http::detail::asio_with_stub_log::transport_config' being compiled
1>          d:\code\graphene\graphene\libraries\fc\vendor\websocketpp\websocketpp/roles/server_endpoint.hpp(44) : see reference to class template instantiation 'websocketpp::endpointwebsocketpp::connection<config,config>' being compiled
1>          with
1>          [
1>              config=fc::http::detail::asio_with_stub_log
1>          ]
1>          d:\code\graphene\graphene\libraries\fc\src\network\http\websocket.cpp(264) : see reference to class template instantiation 'websocketpp::serverfc::http::detail::asio_with_stub_log' being compiled

**Comment by emfrias** [comment]
Try manually applying this fix:
https://github.com/zaphoyd/websocketpp/commit/ba72622303b6c59fae3b2c846ff3a48b58a7c7fa
I'll see if we can get it fixed upstream.

**Comment by cgafeng** [comment]
all right, it's work.

**Comment by emfrias** [comment]
I found a better fix that doesn't require manually modifying websocketpp, you can revert that change next time you update.

**Comment by cgafeng** [comment]
yes, the update work too.
