### ISSUE TITLE
Document the difference between impacted accounts and relevant accounts

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#512]
- Impacted accounts are defined in [impacted.cpp](https://github.com/cryptonomex/graphene/tree/d6878852f07cb88a680e47f4a51d6f667d36ceac/develop/libraries/app/impacted.cpp#L34-L201).
- Relevant accounts are defined in [api.cpp](https://github.com/cryptonomex/graphene/tree/d6878852f07cb88a680e47f4a51d6f667d36ceac/develop/libraries/app/api.cpp#L214-L340).

They seem like similar ideas, why do we have both of them?  What is different about them?  Can we delete one of them?

**Comment by theoreticalbts** [comment]
It seems that impacted accounts are based on the accounts affected by an operation, whereas relevant accounts are accounts related to an object.  Clearly the impacted accounts are used by account history, but how exactly are relevant accounts used?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#165
