### ISSUE TITLE
Missing windows cli-tools for latest release.

### ISSUE THREAD

**Issue by Xeldal** [cryptonomex/graphene#514]

**Comment by abitmore** [comment]
Try this https://github.com/btscube/bitshares-2/releases if you need the windows cli-tools.

**Comment by theoreticalbts** [comment]
We need to clarify internally whose responsibility it is to produce various build artifacts.  Ideally this should all be automated, but it's more manual than we would like, and sometimes stuff might slip through the cracks.

**Comment by theoreticalbts** [comment]
@bytemaster for every binary we upload, let's make a list of who produces it, and a list of what the procedure is to:
- Create and upload BitShares Graphene (backend) release binaries for Windows, Mac, Linux
- Create and upload BitShares standalone GUI executable for Windows, Mac, Linux
- Create and upload web GUI to partners (bitshares.openledger.info, graphene.bitshares.org, others?)

**Comment by Xeldal** [comment]
Will there be a windows cli-tools fullnode download before the next release?  A lot of people may depend on this.

**Comment by abitmore** [comment]
New release without windows binaries again?

**Comment by vsrole** [comment]
btc38.com   has stopped Withdrawals and Deposits. we need new CLI windows version.

**Comment by bytemaster** [comment]
https://github.com/bitshares/bitshares-2/releases includes CLI tools.
