### ISSUE TITLE
Feature:  Special authorities

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#516]
It has been brought to my attention that custom committees as described in #491 are out of scope for now.  Instead, we need the ability to set the authority on an account to be the top `n` holders of an asset.

In order to implement top-n-holders in a way that is fully forward compatible with future extensions (such as if work on custom committees resumes), I propose adding two extensions to `account_options`, which are `owner_special_authority` and `active_special_authority` respectively.  Each extension, if present, indicates a member of a newly defined `static_variant` called `special_authority`:

```
typedef static_variant<
   no_special_authority,
   top_holders_special_authority
   > special_authority;
```

This ticket is a dependency of #452.

**Comment by abitmore** [comment]
> we need the ability to set the authority on an account to be the top n holders of an asset.

If I understand correctly, an asset have to have an issuer/owner? Who will create these accounts if we have tons of FBA in the future?

> In order to implement top-n-holders in a way that is fully forward compatible with future extensions (such as if work on custom committees resumes), I propose adding two extensions to account_options, which are owner_special_authority and active_special_authority respectively. Each extension, if present, indicates a member of a newly defined static_variant called special_authority

I'd like to read more about how to maintain forward compatibility. I'm writing something, maybe need to add some attributes to `extensions` of some objects. Where can I find the docs? Thanks in advance.

**Comment by xeroc** [comment]
> If I understand correctly, an asset have to have an issuer/owner? Who will create these accounts if we have tons of FBA in the future?

FBAs and their maintenance account(s) are created during a hard fork. All FBAs require a hardfork that include those accounts.

> I'd like to read more about how to maintain forward compatibility. I'm writing something, maybe need to add some attributes to extensions of some objects. Where can I find the docs? Thanks in advance.

I fear that there is not much documented about them yet. At least, I wasn't able to find anything yet

**Comment by theoreticalbts** [comment]
Impelemented.
