### ISSUE TITLE
Feature request: Witness alive announcement (transaction)

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#517]
All witnesses started with a signing key periodically sign a packet and broadcast to the network, so that we can always know who is still alive, and/or whether it's on a correct version. This feature is useful specially when some "active" witnesses stopped working and we need to vote in standby witnesses. 

With some algorithm, we can let the "alive" standby witnesses produce blocks automatically when "active" witness is down. This may cause minor forks when the "active" witness back online, but imo it's acceptable or maybe avoidable.

Thoughts? Maybe we need a BSIP discussion for this?

**Comment by abitmore** [comment]
I have an idea, just make the announcement an operation, so it will be packed into blocks. A witness heart beat operation. In maintenance interval, automatically remove the witnesses who have no heart beat recently from the active witness list, even if it has enough votes.

**Comment by pmconrad** [comment]
IMO a persistent heartbeat with automatic witness deactivation only makes things more complicated. At the very least it adds a lot of bloat to an already quickly growing chain. This is simply not necessary, because so far witness stability has not been a problem.

An ephemeral heartbeat (i. e. on the P2P network level without blockchain transactions) would be a good idea, though. That way, standby witnesses could prove that they're active. Otherwise voters have no reliable means to find out if an old witness proposal is outdated or not.

**Comment by abitmore** [comment]
By submitting the request I was not saying we need it right now. Even if we're stable so far, we may need it in the future, maybe sometimes. 

The chain size hasn't been a problem as well, as @pmconrad argued, by now most blocks are empty, if we already have 100 or more transactions in every block, add some heart beat transactions wouldn't impact too much.

On the network level we don't know which packet is sent by whom, without signature there would be forged packets, hence this design may introduce more vulnerabilities to be able to be attacked.

**Comment by abitmore** [comment]
Recently because yunbi started voting with a big stake, caused that some dead standby witnesses were voted in temporarily. We spent a lot of time to figure out who of the standby witnesses are still alive. If we have the feature to detect who is alive automatically, it would be more efficient in this kind of scenarios.

**Comment by pmconrad** [comment]
Signatures are required, even if these heart beats aren't included in the chain.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#147
