### ISSUE TITLE
Compiler is confused selecting pack() template override

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#518]
While implemeintg #516 I encountered a problem with `pack()` overrides.  I'm attaching a minimal program that reproduces it.  The issue reproduces in both gcc and clang.  Basically given two templates:

```
template< typename Stream, typename T >
void pack( Stream& s, const T& v );

template< typename Stream, typename T >
void pack( Stream& s, const E<T>& v );
```

the compiler selects the first in preference to the second, I believe the C++ standard specifies using partial ordering of function templates says the second must be preferred by standards compliant compiler.  I.e. `const E<T>&` is more specialized because `const X&` can be rewritten as `const E<T>&` by substituting `X=E<T>`, but not the reverse, see for example [1].

In the branch I also show a workaround for this case.

[1] https://msdn.microsoft.com/en-us/library/zaycz069.aspx

**Comment by theoreticalbts** [comment]
I hadn't actually pushed this branch.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#148
