### ISSUE TITLE
fc_reflect visit() requires visitor's operator() to be const

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#519]
This is an FC deficiency.  When visiting members of a class, sometimes we want to build up state on all the members as we process it.  It is ideal to store this state in the visitor object, however because of const e.g. [here](https://github.com/cryptonomex/fc/blob/9128edb0d6dcf5ff77802ae495aebd3c33cdf5a6/include/fc/reflect/reflect.hpp#L61) the visitor is not allowed to modify its own fields in operator().

Why does the reflection force visitors to be const?

**Comment by bytemaster** [comment]
It enforces it to avoid ambiguity in calls. Mark the members variables on the visitor as "mutable" and C++ will allow them to be modified by a const method.

**Comment by theoreticalbts** [comment]
I don't like it but I guess I can live with it.
