### ISSUE TITLE
witness_node uses two incompatible parsers for config.ini

### ISSUE THREAD

**Issue by pmconrad** [cryptonomex/graphene#521]
The config.ini file used by the witness_node is parsed twice, with different parsers:
1. By bpo::parse_config_file to get the basic options
2. By boost::property_tree::ini_parser::read_ini for the logging configuration

These two parsers are not entirely compatible, which sometimes leads to the second parse failing. This results in the default logging config being used instead of that in the config file.

Specifically, the ini_parser does not support repeating options. This conflicts with the documented (in the default config file) behaviour wrt the track-account option "Account ID to track history for (may specify multiple times)".

The problem is difficult to diagnose, because the reason for the parse failure is not logged.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#149
