### ISSUE TITLE
Only 1 transfer to alice (expected two):   transfer_to_blind xxx CORE [[alice,1000],[alice,2000]]

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#523]
https://github.com/cryptonomex/graphene/wiki/StealthTransfers#transferring-to-a-stealth-balance

The Docs show that Alice can receive two blinded transfers in one command:

```
>>> transfer_to_blind alicepub BTS [[alice,1000],[alice,2000]] true
alicepub sent 3000 BTS to 2 blinded balances fee: 15 BTS
1000 BTS to  alice
  receipt: 2Dif6AK...

2000 BTS to  alice
  receipt: 28HrgG...
```

However, in `develop` only the 1st one is sent according to the output:

```
transfer_to_blind nathan CORE [[alice,1000],[alice,2000]] true
2044465ms th_a       wallet.cpp:743                save_wallet_file     ] saving wallet to file wallet.json
nathan sent 1000 CORE to 1 blinded balance fee: 10 CORE
1000 CORE to  alice
      receipt: 2SDVv...
```

This command works as expected, sending the balance to two labeled keys:
`transfer_to_blind nathan CORE [[alice,1000],[bob,2000]] true`
#452

**Comment by bytemaster** [comment]
This is probably caused by the API using map<string,string> in the to_amounts which causes the JSON to be parsed and discard the duplicate entry.
