### ISSUE TITLE
cli-wallet distinguishes between `True` and `true`

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#525]
works: `transfer nathan client1 999 CORE "" true`
does not work: `transfer nathan client1 999 CORE "" True` (in the sense that the wallet _broadcasts_ the tx)

**Comment by theoreticalbts** [comment]
OK, a while ago I re-wrote FC's JSON parser.  The new relaxed parser interprets unquoted non-keyword values as strings, so at the JSON level `true` gets converted to boolean `true`, but `True` gets converted to the string `"True"`; you can see that logic implemented [here](https://github.com/cryptonomex/fc/blob/9128edb0d6dcf5ff77802ae495aebd3c33cdf5a6/include/fc/io/json_relaxed.hpp#L656-L685).

Then when JSON is converted to bool, it converts the string `"true"` to the bool `true` and all other strings to the bool `false`; that's part of `fc::variant` implemented [here](https://github.com/cryptonomex/fc/blob/9128edb0d6dcf5ff77802ae495aebd3c33cdf5a6/src/variant.cpp#L433-L434).

I think in the second place, the `string_type` case of the `switch` statement needs to reject any value other than `"true"` or `"false"`.

**Comment by theoreticalbts** [comment]
Recompile with the above commit, `True` -- or any value other than `true` or `false` -- should now throw an exception.
