### ISSUE TITLE
cli_wallet caching issues

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#530]
The cache design of `cli_wallet` is fundamentally broken, leading to numerous issues:   #323 #331 #353 #527

Anything which updates the account object causes a tendency for the cache to get out of sync.  Really the CLI wallet should use the same architecture as the web wallet:  Subscribe to object updates in order to implement a caching proxy for all object requests from individual wallet functions.  As a stop-gap we could simply remove the existing cache, implement a new cache and require it to hit the `witness_node` anytime it needs an account (assuming most `cli_wallet` users also run `witness_node` on localhost or a fast LAN).

As this requires a substantial re-working of the wallet, perhaps this should be a worker proposal.

**Comment by neura-sx** [comment]
Maybe a simple `resync()` command  would be a good temporary fix?
This command would force the CLI's cache to be reset. 
Not perfect but it still better than having to start over the whole process.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#151
