### ISSUE TITLE
Can't reproduce the chain-id from the testnet

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#532]
Hello there,

this is what I did:
    programs/witness_node/witness_node --create-genesis-json genesis.json

```
# edit genesis.json

programs/witness_node/witness_node --genesis-timestamp 10 --genesis-json genesis.json --data-dir data/testnet2/ --p2p-endpoint 0.0.0.0:8070
# will not produce blocks because now witness is setup, but will
# generate a chain id
# write down the new timestamp and the chain id

# paste the new timestamp into the genesis.json

make clean
rm -f CMakeCache.txt
find . -name CMakeFiles | xargs rm -Rf

cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=~/opt/boost_1_57_0/ -DGRAPHENE_EGENESIS_JSON="$(pwd)/genesis.json" .
make

programs/witness_node/witness_node --data-dir data/connect-only-node
```

So I assume that the updates genesis file would now produce the same
chain id but it does NOT.

What am I missing or doing wrong?

The reason I am asking is because people can't connect their witness
nodes to the public testnet and I need to reset it (since I haven't
noted the timestamp). During tests however, I couldn't regenerate the
same chain-id :(

**Comment by jcalfee** [comment]
The chain-id is basically a hash of the entire `genesis.json` file.  If you want the same chain-id you have to have the same `genesis.json` file.  To reset a chain you just need to blow away the database files.  Try renaming `witness_node_data_dir`.

**Comment by xeroc** [comment]
> The chain-id is basically a hash of the entire genesis.json file. If you want the same chain-id you have to have the same genesis.json file. To reset a chain you just need to blow away the database files. Try renaming witness_node_data_dir.

Sure. I deleted all data (including blockchain)

**Comment by jcalfee** [comment]
xeroc [11:18 AM] 
I'll pick a fixed initial_timestamp not use `--genesis-timestamp` ... and see what happens

jcalfee [11:18 AM] 
I believe it is just a warning about the timestamp.. just ignore it.

xeroc [11:19 AM] 
Thanks .. I'll give it a try as soon as i find the time

**Comment by xeroc** [comment]
Stupid end user error ..
