### ISSUE TITLE
Error when retrieving Network Node API identifier

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene#534]
When I attempt to retrieve Network Broadcast API identifier using wscat:

```
> {"id":888,"method":"call","params":[1,"network_broadcast",[]]}
```

it works fine.

But when I attempt to retrieve Network Node API identifier :

```
> {"id":888,"method":"call","params":[1,"network_node",[]]}
```

I get this error:

```
< {"id":888,"error":{"code":1,"message":"10 assert_exception: Assert Exception\n_network_node_api: \n    {}\n    th_a  api.cpp:184 graphene::app::login_api::network_node","data":{"cod
e":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":184,"method":"graphene::app::login_api::network_node","hostna
me":"","thread_name":"th_a","timestamp":"2016-01-22T18:59:57"},"format":"_network_node_api: ","data":{}}]}}}
```

**Comment by abitmore** [comment]
It seems that you need to explicitly enable network_node_api when starting witness_node.
Add this line to config.ini

```
api-access = "/path/to/api-access.json"
```

and put something similar to these into api-access.json

```
{
   "permission_map" :
   [
      [
         "*",
         {
            "password_hash_b64" : "*",
            "password_salt_b64" : "*",
            "allowed_apis" : ["database_api", "network_broadcast_api", "history_api", "network_node_api"]
         }
      ]
   ]
}

```

**Comment by abitmore** [comment]
See http://docs.bitshares.org/api/access.html

**Comment by xeroc** [comment]
@neura-sx how could I forget about it .. 
you definitely need your own api-access for this since no one unauthorized should be able to see your connected peers for security reasons (could be used to located your machine, or even worses, locate a witness the node was supposed to hide as proxy)
