### ISSUE TITLE
Offer a way to import a `wallet.dat` file from PTS

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#535]
Some major BTS and MUSE holders have contacted me and are facing different issues importing rather huge wallets. Most stake has been sharedropped onto BTC/PTS keys and thus it would be extremely helpful if we could have a way to import `wallet.dat` files into the cli_wallet (at least).

Since the code exists in BTS1, I assume it shouldn't be too complicated to merge it over to the graphene cli-wallet.

Clarification: I am not asking to import wallet.dat files into the GUI, but the CLI-wallet

**Comment by theoreticalbts** [comment]
Slightly related: #557

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#152
