### ISSUE TITLE
Question: Deriving public key child

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#536]
In implementing stealth transfers in JavaScript, I ran into `tweak_add` api call used to derive a key.  I have not been able to locate any code or documentation.  I'll make this ticket incase someone can direct me to this.

https://github.com/cryptonomex/secp256k1-zkp/blob/bd067945ead3b514fba884abd0de95fc4b5db9ae/src/secp256k1.c#L354-L377  
`secp256k1_ec_pubkey_tweak_add`

This is the code that calls this API.  Also, this could be a work-around (add the call to the crypto api):

``` c++
fc::ecc::public_key crypto_api::child(fc::ecc::public_key public_key, fc::sha256 child)
{
  return public_key_type( public_key.child( child ) )
}
```

**Comment by pmconrad** [comment]
https://github.com/cryptonomex/secp256k1-zkp/blob/bd067945ead3b514fba884abd0de95fc4b5db9ae/src/eckey_impl.h#L165

IIRC the pubkey P is tweaked with scalar b by computing P' = P + b*G (where G is the generator).

**Comment by jcalfee** [comment]
Thank You!

**Comment by theoreticalbts** [comment]
Why did you revert this commit?  Has the function been implemented in GUI making the API call unnecessary?

**Comment by jcalfee** [comment]
In other implementations, usually see modulus applied using the N point of the secp256k1 curve `pIL.add(this.keyPair.d).mod(curve.n)`:
https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/hdnode.js#L245-L246

I get the same result without the mod, but this will not always be the case.

This is where the tweak add is called but there is no modulus: 
https://github.com/cryptonomex/secp256k1-zkp/blob/bd067945ead3b514fba884abd0de95fc4b5db9ae/src/secp256k1.c#L365-L375

https://github.com/cryptonomex/secp256k1-zkp/blob/a9b6595ef812e8e52b0cb56d22109de5636b82aa/src/eckey_impl.h#L170

It looks like `secp256k1_ecmult` is used only for adding (not modulus):

``` cpp
/** Double multiply: R = na*A + ng*G */
static void secp256k1_ecmult(const secp256k1_ecmult_context_t *ctx, secp256k1_gej_t *r, const secp256k1_gej_t *a, const secp256k1_scalar_t *na, const secp256k1_scalar_t *ng);
```

**Comment by pmconrad** [comment]
You're comparing the tweaking of a privkey in javascript (with modulus) with the tweaking of a pubkey in secp256k1.
If you look at
https://github.com/cryptonomex/secp256k1-zkp/blob/bd067945ead3b514fba884abd0de95fc4b5db9ae/src/secp256k1.c#L331
instead you will find that it uses for example
https://github.com/cryptonomex/secp256k1-zkp/blob/bd067945ead3b514fba884abd0de95fc4b5db9ae/src/scalar_4x64_impl.h#L83
which reduces the result if it overflows.

**Comment by theoreticalbts** [comment]
What still needs done on this ticket?

**Comment by jcalfee** [comment]
Nothing ..
