### ISSUE TITLE
Buyback accounts

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#538]
Buyback -- as returns to holders of an asset (see #452 and #524) -- will be implemented by creating a standard account with an extension and null authority.

The account will then act autonomously by reserving all of the asset it receives, and using all other assets to place a market order each maintenance interval to attempt to clear out the market.  It will then cancel its order.

There are several desirable features to using an account in this role, as opposed to a new object:
- Leverages already-existing maker-taker logic for walking the book.
- Leverages already-existing account history UI to allow people to monitor the buyback program's actions.
- Gives a meaningful `account_id` for market orders.
- Bounded resources:  The only network resources needed are the equivalent of one market order per asset per maintenance interval.  An ordinary asset creation fee should be sufficient to cover this cost.  Fee circumvention is not much of an issue as the other side of each trade will still pay fees.
- Buyback objects cannot interact, so even if assets A and B both have buyback, only one buyback order will be active at a time, so the orders can't match against each other.

**Comment by xeroc** [comment]
Am I assuming right that
- everyone will be able to create such an account
- everyone will be able to use such an account
- the account has a set of predefined markets to sell its assets on?

**Comment by theoreticalbts** [comment]
You're right, it will need to have a set of predefined markets of bounded size -- maybe 4?  We just need to make it a parameter.

**Comment by abitmore** [comment]
Why not the FBA:BTS market only? You got all fees in BTS. The FBA owners own only FBA. What are other markets?

**Comment by theoreticalbts** [comment]
@abitmore : I designed this to be a general primitive which may be used for more than just FBA.

**Comment by theoreticalbts** [comment]
Force-pushed new version based #566 which also doesn't suffer from #575

**Comment by theoreticalbts** [comment]
Implemented, merged.
