### ISSUE TITLE
Can wallet providers pay all transaction fees on behalf of the user?

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#54]
I don't know if this is a use case we want to support, but if so--I want to confirm that our operations support this.

**Comment by nathanielhourt** [comment]
Not seamlessly. If a wallet provider wanted to do this, they would probably want to just refund the user in bulk for fees. The alternative would be to transfer the fee to the user every time they make a transaction, but that would cost double fees. It also requires getting signatures from the user and provider both, which is cumbersome.

**Comment by bytemaster** [comment]
This is an interesting use case. Paying double the fees for double the signatures seems to make sense.  It really wouldn't be a problem if the protocol properly supported "micro payments" by charging transfer fees as a percentage with a min/max fee.

**Comment by vikramrajkumar** [comment]
I am thinking of competitors like Coinbase which eat all transactions fees (for transfers) and the user never has to see them.

**Comment by bytemaster** [comment]
I think the answer is "no protocol support for this".
