### ISSUE TITLE
The committee-account as a default proxy - it does not make sense.

### ISSUE THREAD

**Issue by neura-sx** [cryptonomex/graphene#543]
What is the reason all newly created accounts on [the testnet](http://testnet.bitshares.eu) have `committee-account` as their proxy? Is it a bug or a feature?
IMO it does not make any sense and it only introduces unnecessary confusion for new users about the voting process.

![03](https://cloud.githubusercontent.com/assets/11573977/12675058/f4ba3eb4-c687-11e5-92c9-8873519abe80.png)

**Comment by theoreticalbts** [comment]
How are you creating these accounts?

**Comment by abitmore** [comment]
I think it's a GUI issue. The default `voting_account` in witness_node is `proxy_to_self`, and `register_account` command in cli_wallet behaviors accordingly.

**Comment by xeroc** [comment]
accounts have been created through the faucet using `register_account` of the cli-wallet

**Comment by abitmore** [comment]
Imo no related to faucet. I recently registered an account in GUI (light wallet), paid by another account of mine, not the faucet. See block 3037290 https://cryptofresh.com/b/3037290. Here is part of the transaction

```
...
            "options": {
              "memo_key": "BTS7QC3vSne149XtLGnw6KicvU63ztk2Z7eWbdadMQE54N5FLzR6x",
              "voting_account": "1.2.0",
              "num_witness": 0,
              "num_committee": 0,
              "votes": [],
              "extensions": []
            },
...
```

Obviously the `voting_account` in the transaction is incorrectly set to `1.2.0` aka `committee-account`.

Will cross-submit this issue to graphene-ui.

**Comment by theoreticalbts** [comment]
Closing this and moving discussion to the above-linked `graphene-ui` issue.
