### ISSUE TITLE
Stealth blind_transfer_operation::validate is re-calculated fee (ignoring the signed fee amount)

### ISSUE THREAD

**Issue by jcalfee** [cryptonomex/graphene#548]
Here blind_transfer_operation::validate seems to ignore the "fee" in the transaction and rather updates the fee again (perhaps by re-calculating it).  The reason I think this:  I was seeing the assert below fail with a net_public (where  net_public = fee.amount.value) value that was unchanged even though I sent transactions with different fee amounts.

`FC_ASSERT( fc::ecc::verify_sum( in, out, net_public ), "", ("net_public", net_public) )`

That may never show up, however, here appears that the fee is calculated based on 2 output operations but later function, the operation array may be resided to 1 change output (if there is no change):

https://github.com/cryptonomex/graphene/blob/a2ce86bf4ff10bbb8dce524cccdf269214301516/libraries/wallet/wallet.cpp#L3725-L3737

It is just a little confusing so a comment should help..

**Comment by bytemaster** [comment]
The code referenced is OK, but the blind_transfer::validate method needed to check the fee here: eddc85f3152274664616d526c70906ac63ee0bca
