### ISSUE TITLE
Defer something-for-nothing culling for taker orders until the order is unmatched

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#555]
The code [here](https://github.com/cryptonomex/graphene/blob/develop/libraries/chain/db_market.cpp#L300-L310) culls orders which would allow a counterparty to get something for nothing due to rounding.  However, if the order being culled is a taker order, this culling should be deferred until the taker order doesn't match (and any unfilled remnant would become a maker order).

Put another way, the culling is currently being applied to taker orders, and it really only makes sense to apply it for maker orders.

As the order issued by the buyback code under development for #538 is a taker order with a very small price, correctly handling this case is a prerequisite for that feature.

**Comment by abitmore** [comment]
I wonder if `cancel_order` will cause a fee to the owner with that code.

**Comment by theoreticalbts** [comment]
The `deferred_fee` is taken off the order, and any market fee is charged, but it shouldn't charge the cancellation fee as other cancel ops, as this code uses `push_applied_operation`.  The idea being that the order being almost-totally filled is (economically) the same as the order being totally filled, and it doesn't need to be charged a cancellation fee.

**Comment by theoreticalbts** [comment]
Implemented, merged.
