### ISSUE TITLE
cli_wallet: import_balance does not work with balances sharedropped on PTS (or BTC) addresses

### ISSUE THREAD

**Issue by pmconrad** [cryptonomex/graphene#557]
More detailed problem description: https://bitsharestalk.org/index.php/topic,21249.msg277488.html#msg277488

Fix is simple, I'll create a PR

**Comment by xeroc** [comment]
I think this is the one issue that some exchanges are currently facing when trying to import their MUSE into the cli-wallet from BTC addresses.

**Comment by theoreticalbts** [comment]
Merged.
