### ISSUE TITLE
Ensure arcane C++11 feature is used correctly in fork_database.cpp

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#56]
This looks like a problem:

```
shared_ptr<fork_item>  fork_database::push_block( signed_block b )
{
   auto item = std::make_shared<fork_item>( std::move(b) );
   //wdump((item->num)(_head?_head->num:0));

   if( _head && b.previous != block_id_type() )
```

In particular, I was under the impression `std::move` makes things invalid / undefined -- but we're accessing `b` after using it.  I'd be in favor of making the parameter a const reference and doing a normal copy.  But I first want to read the specs and be sure I understand the exact semantics of what's happening here, and maybe consult with other C++ experts on the team.

**Comment by theoreticalbts** [comment]
There's a magic number `1024` in this function as well -- I officially have no idea WTF this code is doing.

**Comment by nathanielhourt** [comment]
Good catch; that is an invalid use of b. It's referencing a primitive, so it might be safe in practice, but it's undefined behavior and must not be left as is.
