### ISSUE TITLE
Light Wallet 2.0.160106 does not play well with boost-1.60.0-1-x86_64

### ISSUE THREAD

**Issue by ghost** [cryptonomex/graphene#560]
See https://github.com/cryptonomex/graphene-ui/issues/675

This does not effect the cli_wallet or witness_node.

**Comment by theoreticalbts** [comment]
The wallet in `programs/light_client` is not supported / maintained and is going to be removed in the next BitShares release.  See #457

The recommended way to run a BitShares GUI without trusting any remote server is to build `graphene-ui` with Electron:

```
cd web
npm run build
cd ../electron
npm run release
```

These commands should be documented more obviously.

If you'd like to help us with Boost 1.60 testing, try running `make chain_test` followed by `tests/tests/chain_test` -- if that gives you crashes or test failures, feel free to open a new ticket.
