### ISSUE TITLE
Move virtual ops to plugins

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#571]
It seems like it would be useful to have plugins able to create v-ops, and re-work existing core v-ops into plugins.  Then if we upgrade v-ops in any way, clients can use their configuration to choose what v-ops are generated and whether they break operation history.  This approach loses consistent numbering of op history and gives everybody different v-op set based on their configuration -- but that is OK.  V-ops and operation history are inherently things which are used by particular UI implementations and are not core features.  Related:  #246 #570

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#157
