### ISSUE TITLE
Settle orders have no id

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#575]
The settle order objects pushed over the websocket connection have no id, not sure if it's on purpose or not but it would be nice if they had one...Might be a case of a missing reflection only?

![image](https://cloud.githubusercontent.com/assets/6890015/13027710/52c7c6ce-d25a-11e5-9ca9-a94179227800.png)

**Comment by abitmore** [comment]
Unfortunately it's the case.. I'll push a patch soon.

**Comment by xeroc** [comment]
@abitmore 
could you please send pull requests to the graphene codebase instead of bitshares-2?

**Comment by abitmore** [comment]
pull request submitted #576

**Comment by theoreticalbts** [comment]
Please also be a little more verbose in your commit messages.  Including the issue number is good but even better if you include a one-sentence description of the problem (often the issue title).  I'll fix it, I have to cherry-pick this anyway (it seems you're off on your own branch with a bunch of unrelated debugging stuff that should probably remain on your fork).

The buyback objects I implemented for #538 suffer from this problem as well.  I'll add testing for this oversight to the Python reflection audit script I wrote (see #562 for more about the script).

**Comment by theoreticalbts** [comment]
This may also be related to #485 as well.  Good catch!

**Comment by theoreticalbts** [comment]
Fixed, merged.

**Comment by abitmore** [comment]
> Please also be a little more verbose in your commit messages. Including the issue number is good but even better if you include a one-sentence description of the problem (often the issue title). I'll fix it, I have to cherry-pick this anyway (it seems you're off on your own branch with a bunch of unrelated debugging stuff that should probably remain on your fork).

@theoreticalbts The very short commit description you referred to is on a temporary testing branch of mine, since you moved some code to a new file (which is good but I don't want to merge them right now) so the commit with better description can't be simply cherry-picked/merged to my working branch. Anyway I'll write more in the future even if it's temporary.
