### ISSUE TITLE
get_account_history may terminate early due to using first op as sentinel value

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#578]
Calling `get_account_history` on the account which owns `get_object 1.11.0` may cause the iteration to stop early because of a confusion between two cases:
- Case 1:  There is no next `operation_history_object`, we have reached the end of the list
- Case 2:  The next `operation_history_object` exists and has ID zero

The simple fix for new chains is to create a dummy sentinel `operation_history_object` with ID zero.  However, this fix will not work on already-deployed chains because it will change history ID's.

A deployable fix would append `1.11.0` to its result when:
- The account for which the operation history is being requested is the account for `1.11.0`
- Appending it would not exceed the request limits

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#168
