### ISSUE TITLE
Asset can be registered with null core exchange rate, but not updated

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#579]
We have to sure all paths handle null core exchange rate properly, because even if we require non-null core exchange rate for new assets, on already-deployed chains we still have to deal with existing assets that were created with the null rate.

**Comment by abitmore** [comment]
I think CER is validated [here](https://github.com/cryptonomex/graphene/blob/2.0.160103b/libraries/chain/protocol/asset_ops.cpp#L97) and [here](https://github.com/cryptonomex/graphene/blob/2.0.160103b/libraries/chain/protocol/asset_ops.cpp#L213), unless `asset_create_operation::validate()` had never been called.

//Update: the description in OP is correct, existing assets with null rates are come from BitShares 0.x. However the title of this ticket is ambiguous, I thought it means currently new asset can be created with a null rate.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#169
