### ISSUE TITLE
Recover more cleanly from checkpoint failure

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#588]
In order to inspect a particular block, It is common practice among Graphene developers to set a bogus checkpoint:

```
checkpoint = [1812207, "ffffffffffffffffffffffffffffffffffffffff"]
```

The client should gracefully handle checkpoint mismatch with both blocks from disk and network-supplied blocks.  In particular a re-index shouldn't be forced if the `witness_node` is restarted with the checkpoint deleted.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#176
