### ISSUE TITLE
Add virtual operations to blocks

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#590]
It is confusing that v-ops exist in the account history, but not in blocks as returned by the API.  The `get_block()` API call should include any virtual ops created in that block.

Related: #589

**Comment by bytemaster** [comment]
No it shouldn't.  This is a terribly low priority item.

Users can iterate through all virtual operations independently of fetching blocks. Blocks are an artifact of batch processing and should not be used by API users.

**Comment by abitmore** [comment]
> Blocks are ... and should not be used by API users.

I wonder why provide a `get_block` API if it's useless? 

Iteration is inefficient.

IMHO the feature described in OP is useful, if it's not urgent, remove the `Next Release` label from the ticket. Don't close the ticket.
