### ISSUE TITLE
cli_wallet crashes when connection to witness node is lost

### ISSUE THREAD

**Issue by valzav** [cryptonomex/graphene#591]
It's a big issue for the faucet - when the main witness node (out of 4) crashes it makes cli_wallet to crash and this stops faucet from registering new accounts.
It would be nice if cli_wallet could try to reconnect to several witness_node ws sockets in round robin manner.
It can read a list of available witness_node from command line arguments.

**Comment by ByronAP** [comment]
on windows the cli wallet doesn't crash but rpc requests fail with invalid state and the wallet needs to be restarted to reconnect. This has been an issue for some time and should be priority. I agree with the round robin idea.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#177
