### ISSUE TITLE
get_ticker bid and ask not corrected for precision and not correct

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#592]
Playing around with the new API calls I noticed the highest_bid and lowest_ask have two bugs:
1. They're not correctly corrected for precision, unlike the latest price field.
2. They're not up to date. You can see in the screenshot that the current lowest ask and highest bid are quite different from what get_ticker returns.

![image](https://cloud.githubusercontent.com/assets/6890015/13152239/6ffb6bc0-d66e-11e5-8b97-477ea99b023f.png)

Everything else seems to be ok.

**Comment by svk31** [comment]
Another example: 
![image](https://cloud.githubusercontent.com/assets/6890015/13152451/918323ea-d66f-11e5-9314-76a10901bc06.png)

In this one most things are wrong, actual volume was 14 EUR and 3960 BTS. There's definitely some issues with precision, and probably something to do with inversion of markets as well.

**Comment by svk31** [comment]
![image](https://cloud.githubusercontent.com/assets/6890015/13153411/4fccbbaa-d674-11e5-9f34-821fe700c4e5.png)
![image](https://cloud.githubusercontent.com/assets/6890015/13153417/61cb038e-d674-11e5-88dc-aa5bea1169ea.png)

Some more observations: 

Volumes don't get switched when the market is inverted, but the precisions get do get inverted.
Latest price does not get inverted at all, only the precision changes.

**Comment by svk31** [comment]
We're almost there, everything seems to be correct now except for the 24 hr change which is inversed. The below screens were taken at 18.45 on the 24th. The latest price was 35.9361, the last closing price at 18.45 on the 23rd was 39.5. get_ticker is returning a 24hr change of +9.92%.

The correct change should be (35.9361 - 39.5) / 39.5 = -9.02%

![image](https://cloud.githubusercontent.com/assets/6890015/13294917/8b202f3c-db26-11e5-83c5-bf7f468e6e07.png)

![image](https://cloud.githubusercontent.com/assets/6890015/13294934/9a8a7ab8-db26-11e5-82f4-7c2d61303555.png)

**Comment by mvandeberg** [comment]
The 24 hr change displayed on the web is not using the get_ticker call. From the same market, get_ticker returned the correct 24hr change.

![ticker](https://cloud.githubusercontent.com/assets/15834128/13300732/87c332e2-db0f-11e5-88e7-acebfae14494.png)

**Comment by mvandeberg** [comment]
Patch has already been merged into Bitshares,

**Comment by mvandeberg** [comment]
@theoreticalbts This branch is ready for review to be merged.

**Comment by abitmore** [comment]
Just a note, the branch https://github.com/cryptonomex/graphene/compare/592-get_ticker contains new commits which will fix a witness crash issue, and need to be reviewed and merged (if haven't done already).

**Comment by svk31** [comment]
@abitmore @mvandeberg was that fix from 592-get_ticker ever merged into master?

**Comment by abitmore** [comment]
It's merged into develop branch: https://github.com/cryptonomex/graphene/commit/2fb3cb107840efe75235d69c07b942970b048b28, but not yet merged into bitshares branch, see https://github.com/bitshares/bitshares-2/compare/bitshares...cryptonomex:develop

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#178
