### ISSUE TITLE
Premature deletion of object in FC promise library causes SIGSEGV

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#597]
In code [here](https://github.com/cryptonomex/fc/blob/232d59525af8d2e3b56e8b18b2fdb7f58435a7f5/src/thread/future.cpp#L66-L79) we create a `ptr` (according to `typedef` [here](https://github.com/cryptonomex/fc/blob/232d59525af8d2e3b56e8b18b2fdb7f58435a7f5/include/fc/thread/future.hpp#L63) it is actually `fc::shared_ptr`) which takes ownership of `this` (which inherits from `fc::retainable`).  When this `shared_ptr` goes out of scope, the `retainable`'s reference count reaches zero and it's deleted [here](https://github.com/cryptonomex/fc/blob/232d59525af8d2e3b56e8b18b2fdb7f58435a7f5/src/shared_ptr.cpp#L23), however instance variables are still read in the [original function](https://github.com/cryptonomex/fc/blob/232d59525af8d2e3b56e8b18b2fdb7f58435a7f5/src/thread/future.cpp#L66-L79).

In particular the `_dequeue_thread` implementation uses multiple instance variables, and the `_exceptp` check also accesses an instance variable.  This bug was found when the implementation of #596 led to a situation in the networking code which caused the `_exceptp` check to `SIGSEGV` due to the internal `my` pointer of `_exceptp` being nulled when it was destroyed.

**Comment by theoreticalbts** [comment]
The obvious fix [1] is to lift the instantiation of the `fc::shared_ptr` to the function scope.

However this obvious fix does not work; the original crash trigger still causes a crash.  The reason is that the `future` class retains its _own_ variable `m_prom`, so the sequence of events is:
- `future` class creates an `fc::shared_ptr` from a raw pointer and stores it in `m_prom` member variable
- `promise_base::_wait_until()` creates its own `fc::shared_ptr` from a raw `this` pointer
- Destruction of pointer created in `_wait_until()` results in deletion of `this`
- The `future` class expects the object which was deleted in the previous step to not have been deleted, as it holds a `shared_ptr` to it in `m_prom`

The proper fix is to use `shared_from_this()` in `_wait_until()`, however unfortunately `fc::shared_ptr` does not provide `shared_from_this()` functionality, and `std::shared_ptr` may have slightly different API than `fc::shared_ptr`.

[1] There is a slight difficulty:  The `wait_until()` API of `thread` requires us to `std::move()` the pointer, but this difficulty can easily be circumvented by simply cloning the pointer.

**Comment by theoreticalbts** [comment]
Simply replacing `fc::shared_ptr` with `std::shared_ptr` is not going to be an easy fix. Not only is there a ton of FC internals that need to be updated, but in addition the API is different, according to [this page](http://en.cppreference.com/w/cpp/memory/enable_shared_from_this/shared_from_this) it is undefined behavior to use `shared_from_this()` with objects not chaperoned by a `shared_ptr`, and many places in Graphene (especially the network code) there are `fc::future<T>` which are not wrapped in a `shared_ptr`.

**Comment by theoreticalbts** [comment]
Hmm, the reference count for `fc::shared_ptr` is attached to the object itself by forcing it to inherit from `retainable`.  I'm thinking that means `shared_from_this()` be unnecessary, as all `fc::shared_ptr` are using the same reference count.

**Comment by theoreticalbts** [comment]
And I figured it out.  The obvious fix in my second comment actually works, it actually was just an unrelated later crash.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#181
