### ISSUE TITLE
In p2p code, iterator is not robust to concurrent modification in _handle_message_calls_in_progress loop

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#598]
The problem is [here](https://github.com/cryptonomex/graphene/blob/a3e609d331e196679ba48a0a346eb5c25eda3b4f/libraries/net/node.cpp#L3951-L3973).  The code walks an `std::list` using an iterator, but the `cancel_and_wait()` call allows other FC tasks to run, some of which modify the `list` and invalidate the iterator.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#182
