### ISSUE TITLE
Market order history API call

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#6]
> We're not going to do this for a while. For now you can subscribe to the market in the wallet and build it up there.

**Comment by vikramrajkumar** [comment]
Looks like wontfix.

**Comment by svk31** [comment]
Can we reopen this anytime soon? This is essential to the exchange interface, only having access to orders that were executed after opening the exchange won't be acceptable to the users.

**Comment by nathanielhourt** [comment]
What's the difference between this and the market history plugin?

**Comment by svk31** [comment]
The market history plugin, at least the results I've seen the one time it actually worked, only gives general price information in time "buckets", eg. for a given period of 60s the open was 1.5, close was 1.3, high was 1.6 and low was 1.2.

What I'm asking for here is a list of orders that were filled over a given time period for a given market, with their exact timestamps. 

In BTS 1.0 we have blockchain_market_price_history (equivalent to what's already in BTS 2.0 with get_market_history) and also blockchain_market_order_history, which is currently missing.

**Comment by nathanielhourt** [comment]
OK, thanks for the clarification. So this is another feature that needs to be implemented in the market history plugin, but it's distinct from what's already there.

**Comment by theoreticalbts** [comment]
This has been implemented.
