### ISSUE TITLE
Default active authority of committee-account is empty after HARDFORK_533_TIME

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#600]
If a (new) chain is started after `HARDFORK_533_TIME`, the default active authority of committee-account is empty, but not set to init0~init10. Related code is [here](https://github.com/cryptonomex/graphene/blob/2.0.160223/libraries/chain/db_maint.cpp#L299-L305) and [here](https://github.com/cryptonomex/graphene/blob/2.0.160223/libraries/chain/include/graphene/chain/vote_count.hpp#L39-L40). 
According to the logic in the code, only the members with votes > 0 will be added to the authority. So if nobody is voting, no one will be added to active authority of committee-account; if less than 11 committee members are being voted for, there will be less than 11 members in active authority of committee-account.

**Comment by abitmore** [comment]
Related to #533.

**Comment by theoreticalbts** [comment]
This should probably be fixed before we start any new chain.

**Comment by abitmore** [comment]
It annoys while testing committee related operations -- with a new chain, committee proposals always get removed without executing. It took me some time to figure out the reason. Hopefully it may save other developers some time if run into same situation.

**Comment by abitmore** [comment]
The `witness-account` is affected by similar issue as well. Unable to publish price feeds with init witnesses while testing.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#183
