### ISSUE TITLE
Node fixes for debug mode

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#604]
Debug mode #596 has revealed many race conditions in `node.cpp` close() function.

This ticket is to keep track of the fixes for those issues

**Comment by theoreticalbts** [comment]
Branch is [here](https://github.com/cryptonomex/graphene/tree/604-bugfix-p2p-close).

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#187
