### ISSUE TITLE
Disable negative voting on workers

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#607]
Need to not only disable new negative votes, but go through and delete existing negative votes at the time of the hardfork.

New workers should still be assigned + and - vote ID's to keep wallet breakage to a minimum.

**Comment by bytemaster** [comment]
Rationale is that negative voting requires voters to pro-actively fight against attackers every time they create a new proposal. The attacker, with coordinated stake can out maneuver the defender with uncoordinated stake.  

Fundamentally, expressing what you support and "defaulting" to being against everything new is better than having to actively vote against everything new. This in turn raises the barrier to entry for an attacker with coordinated stake.

**Comment by abitmore** [comment]
Can we just ignore the negative votes when calculating in maintenance interval?

**Comment by bitcrab** [comment]
this sounds not bad, what I want to know is, will this go through a worker proposal for implementation?

**Comment by bitcrab** [comment]
Will this go through a worker proposal for implementation?

**Comment by abitmore** [comment]
@bitcrab Imo the workload for this feature is relatively small, so the cost could probably be covered by this worker: "Blockchain maintenance developer (1.14.30)". Do you mean we need to go through some voting procedure according to the "hard fork principle" (by the way, where is the document)?

**Comment by bitcrab** [comment]
@abitmore yes, what I care is not the cost, but whether there is a voting process for this, this is not a small change, IMO voting is a must.

maybe the BSIP process is suitable? https://github.com/bitshares/bsips

**Comment by abitmore** [comment]
@bitcrab imo it's more or less a security fix, so better not to advertise the hole before fixed.

**Comment by bitcrab** [comment]
@abitmore why security fix? do you assume that all the users that vote against a worker proposal are attackers?

**Comment by abitmore** [comment]
@bitcrab please check https://github.com/cryptonomex/graphene/issues/565 for more information.

**Comment by bitcrab** [comment]
@abitmore got it, however I think a good explanation to the community is necessary to avoid misunderstanding.

**Comment by xeroc** [comment]
https://github.com/bitshares/bsips/blob/master/bsip-0015.md

**Comment by abitmore** [comment]
@xeroc 0013 was assigned to another BSIP already. See https://github.com/bitshares/bsips/issues
