### ISSUE TITLE
New OP for issuer to reclaim fee pool funds

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#608]
Two points about the fee pool:
- The fee pool of an asset can be drained by anyone that has a share in that asset by creating an order paying the fee in that asset and cancelling the order again. He gets refunded 90% in BTS not the asset.
- When creating a new asset, the fee pool is prefunded by 50% of the fee. This fee is deducted from the basic member fee. Recently @Rune has bought a 3-letter symbol (MKR) and payed quite a bit for it with the expectation of a 80% refund after 90 days! He won't get 80% after 90 days but only 40% because the fee pool funds have been deduced from the total amount! He could now drain the fee pool him self (which is cumbersome and time consuming) or we offer a way to collect all of them instantly.

This should really exist as there is no real reason (AFAIK) that should prevent the issuer of an asset to also full control funds in the fee pool.

I propose a new `claim_pool_balance_operation` that takes 
- the asset, 
- the amounts of BTS to claim, and
- the account to credit

as arguments.

~I consider this high priority to get this included in the next hard fork (if by any means possible)~

**Comment by abitmore** [comment]
Assume the core exchange rate of the asset is 1 asset = 1 CORE, assume there is X CORE in fee pool, the issuer can claim funds from fee pool easily with following steps as a work around, no matter how much CORE is in the fee pool:
1. issue X assets to herself
2. craft an `limit_order_create_operation` which will never be filled, set the fee field to X assets, sign & broadcast it
3. cancel the order

I believe @xeroc can make a python script to batch these operations, no need to write C++ code.

**Comment by xeroc** [comment]
@abitmore 
The approach you describe is exactly what I meant by "pool draining" in the OP.
I see it as a hacky solution that cannot be used if you have your asset traded already.

**Comment by abitmore** [comment]
@xeroc what did you mean "have your asset traded already"? IMO the issuer can withdraw from fee pool with that approach at any time, anyone else can do that as well if have enough issued assets.

**Comment by abitmore** [comment]
The approach I provided is just not too "cumbersome and time consuming" as you said in OP.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#188
