### ISSUE TITLE
getting delegate_id and witness_id from account object

### ISSUE THREAD

**Issue by svk31** [cryptonomex/graphene#61]
Would it be possible to include these two ids as optional fields in the account object? As of right now I don't see any way to directly fetch a witness or delegate object (1.6.x, 1.7.x) if all I have is the account name, which is bound to happen in the explorer part of the wallet. I could of course start fetching 1.6.1, 1.6.2, 1.6.3 etc until I find the right one, but that's no good at scale.

Maybe the num_witness and num_committee fields in the options field are meant to give this information? But right now they're reading 0 always for me..

**Comment by nathanielhourt** [comment]
@svk31 Is there anything else needed, or is this issue resolved?

Btw, num_witness and num_committee are part of voting; they are the user's votes for the number of witnesses and delegates the chain should appoint.

**Comment by svk31** [comment]
That should do it, thanks.
