### ISSUE TITLE
Deprecate annual membership

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#613]

**Comment by abitmore** [comment]
Why not fix it? Maybe simply make it 80% cash-back? Just need to store referrer and registrar info somewhere, restore/reuse them when membership expires.

**Comment by abitmore** [comment]
Anyway, IMHO it shouldn't be decided by developers alone. Having multi-level membership structure is a good pricing strategy, we'd better let stake holders make decisions on how to set it up. Labeling this ticket "NextRelease" without any description is a bit rushing.

**Comment by beyondbitcoin** [comment]
Agreed.

**Comment by xeroc** [comment]
The committee has raised the annual membership fee significantly in order to deactivate annual upgrades for now

**Comment by abitmore** [comment]
FYI theoreticalbts wrote a new post: [Why annual memberships are going away](https://bitsharestalk.org/index.php/topic,21846.0.html)

**Comment by theoreticalbts** [comment]
I meant to link that here, thanks.

**Comment by theoreticalbts** [comment]
Above commit allows you to replay the chain and log annual member registration events
