### ISSUE TITLE
feed_is_expired returns wrong value

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#615]
Partial fix pull request:  #614.   Some discussion:  #540.

**Comment by theoreticalbts** [comment]
Copy-pasted text from #540:

Fix #614 doesn't work as-is, and if it is modified to work correctly, won't fix this bug.

feed_is_expired() returns the opposite value of what's expected, but the caller takes that into account and does the thing that should be done if it is not expired when the feed_is_expired() return value is true.

So the proper fix would also have the caller check !feed_is_expired() instead of feed_is_expired() as currently, which would end up not changing any semantics.

What this fix effectively does (without the call site change) is mark all BitAssets as expired and stop updating the median feed. So I'm sure it will help with the websocket spamming problem, but it will also break all BitAssets!

**Comment by svk31** [comment]
Too bad :(

Surely there's a simple fix for the fact that bitasset objects that have not changed are marked as changed and pushed through the websocket though (https://github.com/cryptonomex/graphene/issues/540) ??

**Comment by dnotestein** [comment]
No, there's no simple solution that we're aware of, although we have an idea for a more complicated one involving changing the caching method used. But because it's non-trivial we decided to push it off to a later date, assuming that the 16x compression will likely solve the worst part of the problem for now.

**Comment by abitmore** [comment]
@theoreticalbts @dnotestein : IMO the correct logic should be:
- when a witness publishes a price feed, 2.4.x will be updated, so the client know the settle price changed.
- when time pass by, if no feed expired, the settle price shouldn't be updated and shouldn't notify clients. 
- when time pass by, if one feed expired, the settle price should be re-calculated, so send notification to clients. 

Why did you think (according to the code) when no feed is expired, we should still change the settle price in db?

**Comment by theoreticalbts** [comment]
Actually the problem is that `update_median_feeds()` is called every block, which unconditionally modifies the `asset_bitasset_data_object` for every MIA.

One solution might be to copy the `bitasset_data_object` onto the stack, run the in-place update on the copy, then only do `modify()` to write it into the database if it was changed.

**Comment by abitmore** [comment]
> What this fix effectively does (without the call site change) is mark all BitAssets as expired and stop updating the median feed. So I'm sure it will help with the websocket spamming problem, but it will also break all BitAssets!

What my fix does is when one **price feed** expired, call `update_median_feeds()` once. It's the correct logic.

> Actually the problem is that update_median_feeds() is called every block, which unconditionally modifies the asset_bitasset_data_object for every MIA.

IMO it's not needed to call update_median_feeds every block.

By the way, since in [the code](https://github.com/cryptonomex/graphene/blob/e3478d233847056943da6f84f18adcf18c42e64d/libraries/chain/db_update.cpp#L437-L443) also called `check_call_orders` at same (but wrong) time, the fix need a hard fork.

**Comment by abitmore** [comment]
Replay of current BTS chain will fail at block 25xxxx or 26xxxx with my previous fix (without hard fork logic).

**Comment by theoreticalbts** [comment]
Copy-pasted from #540:

On second thought @abitmore is right -- the logic is supposed to only update the feed when it expires, instead it is updating when the feed is non-expired, leading to many repetitions of objects (and non-updating when feeds expire).

This is definitely something that needs a hardfork -- if a feed ever expired and it wasn't updated, then someone did anything based on the non-updated feed value, subsequent balances would be different even if we could still sync.

**Comment by theoreticalbts** [comment]
We should be careful about whether to use `>=` or `>`.

Let `f` be a `pair<time_point_sec, price_feed>`.  We say `f` is _unexpired_ at time `t` iff `t < f.first + options.feed_lifetime_sec`; this is the condition that causes `f` to be thrown out in the recomputation loop in `update_median_feeds()`.  Given a set `F` of `f` values, the first `f` value to expire will expire at `m = min(f.first + options.feed_lifetime_sec)` minimized over `f in F`.  We instead store `m' = m - options.feed_lifetime_sec` in `current_feed_publication_time`.

When `t >= m` we have a dirty feed [1], so the correct answer is that the feed is dirty precisely when

```
t >= m
   = m' + options.feed_lifetime_sec
   = current_feed_publication_time + options.feed_lifetime_sec
   = feed_expiration_time()
```

which means that `feed_is_expired(t)` should return `true` when `t >= feed_expiration_time()`, as the implicit contract is that `feed_is_expired(t)` whenever it's dirty [1].

[1] With respect to `update_median_feeds()`
(i.e. `is_expired(t)` is `true` for precisely those `t` for which `update_median_feeds(t)` will throw out at least one value).

**Comment by abitmore** [comment]
The logic about `>=` or `>` in my code is aligned with which in `update_median_feeds()`: when the two times equal to each other, the feed is expired. 

I've pushed some hard fork code which is assigned with number 540, need to change them to 615 (this ticket)?

**Comment by theoreticalbts** [comment]
Basically the above post was me convincing myself that it's doing what it's intended to do (which is to prove whether `update_median_feeds()` would be a no-op).  Go ahead and change them to 615, then do `git rebase -i 529f0bef0eeaef6424c6ff10cbb6415c35b7fe03` and `squash` (or `fixup`) all but the first commit (no reason for this to be multiple ~~patches~~ commits).

**Comment by abitmore** [comment]
You mean at the end we'll have the first commit (which has been merged to develop branch), and one more commit?

**Comment by kenCode-de** [comment]
aah snap, wasn't this websocket spamming too much data issue gonna be fixed with tomorrow's hardfork?

**Comment by abitmore** [comment]
> aah snap, wasn't this websocket spamming too much data issue gonna be fixed with tomorrow's hardfork?

Yes, it will be fixed with tomorrow's hardfork.
