### ISSUE TITLE
Witness node crash on startup when DNS resolution fails

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#618]
It's an old known issue anyway, just record it here so it will get fixed at some time. Not urgent imo.

```
431050ms th_a       application.cpp:461           startup              ] 0 exception: unspecified
process exited with: Host not found (authoritative) 
    {"message":"Host not found (authoritative)"}
    asio  asio.cpp:88 resolve_handler

    {}
    th_a  asio.cpp:160 resolve

    {"endpoint_string":"seed.cubeconnex.com:1777"}
    th_a  application.cpp:221 resolve_string_to_ip_endpoints

    {}
    th_a  application.cpp:195 reset_p2p_node
```

**Comment by abitmore** [comment]
<del>Need to cherry-pick commit https://github.com/abitmore/bitshares-2/commit/8d800045459a98fc43b6de72757f4130d07b276f to develop branch. Other commits are not compatible.</del>

//Update:
Above comment is incorrect.
Need to cherry-pick commit https://github.com/abitmore/bitshares-2/commit/39a5805491e172107a2d662624145f95fdd06ed6 to develop branch. Other commits are not compatible.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#190
