### ISSUE TITLE
revise license and double-check all file header licenses

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#62]
Switch to finalized license for both Graphene and BitShares 2.0, and make sure it's present in the head of all files (some are probably naked by now after all the churn).

**Comment by nathanielhourt** [comment]
What's the task here?

**Comment by vikramrajkumar** [comment]
Edited the OP with description; assigned it to you just cause you originally inserted all the license headers.

**Comment by nathanielhourt** [comment]
Do we have a finalized license?

**Comment by vikramrajkumar** [comment]
No that still needs to be decided. I've moved this to DVS milestone now.

**Comment by theoreticalbts** [comment]
Closing this, as the license was set when we released.
