### ISSUE TITLE
cli_wallet: get_market_history returns earliest buckets, not latest buckets

### ISSUE THREAD

**Issue by roadscape** [cryptonomex/graphene#620]
On a fresh install, via cli_wallet:

```
get_market_history BTS USD 3600
---snip----
    "id": "5.1.2706",
    "key": {
      "base": "1.3.0",
      "quote": "1.3.121",
      "seconds": 3600,
      "open": "2015-10-29T07:00:00"
    },
---snip---
    "id": "5.1.4048",
    "key": {
      "base": "1.3.0",
      "quote": "1.3.121",
      "seconds": 3600,
      "open": "2015-11-05T05:00:00"
    },
    ---snip---
  }
]
```

The history cuts out a week ago even though there's been plenty of activity, so it appears as though it returns the first 200(?) buckets, not the most recent buckets.

Also, I think it may be ignoring the `history-per-size` parameter in config.ini.

**Comment by abitmore** [comment]
The 200 is a [hard coded limit](https://github.com/bitshares/bitshares-2/blob/2.0.160316b/libraries/app/api.cpp#L471) in history api. 

The `get_market_history` API comes with no document. Current implementation returns the first 200 records. So.. what's the best behavior? Probably we need a BSIP for it?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#191
