### ISSUE TITLE
In debug_node, current_feed_publication_time resets on reload

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#624]
I think this wasn't found because `check_reflect.py` might not be checking object classes.

Related: #615

**Comment by theoreticalbts** [comment]
Wait a minute, it is reflected after all lower down...but it is not loading properly for some reason.

Reproduction steps:  Generate blocks, check 2.4.x, reload, check 2.4.x again, `current_feed_publication_time` is reset.

**Comment by theoreticalbts** [comment]
NB this occurred on a chain consisting of BitShares, plus a week's worth of empty blocks produced by `dbg_generate_blocks`.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#194
