### ISSUE TITLE
Account_update_operation requires both owner authorities and active authorities when owner presents

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#628]
When specified `owner` in `account_update_operation`, witness_node asks for both owner authorities and active authorities for signing the transaction. Worse case is when active authorities contain multiple keys but not all keys are in the wallet, even if the transaction is signed with owner key, sometimes it will still be rejected by witness_node. IMO active authorities is not needed in this case. 

We need a clear specification about owner/active authorities, not just concepts like https://bitshares.org/technology/dynamic-account-permissions/.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#197
