### ISSUE TITLE
transaction.cpp check_authority() recursion end issue

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#631]
In _transaction.cpp_, [this line](https://github.com/bitshares/bitshares-2/blob/2.0.160316b/libraries/chain/protocol/transaction.cpp#L196) should not `return false`, but `continue`.

Test case (see testnet http://testnet.bitshares.eu/#/account/level00/permissions/):
- Global `max_authority_depth` is 2
- Create some accounts and set active permissions as: `level00` -> `level0` -> `level1` -> `level2-1`/`level2-3`
- Propose a proposal to transfer 1 `TEST` from `level00` to `level0`
- Approve the proposal by `level2-3`, the proposal doesn't execute
- Approve the proposal by `level2-1`, the proposal executes

**Comment by theoreticalbts** [comment]
This is a hardforking change.

**Comment by abitmore** [comment]
Yes, it is. Will add hard fork logic (and probably rebase).

**Comment by bytemaster** [comment]
great catch abit.

**Comment by theoreticalbts** [comment]
After some discussion we've decided that the hardfork patch above is rather complex and needs a ton of testing to validate, and it's actually better to just port abit's one-liner.

**Comment by abitmore** [comment]
It would be OK if nobody tried that in live network. However testnet will be broken anyway.. @xeroc any idea?

**Comment by xeroc** [comment]
testnet's purpose is to break things .. finally a success .. 
it's probably less work to just patch this hard fork in the testnet and continue as usual :)
