### ISSUE TITLE
[Request] Require owner key for change of asset-issuer

### ISSUE THREAD

**Issue by xeroc** [cryptonomex/graphene#635]
Since an asset's issuer can be changed by the issuer and we want to have a solid cold storage solution to secure accounts and assets, I think it makes most sense to require a valid signature of the **owner** key for changes to the asset-issuer.

Currently, AFAIK, only the active authority is required. If that key gets stolen, an asset can be handed over to an account that is no longer under proper control.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#199
