### ISSUE TITLE
Balance computation in the wrong place in verify_asset_supplies()

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#639]
Test that asset supply is correct is [here](https://github.com/cryptonomex/graphene/blob/006d54863312c7daf1ccb73d5940ec658c860efb/tests/common/database_fixture.cpp#L188-L189) but `total_balances` is concurrently modified in the loop and additional modifications take place [below](https://github.com/cryptonomex/graphene/blob/006d54863312c7daf1ccb73d5940ec658c860efb/tests/common/database_fixture.cpp#L197-L202) the loop.

They're probably working because it only matters for core asset, which is tested separately outside the loop at the end.

Cleaner design is to consistently test everything at the end after all modifications, and add `confidential_supply` to the supply instead of subtracting it from the expected supply.  This allows the CORE supply check to not be special-cased. 

The fact that this code works reveals some deficiencies in our test suite, for example we don't test stealth tx's or VBO's with non-CORE asset.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#201
