### ISSUE TITLE
Update README with new wallet instructions

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#64]
The instructions for getting up and running in `README.md` include instructions for setting a wallet password.  These instructions no longer work.

**Comment by emfrias** [comment]
Still works for me (tested at rev 3eaec849eb6fce46c80cbae087a719cadff6efe2).  Maybe you had a old wallet.json in your directory?

```
~/src/graphene/programs/cli_wallet$ ./cli_wallet
Please use the set_password method to initialize a new wallet before continuing
new >>> set_password password
set_password password
null
locked >>> unlock password
unlock password
null
unlocked >>>
```

**Comment by theoreticalbts** [comment]
Yep, looks like it was an old `wallet.json`.
