### ISSUE TITLE
Hard fork request: correct wrong voting proxy settings

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#640]
Due to [a GUI bug](https://github.com/cryptonomex/graphene-ui/issues/700), many accounts have `committee-account` as voting proxy (see the "_Followers_" section of https://cryptofresh.com/u/committee-account). This ticket is to request a hard fork to correct them to `proxy-to-self`.

The GUI bug has been fixed.

**Comment by pmconrad** [comment]
What is the benefit of "fixing" these accounts via a hardfork?
Is that benefit worth the effort + risk associated with a hardfork?

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#202
