### ISSUE TITLE
Hard fork request: re-enable some permission settings of TCNY

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#641]
Due to a GUI bug, some permissions/flags of TCNY are accidentally disabled and hard if not unable to enable again. This ticket is for re-enabling these permissions/flags, just set them to same as CNY.

Earlier discussion is here: https://bitsharestalk.org/index.php?topic=20870.0.

**Comment by abitmore** [comment]
Update: according to https://github.com/cryptonomex/graphene-ui/issues/737, the GUI bug has been fixed.

**Comment by pmconrad** [comment]
This is problematic, IMO. Issuer permissions define certain guarantees on what the issuer can or cannot do wrt an asset. Changing these guarantees requires the consent of _all_ holders of the asset.

Apparently in this case what hurts most is the missing flag to allow witnesses to provide a price feed. A workaround exists (?), from which two conclusions follow:
1. the requested hardfork is not necessary, and
2. the requested hardfork, if limited to the the witness_fed_asset flag, does not change the effective guarantees on the asset and might therefore be seen as acceptable.

**Comment by theoreticalbts** [comment]
@pmconrad is absolutely correct.  The idea of permissions is "These are the rules, and the blockchain won't allow the issuer to change the rules on you later."

A recent hardfork #572 allows assets with no float to change issuer permissions.  So if you can destroy all the existing float of the asset, you can fix the problem.

**Comment by abitmore** [comment]
Let the asset holders decide, or let the core asset holders decide (voting)? Anyway it's caused by a GUI bug, so imo fixing it with a hard fork is acceptable.

It's a private smart coin, not a UIA, how to make it "no float"? Global settle?

**Comment by xeroc** [comment]
@abitmore global settlements are irreversible (another thing that needs to be discussed eventually). So, once globally settled, the asset is is practically unusable.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#203
