### ISSUE TITLE
`virtual_op` in `operation_history_object`?

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#644]
There is a `virtual_op` field in `operation_history_object`, related code is [here](https://github.com/cryptonomex/graphene/blob/2.0.160316b/libraries/chain/include/graphene/chain/operation_history_object.hpp#L64). Questions:
- what's the supposed use case of this data? I noticed recently it's used in GUI to sort account history, which is introduced as [a fix](https://github.com/cryptonomex/graphene-ui/commit/57c178d01f18590fb0766088c01a09ebac9778b9) of [issue 793](https://github.com/cryptonomex/graphene-ui/issues/793).
- however, in witness_node, this data is filled with the variable `_current_virtual_op` in `database.hpp` with [this code](https://github.com/cryptonomex/graphene/blob/2.0.160316b/libraries/chain/db_block.cpp#L446),  but `_current_virtual_op` has never been saved to or loaded from disk. So if `witness_node` is started without `--replay-blockchain`, `_current_virtual_op` is reset to 0, then every new `operation_history_object` saved to database contains a `virtual_op` value which would be already assigned to an old `operation_history_object`<s>, thus the logic in above fix is not totally reliable</s>.

Thoughts?

//Edit: logic in the GUI fix is correct, because it compares `block_num` first, then compares `virtual_op`.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#206
