### ISSUE TITLE
Duplicate keys in config.ini breaks logging

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#648]
If your witness_node doesn't write logs, please check if there is this message while starting witness:

> 448168ms th_a       main.cpp:121                  main                 ] Error parsing logging config from config file xxx/witness_node_data_dir/config.ini, using default config

it probably caused by duplicated keys in config.ini, for example:

```
checkpoint = [2821600, "002b0de0540f7625fe55baf29583b3f45e8b23e9"]
checkpoint = [2821650, "002b0e12cb488ac912504dd483eaa92991fa3b3e"]
checkpoint = [2821700, "002b0e446a72ada002bfdc65fb4ab5fbd29763a1"]
```

or

```
seed-node = "1.2.3.4"
seed-node = "1.2.3.5"
```

**Comment by abitmore** [comment]
or

```
private-key = ["pub1","wif1"]
private-key = ["pub2","wif2"]
```

**Comment by abitmore** [comment]
Duplicate of #521

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#209
