### ISSUE TITLE
Seed node stuck issue

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#654]
A seed node will get stuck if an exception is thrown out while accepting a new connection. When it's stuck, the TCP port is still open/listening, but it doesn't respond with a `hello` message when other peers connected to it, nor do further communication.

This issue occurs rather frequently in BitShares network recently.

Reference: 
- [BitSharesTalk forum post](https://bitsharestalk.org/index.php/topic,22385.msg291611.html#msg291611)
- [Seed node status page](http://status.bitsharesnodes.com/)

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#213
