### ISSUE TITLE
Memo fields are all failing to decrypt now

### ISSUE THREAD

**Issue by ByronAP** [cryptonomex/graphene#656]
every transaction is now throwing

"Memo is encrypted to a key BTS************\* or BTS***********\* not in this wallet."

this is causing me hell since the exchange relies on the memo field to credit users accounts.

(windows cli wallet)

**Comment by svk31** [comment]
We recently made some changes to how the GUI handles memos but it was only intented to ensure full compatibility with the CLI wallet, which was not the case earlier due to an edge case. 

See https://github.com/cryptonomex/graphene-ui/pull/849 for details.

Which version of the CLI wallet are you using?

**Comment by ByronAP** [comment]
cli was 2 version behind and just upgraded to the latest but it is still doing it

**Comment by abitmore** [comment]
Try `get_block block_num` in CLI, you'll see what keys are used to encrypt the memos, for example

```
            "memo": {
              "from": "BTS8bYMsSFQ7M2jGhZJvG9WDumtF9Ku99VE3a9azHzTrKLoKiGRGU",
              "to": "BTS7SakKqZ8HamkTr7FdPn9qYxYmtSh2QzFNn49CiFAkdFAvQVMg6",
              "nonce": "374816006311167",
              "message": "088d240a593e58ea74f428321de7d9c8"
            },
```

then try `dump_private_keys` to check if you have the correct keys in the wallet.

**Comment by ByronAP** [comment]
I checked everything, it has the associated keys. I even tried sending from the gui wallet to my cli wallet and the gui can decrypt the message I sent but the cli wallet fails to decrypt even though the key is shown when I dump the private keys.

**Comment by ByronAP** [comment]
just tried on a 2nd machine with a different cli wallet and it throws the same error

**Comment by ByronAP** [comment]
apparently the gui can decrypt the memos but the cli wallet cant...

**Comment by Alok123456** [comment]
hey, i am running graphene-ui app in my localhost in ubuntu 16.04 and trying to create account in that but its giving me some errors.What should i do now to cure that.

**Comment by abitmore** [comment]
> hey, i am running graphene-ui app in my localhost in ubuntu 16.04 and trying to create account in that but its giving me some errors.What should i do now to cure that.

@Alok123456 Please create a new issue, describe your questions in detail, E.G. what are those "some errors".

**Comment by Alok123456** [comment]
hey, i am running graphene-ui app in my localhost in mozilla on ubuntu 16.04 but it keeps on throwing me on init-error page i.e on this link [http://localhost:8080/#/init-error](url). 
And providing me several errors as well which are here below in provide screen shot.
![screenshot from 2016-11-25 12-38-35](https://cloud.githubusercontent.com/assets/20416373/20616995/1e547926-b30c-11e6-9c81-e0bc2d613cef.png)
I have disabled the flag in mozilla as well by making "network.websocket.extensions.permessage-deflat" as false but still i am not getting any improvement with that.

**Comment by xeroc** [comment]
the graphene-ui repo is **not compatible** with the peerplays network .. please use **their** graphene-ui fork and **their** issue tracker.
