### ISSUE TITLE
Unable to propose a proposal with an `approve_proposal` operation

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#658]
Got this message while trying to propose a proposal with an `approve_proposal` operation:

```
10 assert_exception: Assert Exception
other.size() == 0:
    {}
    th_a  proposal_evaluator.cpp:54 do_evaluate
```

The issue is probably caused by lack of size checking on `auth.key_auths` before [this line in proposal.cpp](https://github.com/cryptonomex/graphene/blob/2.0.160328/libraries/chain/protocol/proposal.cpp#L92), imo the code could be

```
if( auth.key_auths.size() > 0 )
   o.emplace_back( std::move(auth) );
```

To fix this issue, a hard fork is needed.

**Comment by abitmore** [comment]
Actually it should be `proposal_update_operation` (and if to add an account authority to "approve" the proposal).

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#214
