### ISSUE TITLE
Getting started - What parameters to set?

### ISSUE THREAD

**Issue by VinzentE** [cryptonomex/graphene#661]
Hi there,

we are having a hard time getting started with graphene / bitshares. 

It would be fantastic if anyone can point us to the right direction for:
1.  what are all the parameter that can be set for the blockchain / graphene?
2.  what are the pre-existing smart contracts that can be used "out of the box" and where do we finde each ones parameters?
3. where do we find information on who is allowed to set these parameters in which conditions? E.g. Number of witnesses can only be changed by votes from deligates if they are >51% ... 

Thanks a lot,

Vinz

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#215
