### ISSUE TITLE
Cherry-pick the block timestamp validation patch to develop branch

### ISSUE THREAD

**Issue by abitmore** [cryptonomex/graphene#662]
[This commit](https://github.com/bitshares/bitshares-2/commit/2cf8fb62c98befb70fedffe739a05bc4ac5a0de8) need to be cherry-picked to develop branch. Related: #645

**Comment by xeroc** [comment]
https://github.com/cryptonomex/graphene/commit/ead2db3272f75fd477a7ed64b56427c29c54ec02
