### ISSUE TITLE
Bitshares issue

### ISSUE THREAD

**Issue by faddat** [cryptonomex/graphene#665]
BTS2.0 repository is just a clone of graphene's repository, and one of the consequences of thsi is that there are no issues.  BTS issues are not necessairly graphene issues, however, and so I recommend that we try and address this.  

Plus, my original reason for this posting altogether:  

How to build the bts2.0 gui client?

**Comment by xeroc** [comment]
@vikramrajkumar do you think it makes sense to separated the bitshares branch from the graphene repo? I suppose it makes things more complicated. Anyway, I do agree that we should have a bitshares specific issue tracker.

@faddat the bts gui is in another repo called bitshares-2-ui .. it is a web wallet and can be compiled as described here: http://docs.bitshares.eu/testnet/6-webwallet.html

**Comment by vikramrajkumar** [comment]
@xeroc I think it may be inevitable that the bitshares-2 repo will continue to diverge from this graphene repo unless Cryptonomex begins maintaining it again. I think this is fine and the bitshares-2 repo will be my focus. I've also enabled the issue tracker https://github.com/bitshares/bitshares-2/issues

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-core#217
