### ISSUE TITLE
Add description/name/url fields for workers/delegates/witnesses

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#67]

**Comment by vikramrajkumar** [comment]
127 characters for a URL seems extremely short.

**Comment by bytemaster** [comment]
We don't want really long URLs.  Worst case they can use tinyurl, but generally speaking these entities should have their own domain names or could have something like:  delegatename.github.io as their website.   There is no reason why a delegate should need a LONG url.

**Comment by nathanielhourt** [comment]
I went ahead and threw the URLs into the fee calculation anyways. They should have no effect, since the data fee only applies in 1024-byte chunks anyways.

Is this issue resolved?

**Comment by nathanielhourt** [comment]
TODO: add to the objects in memory
