### ISSUE TITLE
Cleanup and finish advanced UIA features

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#7]
current code somewhat matches original bitshares advanced uia attempt and can be improved

e.g. whitelist handling can be streamlined more

also explicitly handle that there are at least 3 different asset types in the system: core, uia, and mia

Also need to figure out UIA retraction

**Comment by bytemaster** [comment]
Can we get more specific in this issue?  What items are unimplemented an what cases need to be reviewed?   

Retraction has already been implemented.

**Comment by vikramrajkumar** [comment]
Upon review, specific work is no longer necessary. Subsuming this into: #75
