### ISSUE TITLE
Define denominators for all fractional fields

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#70]
I noticed this in `asset.hpp`:

```
  /** Fixed point between 1.000 and 10.000 */
  uint16_t maintenance_collateral_ratio = GRAPHENE_DEFAULT_MAINTENANCE_COLLATERAL_RATIO;

  /** Fixed point between 1.000 and 10.000 */
  uint16_t maximum_short_squeeze_ratio = GRAPHENE_DEFAULT_MAX_SHORT_SQUEEZE_RATIO;
```

We need to define denominator constants for these fractions.  In general we need to review the code for places where fields representing fractional quantities assume denominators, and define explicit denominator constants for all of these places.

**Comment by bytemaster** [comment]
The denominator was defined implicitly, by the 0.000 precision in the comment.
