### ISSUE TITLE
Check signatures during reindexing when consensus rules change or participation is low

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#71]

**Comment by nathanielhourt** [comment]
What's the "correct" way to determine the participation? I can determine global participation rate by taking `head_block_num() / witness_schedule_object->slots_since_genesis` but this probably isn't a good metric. We'd rather have participation in the last round. I could calculate this by looking at the block header from 1 round ago and doing `round_size / ((head_block_time() - old_header.timestamp) / block_interval)`. Does anyone know of a better way / one that doesn't break if the interval changes? Do we want to look at just the last round or the last N rounds?
