### ISSUE TITLE
Do core shares locked in contracts still vote on behalf of the owning account?

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#72]

**Comment by theoreticalbts** [comment]
It should be in `account_statistics_object::total_core_in_orders`.  We should add a supply check to the DB fixture in the unit tests, verifying that `total_core_in_orders` plus account balances plus reserve equals `GRAPHENE_MAX_SHARE_SUPPLY`.

**Comment by bytemaster** [comment]
That check is already there in every test.  
If a contract has a clear owner then the stake votes
