### ISSUE TITLE
Does the feed price update when the set of producers change or when a feed expires?

### ISSUE THREAD

**Issue by vikramrajkumar** [cryptonomex/graphene#73]

**Comment by bytemaster** [comment]
The feed price updates every time a feed is published, but not when a feed expires.

**Comment by vikramrajkumar** [comment]
What about when the set of producers change?

**Comment by nathanielhourt** [comment]
The median feed values are updated when a feed is published, when the set of producers changes, _and_ when a feed expires. See https://github.com/cryptonomex/graphene/blob/master/libraries/chain/asset_evaluator.cpp#L309, https://github.com/cryptonomex/graphene/blob/master/libraries/chain/asset_evaluator.cpp#L426, https://github.com/cryptonomex/graphene/blob/master/libraries/chain/db_update.cpp#L226
