### ISSUE TITLE
I see that the secp256k1-zkp library has configuration options hard coded instead of using the ./configure 

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#76]
I see that the secp256k1-zkp library has configuration options hard coded instead of using the ./configure script:
https://github.com/cryptonomex/fc/blob/master/CMakeLists.txt
https://github.com/ElementsProject/secp256k1-zkp

That is causes build errors on some systems:
In file included from /home/pi/graphene/graphene/libraries/fc/vendor/secp256k1-zkp/src/secp256k1.c:11:0:
/home/pi/graphene/graphene/libraries/fc/vendor/secp256k1-zkp/src/util.h:102:37: error: ‘__int128’ is not supported for this target
 SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t;

since not all architectures have __int128

just running ./autogen.sh and ./configure then make works in that folder, but the fc cmake build does not work

I know it's early and it's probably just set up for testing at this point, but I wanted to give a heads up.

**Comment by vikramrajkumar** [comment]
https://bitsharestalk.org/index.php/topic,17156.msg219199.html#msg219199

**Comment by maqifrnswa** [comment]
This commit is at least a starting point:
https://github.com/maqifrnswa/fc/commit/f6bd3274c408fddc9ab48a62b545c74fe4afb33b
I'm testing now - it will obviously be optimized for everyone's  individual machine, maybe some performance increase there.

**Comment by maqifrnswa** [comment]
~~A bug in the above diff, it needs a "include_directories(libraries/fc/vendor/secp256k1-zpk/include)" -- I don't have it the above diff. If it's helpful, great - but if not, that's find too, hopefully it helps~~

Below PR has the correct includes and works.
