### ISSUE TITLE
Audit leveldb removal artifacts

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#78]
The `peer_database.cpp` contains this snippet, which is causing a compiler warning for some:

```
  else
  {
    uint32_t last_database_key;
    //_leveldb.last(last_database_key);
    uint32_t new_database_key = last_database_key + 1;
    potential_peer_database_entry new_database_entry(new_database_key, updatedRecord);
    _potential_peer_set.get<endpoint_index>().insert(new_database_entry);
    //_leveldb.store(new_database_key, updatedRecord);
  }
```

This should really be an error.  Commit ca89d505 is the culprit.  Someone needs to audit that commit and find the obvious bugs it introduced -- the commit message implies this may not be the only one.

**Comment by vikramrajkumar** [comment]
@theoreticalbts I have removed all remaining traces of LevelDB (see https://github.com/cryptonomex/graphene/commit/34388fabee6989cf18eb4838fc6fc063c7f00f38) except in the `net` folder, which I have left to @emfrias who has been making his fixes in the `remove_leveldb` branch.

**Comment by emfrias** [comment]
My mistake, I thought someone else was merging that branch.  I've merged my changes into master.

**Comment by vikramrajkumar** [comment]
https://github.com/cryptonomex/graphene/compare/a0765e2cf2...37cadb2be8
