### ISSUE TITLE
Create asset with distribution Acc. to snapshot.

### ISSUE THREAD

**Issue by pureland** [cryptonomex/graphene#80]
I am a fans of this project , I don`t know if you`d like to supply following function  
Create asset with distribution Acc. to snapshot.
1.snapshot file is stored parallel with block-chain 
2.hash of snapshot is stored in operation of creating asset .
3.full node would download snapshot file ,and valid hash.

**Comment by theoreticalbts** [comment]
If you want to issue a UIA, you must issue the UIA to all accounts you want to have the UIA.
