### ISSUE TITLE
Add more extensive invariant checks to unit tests

### ISSUE THREAD

**Issue by theoreticalbts** [cryptonomex/graphene#82]
We should provide a rigorous mode to check invariants at each op, each tx, or each block.  This can be used as a debugging tool on both test cases and live networks.

**Comment by vikramrajkumar** [comment]
Related: #11

**Comment by bytemaster** [comment]
Can we define the requirements for closing this issue, are these checks just added to the unit tests or should we add them to normal blockchain validation.  Some checks might be too expensive to perform in real time if we have 100K or more accounts.  

If this isn't well defined then we need to close the issue.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-2#30
