### ISSUE TITLE
Audit Fee handling of BitAssets managed by delegates.

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#83]
- [x] If the collateral is CORE make sure the fee pool ratio is updated via the price feed.
- [x] If the collateral is another BitAsset then recursively apply the fee pool ratios until a price per CORE is found
- [ ] ~~Using the fee pool price ratio, calculate the value of all fees in the BitAsset in terms of core, if the value of the collected fees is higher than a threshold defined by chain parameters, then liquidate the collected BitAsset fees for the collateral.   If the collateral is another BitAsset then add the proceeds to that BitAssets fees and repeat until the fees have been converted to CORE.~~
- [ ] ~~Generally speaking the delegates shouldn't be creating any BitAssets that are not ultimately backed by CORE which means this process will work for all network based BitAssets.   This process should not be applied for assets issued by others.~~
  (Previous 2 are WONTFIX for now; maybe we'll do them later if stakeholders want it)
- [x] Only perform `core_exchange_rate` update on maintenance intervals.

**Comment by nathanielhourt** [comment]
First two components are completed by #94.

**Comment by nathanielhourt** [comment]
Actually, we're going to restrict the `core_exchange_rate` updates to the maintenance interval, to keep fees predictable.
