### ISSUE TITLE
Add core_exchange_rate to price feed

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#94]
Any BitAsset that wishes to be used to pay fees requires a feed pool and a valid core_exchange_rate, the core_exchange_rate may be different than the settlement_price, especially if the collateral is not CORE. 

The issuer gets to appoint the feed producers, so having the producers set the exchange rate via median like they do the settlement price is fine.   The core exchange rate can favor the issuer to cover the cost of maintaining the fee pool and/or to make some extra profit for the issuer.

The issuer's private_keys should be kept more secure than the keys in charge of producing feeds which must remain hot all of the time on an automated server.

**Comment by bytemaster** [comment]
The wallet API for publishing a price feed needs to be updated to handle this as well

**Comment by vikramrajkumar** [comment]
Duplicate #83 ?
