### ISSUE TITLE
Create Balance Object + Simple Claim Operation for Snapshot

### ISSUE THREAD

**Issue by bytemaster** [cryptonomex/graphene#98]
Rather than creating many accounts, simply migrate the balance objects to make it easier to initialize the genesis condition and to free up memory after they have been claimed.

**Comment by bytemaster** [comment]
TODO: verify that owner signature is on the transaction and implement tests.

**Comment by bytemaster** [comment]
My initial testing of the balance claim in the wallet shows that it is working.   What remains to be done on this?

**Comment by nathanielhourt** [comment]
Still need to do some anti-spam on the vesting withdrawals, and test them.
